<?php
    $_productCollection = $this->getLoadedProductCollection();
    $_helper            = $this->helper('catalog/output');
    $_collectionSize    = $_productCollection->count();
    $_columnCount       = $this->getColumnCount();
?>
<?php if (!$_collectionSize) : return; endif; ?>

<div class="category-products block-highlight <?php echo $this->getClassName() ?>">
    <div class="block-title"><span><?php echo $this->__($this->getTitle()) ?></span></div>
    <div class="block-content">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid cols-<?php echo $_columnCount ?>">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">

				<h2 class="product-name"><a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>

				<span class="description" style="">
					<?php echo $_product->getShortDescription(); ?>
				</span>

                <a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(210); ?>" width="210" height="210" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>

                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>

                <?php echo $this->getPriceHtml($_product, true, $this->getPriceSuffix()) ?>


                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
						<form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId()?>"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
							<?php //if(!$_product->isGrouped()): ?>
							<div class="divQtd">
								<!--														<label for="qty">--><?php //echo $this->__('Qty') ?><!--:</label>-->
								<input type='button' value='-' class='qtyminus' field='qty-<?php echo $_product->getId(); ?>' />
								<input type='text' name='quantity' value='12' class='qty' id="qty-<?php echo $_product->getId(); ?>"/>
								<input type='button' value='+' class='qtyplus' field='qty-<?php echo $_product->getId(); ?>' />
							</div>
							<?php //endif; ?>
							<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="addToCart('<?php echo $this->getAddToCartUrl($_product) ?>', <?php echo $_product->getId(); ?>)"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
						</form>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last']);</script>
    </div>
</div>
