<?php

$blankFields = array();

$formErrors = $this->getParentBlock()->formErrors;
$formErrors = (!empty($formErrors['billing_errors'])) ? $formErrors['billing_errors'] : array();

$helper = Mage::helper('onestepcheckout/checkout');
$dataHelper = Mage::helper('onestepcheckout');

$customer = $this->getCustomer();

if ($this->customerHasAddresses()) {
    $address = $customer->getDefaultBillingAddress();
} else {
    $address = $this->getQuote()->getBillingAddress();
}

    $billingFields['address_id'] = '<li class="no-display"><input type="hidden" name="billing_address_id" id="billing_address_id" value="'.$address->getId().'" /></li>';

    $billingFields['firstname'] = '
        <li class="fields">
          <div class="field">
            <div class="input-box input-firstname'.((in_array('firstname', $formErrors)) ? ' input-error' : '').'">
                <label for="billing:firstname">'.$this->__('First Name').' <span class="required">*</span></label>
                <input class="required-entry form-control" type="text" name="billing[firstname]" id="billing:firstname" value="'.$dataHelper->clearDash($customer->getFirstname()).'" '.(($dataHelper->clearDash($customer->getFirstname()) != '') ? 'readonly="readonly"' : $blankFields[] = 'firstname').' />
            </div>
           </div>';
    $billingFields['lastname'] = '
          <div class="field">
            <div class="input-box input-lastname'.((in_array('lastname', $formErrors)) ? ' input-error' : '').'">
									<label for="billing:lastname">'.$this->__('Last Name').' <span class="required">*</span></label>
                <input class="required-entry form-control" type="text" name="billing[lastname]" id="billing:lastname" value="'.$dataHelper->clearDash($customer->getLastname()).'" '.(($dataHelper->clearDash($customer->getLastname()) != '') ? 'readonly="readonly"' : $blankFields[] = 'lastname').' />
            </div>
           </div>
        </li>';
    ?>
<?php if(!$this->isCustomerLoggedIn() || in_array('email_registered', $formErrors)): ?>
    <?php $billingFields['email'] = '
        <div class="clearfix" id="onestepcheckout-email-error" '.((!in_array('email_registered', $formErrors)) ? 'style="display: none"' : '').'>
            <div id="onestepcheckout-email-error-message" class="onestepcheckout-error">'.
                ((in_array('email_registered', $formErrors)) ? $this->__('Email address already registered. Please <a href="#" onclick="login_popup.show(); return false;">login now</a> or use a different email address.') : $this->__('Invalid email address.'))
            .'</div>
        </div>';
    ?>
<?php endif; ?>
<?php /*if(!$this->isCustomerLoggedIn()):*/ ?>
		<?php if(!isset($billingFields['email'])) : ?>
			<?php $billingFields['email'] = null; ?>
		<?php endif; ?>
			<?php $billingFields['email'] = $billingFields['email'].'
				<li class="wide">
					<label for="billing:email">'.$this->__('Email Address').' <span class="required">*</span></label><br />
					<div class="input-box input-email'.((in_array('email', $formErrors)) ? ' input-error' : '').'">
							<input type="text" readonly="readonly" name="billing[email]" id="billing:email" value="'.$dataHelper->clearDash($customer->getEmail()).'" title="'.$this->__('Email Address') .'" class="validate-email required-entry form-control" />
					</div>
				</li>';
			?>

<?php /*endif;*/ ?>

<?php $billingFields['cpf'] = '
    <li class="fields">
      <div class="field">
        <div class="input-box input-cpf'.((in_array('cpf', $formErrors)) ? ' input-error' : '').'">
            <label for="billing:cpf">'.$this->__('CPF').' <span class="required">*</span></label><br/>
            <input type="text" name="billing[cpf]" value="'.$dataHelper->clearDash($customer->getCpf()).'" title="'.$this->__('CPF').'" class="required-entry form-control billing_cpf" id="billing:cpf" '.(($dataHelper->clearDash($customer->getCpf()) != '') ? 'readonly="readonly"' : $blankFields[] = 'cpf').' />
        </div>
      </div>';
?>


<?php if(!$this->settings['exclude_telephone']):?>
    <?php $billingFields['telephone'] = '
      <div class="field">
        <div class="input-box input-telephone'.((in_array('telephone', $formErrors)) ? ' input-error' : '').'">
            <label for="billing:telephone">'.$this->__('Telephone').' <span class="required">*</span></label><br/>
            <input type="text" name="billing[telephone]" value="'.$dataHelper->clearDash($address->getTelephone()).'" title="'.$this->__('Telephone').'" class="required-entry form-control billing_telephone" id="billing:telephone" '.(($dataHelper->clearDash($address->getTelephone()) != '') ? 'readonly="readonly"' : $blankFields[] = 'telephone').' />
        </div>
      </div>';
    ?>
<?php endif; ?>

<?php /*var_dump($customer->getAttribute('tipopessoa')->getFrontend()->getValue($customer));*/ ?>
<?php if ($customer->getTipopessoa() == 'pet' || $customer->getTipopessoa() == 'both') : ?>

    <?php $billingFields['nomefantasia'] = '
      <li><h6>Dados do Petshop</h6></li>
      <li class="fields">
        <div class="field">
          <div class="input-box input-nomefantasia'.((in_array('nomefantasia', $formErrors)) ? ' input-error' : '').'">
              <label for="billing:nomefantasia">'.$this->__('Nome fantasia').' <span class="required">*</span></label><br/>
              <input type="text" name="billing[nomefantasia]" value="'.$dataHelper->clearDash($customer->getNomefantasia()).'" title="'.$this->__('Nome Fantasia').'" class="required-entry form-control" id="billing:nomefantasia" '.(($dataHelper->clearDash($customer->getNomefantasia()) != '') ? 'readonly="readonly"' : $blankFields[] = 'nomefantasia').' />
          </div>
        </div>';
    ?>

    <?php $billingFields['razaosocial'] = '
        <div class="field">
          <div class="input-box input-razaosocial'.((in_array('razaosocial', $formErrors)) ? ' input-error' : '').'">
              <label for="billing:razaosocial">'.$this->__('Razão social').' <span class="required">*</span></label><br/>
              <input type="text" name="billing[razao_social]" value="'.$dataHelper->clearDash($customer->getRazaoSocial()).'" title="'.$this->__('Razão social').'" class="required-entry form-control" id="billing:razaosocial" '.(($dataHelper->clearDash($customer->getRazaoSocial()) != '') ? 'readonly="readonly"' : $blankFields[] = 'razaosocial').' />
          </div>
        </div>
      </li>';
    ?>

    <?php $billingFields['cnpj'] = '
      <li class="fields">
        <div class="field">
          <div class="input-box input-cnpj'.((in_array('cnpj', $formErrors)) ? ' input-error' : '').'">
              <label for="billing:cnpj">'.$this->__('CNPJ').' <span class="required">*</span></label><br/>
              <input type="text" name="billing[cnpj]" value="'.$dataHelper->clearDash($customer->getCnpj()).'" title="'.$this->__('CNPJ').'" class="required-entry form-control billing_cnpj" id="billing:cnpj" '.(($dataHelper->clearDash($customer->getCnpj()) != '') ? 'readonly="readonly"' : $blankFields[] = 'cnpj').' />
          </div>
        </div>';
    ?>

    <?php $billingFields['inscricaoestadual'] = '
        <div class="field">
          <div class="input-box input-inscricaoestadual'.((in_array('inscricaoestadual', $formErrors)) ? ' input-error' : '').'">
              <label for="billing:inscricaoestadual">'.$this->__('Inscrição Estadual').' <span class="required">*</span></label><br/>
              <input type="text" name="billing[inscricao_estadual]" value="'.$dataHelper->clearDash($customer->getInscricaoEstadual()).'" title="'.$this->__('Inscrição Estadual').'" class="required-entry form-control" id="billing:inscricaoestadual" '.(($dataHelper->clearDash($customer->getInscricaoEstadual()) != '') ? 'readonly="readonly"' : $blankFields[] = 'inscricaoestadual').' />
          </div>
        </div>
      </li>';
    ?>



<?php endif; ?>

<?php if ($customer->getTipopessoa() == 'both' || $customer->getTipopessoa() == 'vet') : ?>

    <?php $billingFields['crmv'] = '
      <li class="wide">
        <div class="input-box input-crmv'.((in_array('crmv', $formErrors)) ? ' input-error' : '').'">
            <label for="billing:crmv">'.$this->__('CRMV').' <span class="required">*</span></label><br/>
            <input type="text" name="billing[crmv]" value="'.$dataHelper->clearDash($customer->getCrmv()).'" title="'.$this->__('CRMV').'" class="required-entry form-control" id="billing:crmv" '.(($dataHelper->clearDash($customer->getCrmv()) != '') ? 'readonly="readonly"' : $blankFields[] = 'crmv').' />
        </div>
      </li>';
    ?>

<?php endif; ?>

<?php if(!$this->settings['exclude_address']):?>
    <?php if(Mage::getStoreConfig('onestepcheckout/exclude_fields/enable_address_fields')):?>
        <?php
        $addressFields = '';
            for ($_i=1, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++){
                    if ($_i % 2 != 0)
                      $addressFields .= '<li class="fields">';
                    $addressFields .= '
                    <div class="field">
                      <div class="input-box input-address-short'.((in_array('address', $formErrors)) ? ' input-error' : '').'">
                      <label for="billing:street'.$_i.'">'.$this->__('Street Address '.$_i).' '.(($_i != 3) ? '<span class="required">*</span>' : '').'</label><br />
                      <input type="text" title="'.$this->__('Street Address '.$_i).'" name="billing[street][]" id="billing:street'.$_i.'" value="'.$dataHelper->clearDash($address->getStreet($_i)).'" class="'.(($_i != 3) ? 'required-entry' : '').' form-control onestepcheckout-address-line" '.((trim($dataHelper->clearDash($address->getStreet($_i))) != '') ? 'readonly="readonly"' : (($_i != 3) ? $blankFields[] = 'street_'.$_i : '')).' />
                      </div>
                    </div>';
                    if ($_i % 2 == 0)
                      $addressFields .= '</li>';
            }
            $billingFields['street'] = $addressFields;
        ?>
    <?php else:?>
        <?php
        $addressFields = '';
            for ($_i=1, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++){

                    $addressFields .= '<input type="text" title="'.$this->__('Street Address '.$_i).'" name="billing[street][]" id="billing:street'.$_i.'" value="'.$dataHelper->clearDash($address->getStreet($_i)).'" class="'.(($_i == 1)? 'required-entry ' : '').'form-control onestepcheckout-address-line" '.(($dataHelper->clearDash($address->getStreet($_i)) != '') ? 'readonly="readonly"' : $blankFields[] = 'street_'.$_i).' />';
                    $addressFields .= (($_i != $this->helper('customer/address')->getStreetLines()) ? '<br/>': '');
            }
            $billingFields['street'] = '
                <div class="input-box input-address'.((in_array('address', $formErrors)) ? ' input-error' : '').'">
                    <label for="billing:street1">'.$this->__('Address').' <span class="required">*</span></label><br />
                    '.$addressFields.'
                </div>';
        ?>
    <?php endif; ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_country_id']):?>
<?php
$billingFields['country_id'] = '
    <div class="input-box input-country'.((in_array('country', $formErrors)) ? ' input-error' : '').'">
        <label for="billing:country_id">'.$this->__('Country').' <span class="required">*</span></label><br />
            '.$this->getCountryHtmlSelect('billing').'
    </div>';
?>
<?php else: ?>
<?php $billingFields['country_id'] = '
    <input type="hidden" name="billing[country_id]" id="billing:country_id" value="'.$this->settings['default_country'].'" />';
?>
<?php endif; ?>
<?php if(!$this->settings['exclude_region']): ?>

    <?php $billingFields['region_id'] = '
        <div class="field">
          <div class="input-box input-region'.((in_array('region', $formErrors)) ? ' input-error' : '').'">
              <label for="billing:region">'.$this->__('State/Province').' <span class="required">*</span></label><br/>
              <select id="billing:region_id" name="billing[region_id]" title="'.$this->__('State/Province').'" class="validate-select" style="display:none" '.(($dataHelper->clearDash($address->getRegionId()) != '') ? 'readonly="readonly"' : $blankFields[] = 'region_id').'>
                  <option value="">'.$this->__('Please select region, state or province').'</option>
              </select>
              <script type="text/javascript">
                  $("billing:region_id").setAttribute("defaultValue",  "'.$dataHelper->clearDash($address->getRegionId()).'");
              </script>
              <input type="text" id="billing:region" name="billing[region]" value="'.$dataHelper->clearDash($address->getRegion()).'"  title="'.$this->__('State/Province').'" class="required-entry form-control" style="display:none" />
          </div>
        </div>
      </li>';
    ?>
<?php endif; ?>
<?php if(!$this->settings['exclude_city']):?>
    <?php $billingFields['city'] = '
      <li class="wide">
        <div class="input-box input-city'.((in_array('city', $formErrors)) ? ' input-error' : '').'">
            <label for="billing:city">'.$this->__('City').' <span class="required">*</span></label><br/>
            <input type="text" name="billing[city]" value="'.$dataHelper->clearDash($address->getCity()).'" title="'.$this->__('City').'" class="required-entry form-control" id="billing:city" '.(($dataHelper->clearDash($address->getCity()) != '') ? 'readonly="readonly"' : $blankFields[] = 'city').' />
        </div>
      </li>';
    ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_zip']): ?>
    <?php $billingFields['postcode'] = '
      <li class="fields">
        <div class="field">
          <div class="input-box input-postcode'.((in_array('postcode', $formErrors)) ? ' input-error' : '').'" >
              <label for="billing:postcode">'.$this->__('Zip/Postal Code').' <span class="required">*</span></label><br />
              <input type="text" title="'.$this->__('Zip/Postal Code').'" name="billing[postcode]" id="billing:postcode" value="'.$dataHelper->clearDash($address->getPostcode()).'" '.(($address->getPostcode() != '') ? 'readonly="readonly"' : $blankFields[] = 'postcode').' class="validate-zip-international required-entry form-control" />
          </div>
        </div>';
    ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_company']): ?>
    <?php $billingFields['company'] = '
        <div class="input-box input-company'.((in_array('company', $formErrors)) ? ' input-error' : '').'">
            <label for="billing:company">'.$this->__('Company').'</label><br/>
            <input type="text" name="billing[company]" value="'.$dataHelper->clearDash($address->getCompany()).'" title="'.$this->__('Company').'" class="form-control" id="billing:company" />
        </div>';
    ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_fax']): ?>
    <?php $billingFields['fax'] = '
        <div class="input-box input-fax'.((in_array('fax', $formErrors)) ? ' input-error' : '').'">
            <label for="billing:fax">'.$this->__('Fax').'</label><br/>
            <input type="text" name="billing[fax]" value="'.$dataHelper->clearDash($address->getFax()).'" title="'.$this->__('Fax').'" class="form-control" id="billing:fax" />
        </div>';
    ?>
<?php endif; ?>

<?php
    $_taxvat = false;
    try {
        if(Mage::getStoreConfig('onestepcheckout/exclude_fields/enable_pillwaxeuvat_support')){
            $_taxvat = $this->getLayout()->createBlock('euvat/widget_taxvat');
        }
    } catch (Exception $e) {
    }
    if(!is_object($_taxvat)){
        $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat');
    }
?>
<?php if(is_object($_taxvat) && $_taxvat->isEnabled()  && !$this->isCustomerLoggedIn()): ?>
    <?php $billingFields['taxvat'] =
            $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())
                ->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml();
    ?>
<?php endif; ?>
<?php if (method_exists(Mage::helper('customer/address'), 'isVatAttributeVisible') && Mage::helper('customer/address')->isVatAttributeVisible()) : ?>
    <?php $billingFields['taxvat'] = '
            <label for="billing:vat_id">'.$this->__('VAT Number').'</label>
            <div class="input-box">
                <input type="text" id="billing:vat_id" name="billing[vat_id]" value="'.$dataHelper->clearDash($address->getVatId()).'" title="'.$this->__('VAT Number').'" class="form-control '.Mage::helper('customer/address')->getAttributeValidationClass('vat_id').'" />
            </div>';
    ?>
<?php endif; ?>
<?php
    try {
        $_dob = $this->getLayout()->createBlock('customer/widget_dob');
    } catch (Exception $e) {
        $_dob = false;
    }
?>
<?php
    try {
        $_gender = $this->getLayout()->createBlock('customer/widget_gender');
    } catch (Exception $e) {
        $_gender = false;
    }
?>

<?php if (is_object($_dob) && $_dob->isEnabled() && !$this->isCustomerLoggedIn()): ?>
    <?php $billingFields['dob'] = '
        <div class="field">
            '.$_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml().'
        </div>';
    ?>
<?php endif; ?>
<?php if (is_object($_gender) && $_gender->isEnabled() && !$this->isCustomerLoggedIn()): ?>
    <?php $billingFields['gender'] = '
        <div class="field">
            '.$_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml().'
        </div>';
    ?>
<?php endif ?>
<?php if(!$this->isCustomerLoggedIn() && $helper->showCreateAccount()): ?>
    <?php $billingFields['create_account'] = '
        <div class="input-box">
            <input id="id_create_account" type="checkbox" name="create_account" value="1" '.((isset($_POST['create_account']) && $_POST['create_account'] == '1') ? ' checked="checked"' : '').' />
            <label for="id_create_account">'.$this->__('Create an account for later use').'</label>
        </div>

        <script>
        document.observe("dom:loaded", function() {
            $("id_create_account").observe("click", function(e) {
                var element = e.element();
                if(element.checked) {
                    $("onestepcheckout-li-password").show();
                }
                else    {
                    $("onestepcheckout-li-password").hide();
                }
            });
        });
        </script>';
    ?>
<?php endif; ?>
<?php if($helper->showPasswords() && !$this->isCustomerLoggedIn()): ?>
    <?php
        //id="onestepcheckout-li-password"
        $billingFields['password'] = '
        <li id="onestepcheckout-li-password" '.(($helper->hidePasswords()) ? 'style="display: none;"':'').'>
            <div class="input-box input-password'.((in_array('password', $formErrors)) ? ' input-error' : '').'">
                <label for="billing:customer_password">'.$this->__('Password').'</label><br/>
                <input type="password" class="form-control required-entry validate-password" value="'.((isset($_POST['billing']['customer_password'])) ? Mage::helper('core')->escapeHtml($_POST['billing']['customer_password']) : '').'" title="Password" id="billing:customer_password" name="billing[customer_password]"/>
            </div>
            <div class="input-box input-password'.((in_array('confirm_password', $formErrors)) ? ' input-error' : '').'">
                <label for="billing:confirm_password">'.$this->__('Confirm password').'</label><br/>
                <input type="password" class="form-control required-entry validate-cpassword" value="'.((isset($_POST['billing']['confirm_password'])) ? Mage::helper('core')->escapeHtml($_POST['billing']['confirm_password']) : '').'" id="billing:confirm_password" title="Confirm Password" name="billing[confirm_password]"/>
            </div>
        </li>';
    ?>
<?php endif; ?>

<?php /*if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
    <?php $billingFields['save_in_address_book'] = '
        <li class="">
            <input type="checkbox" checked="checked" name="billing[save_in_address_book]" value="1" title="'.$this->__('Save in address book').'" id="billing:save_in_address_book" onchange="shipping.setSameAsBilling(false);"'.(($dataHelper->clearDash($address->getSaveInAddressBook())) ? 'checked="checked"':'').' class="checkbox" /><label for="billing:save_in_address_book">'.$this->__('Save in address book').'</label>
        </li>';
    ?>
<?php else:*/ ?>
    <?php $billingFields['save_in_address_book'] = '
        <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>';
    ?>
<?php //endif; ?>

<h6>Dados do responsável pelo pedido</h6>

<?php $billingFields = $this->getBillingFieldsOrder($billingFields);?>
<?php foreach($billingFields as $key => $value):?>
    <?php //if(!empty($value['has_li'])):?>
        <?php echo implode('',$value['fields']);?>
    <?php //else:?>
        <?php /*<li class="clearfix"><?php echo implode('',$value['fields']);?></li> */ ?>
    <?php //endif;?>
<?php endforeach;?>

<li style="text-align: right" class="buttons-set">
   <br />
  <button id="step:save_billing" type="button" class="button btn large green onestepcheckout-button step_save_billing">Ir para entrega</button>
  <span class="please-wait" id="billing-please-wait" style="display:none;">
      <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
  </span>
</li>

<?php

if ($dataHelper->clearDash($address->getIdentification()) == '') { $blankFields[] = 'identification'; }
if ($dataHelper->clearDash($customer->getTelefone()) == '') { $blankFields[] = 'telefone'; }

  if (count($blankFields) <= 0)
  {
    echo '
    <script>
      jQuery(document).ready(function() {
        changeCheckoutStep(1);
      });
    </script>';
  }
?>

<li>
	Caso necessite fazer alguma alteração no cadastro, entre em contato pelo email <a href="mailto">suporte@4vets.com.br</a>
</li>