<?php $_code = $this->getMethodCode(); ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
                <option value=""><?php echo $this->__('--Please Select--') ?></option>
                <?php $_ccType = $this->getInfoData('cc_type') ?>
                <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option value="<?php echo $_typeCode ?>"<?php if ($_typeCode == $_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="form-control validate-cc-number validate-cc-type" value="" />
        </div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                    <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                    <?php foreach ($this->getCcMonths() as $k => $v): ?>
                        <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                    <?php foreach ($this->getCcYears() as $k => $v): ?>
                        <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_cvv_div">
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="form-control cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>
    </li>
    <?php if (count($this->getInstallments()) > 1): ?>
    <li id="<?php echo $_code ?>_installments">
        <label for="<?php echo $_code ?>_installments" class="required"><em>*</em><?php echo $this->__('Number of installments') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_installments" name="payment[cc_installments]" class="required-entry">
                <?php foreach ($this->getInstallments() as $key => $label): ?>
                <option value="<?php echo $key; ?>"><?php echo $label; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </li>
    <?php endif; ?>
    <li>
        <label for="<?php echo $_code ?>_portador_nome" class="required"><em>*</em><?php echo $this->__('Nome do portador') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_portador_nome" name="payment[portador_nome]" title="<?php echo $this->__('Nome do portador') ?>" class="form-control" value="" />
        </div>
    </li>
    <li>
        <?php /** @TODO mask 99/99/9999 */ ?>
        <label for="<?php echo $_code ?>_portador_nascimento" class="required"><em>*</em><?php echo $this->__('Data de nascimento') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_portador_nascimento" name="payment[portador_nascimento]" title="<?php echo $this->__('Data de nascimento') ?>" class="form-control" value="" />
        </div>
    </li>
    <li>
        <?php /** @TODO mask 99999999999 */ ?>
        <label for="<?php echo $_code ?>_portador_cpf" class="required"><em>*</em><?php echo $this->__('CPF') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_portador_cpf" name="payment[portador_cpf]" title="<?php echo $this->__('CPF') ?>" class="form-control" value="" />
        </div>
    </li>
    <li>
        <?php /** @TODO mask (99)9999-9999 */ ?>
        <label for="<?php echo $_code ?>_portador_telefone" class="required"><em>*</em><?php echo $this->__('Telefone') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_portador_telefone" name="payment[portador_telefone]" title="<?php echo $this->__('Telefone') ?>" class="form-control" value="" />
        </div>
    </li>
</ul>
