<div class="hidden" id="login-box-hidden">
	<div id="account-login-box" name="account-login-box" class="account-login login-box">
		<div class="page-title">
			<h1><?php echo $this->__('Login or Create an Account'); ?></h1>
		</div>
		<?php /* Extensions placeholder */ ?>
		<?php echo $this->getChildHtml('customer.form.login.extra'); ?>
		<form action="<?php echo $this->getPostActionUrl(); ?>" method="post" id="login-form-box" name="login-form-box">
			<?php echo $this->getBlockHtml('formkey'); ?>
			<div class="login-box-container">
				<div class="content">
					<p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
					<ul class="form-list">
						<li>
							<label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>

							<div class="input-box">
								<input type="text" name="login[username]"
											 value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email"
											 class="input-text required-entry validate-email"
											 title="<?php echo $this->__('Email Address') ?>"/>
							</div>
						</li>
						<li>
							<label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>

							<div class="input-box">
								<input type="password" name="login[password]" class="input-text required-entry validate-password"
											 id="pass" title="<?php echo $this->__('Password') ?>"/>
							</div>
						</li>
						<?php echo $this->getChildHtml('form.additional.info'); ?>
					</ul>
					<p class="required"><?php echo $this->__('* Required Fields') ?></p>
				</div>
				<div class="buttons-set">

					<a href="<?php echo $this->getForgotPasswordUrl() ?>"
						 class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
					<br>
					<a href="<?php echo $this->getCreateAccountUrl() ?>" type="button"
						 title="<?php echo $this->__('Create an Account') ?>">
						<?php echo $this->__('Create an Account') ?>

					</a>
					<button type="submit" class="button btn btn-action" title="<?php echo $this->__('Login') ?>" name="loginbox-btn-action" id="loginbox-btn-action">
						<span><span><?php echo $this->__('Login') ?></span></span></button>
				</div>

				<br/>
				<br/>

				<?php echo $this->getChildHtml('loginbox.facebooklogin'); ?>
			</div>
		</form>
		<script type="text/javascript">
			//<![CDATA[
			var dataForm = new VarienForm('login-form-box', true);
			//]]>
		</script>
	</div>
</div>

<div id="login-box-loading" style="display: none;">
	<i class="fa fa-spinner fa-spin fa-5x"></i>
</div>

<style type="text/css">
	#login-box-loading {
		height: 100%;
		width: 100%;
		position: fixed;
		background-color: gray; /* for demonstration */
		opacity: 0.6;
		z-index: 999999;
		top: 0;
	}

	#login-box-loading i {
		position: absolute;
		left: 50%;
		top: 50%;
		margin-left: -32px; /* -1 * image width / 2 */
		margin-top: -32px; /* -1 * image height / 2 */
		z-index: 9999999;
	}
</style>

<script type="text/javascript">

	jQuery(document).ready(function () {

		jQuery('#login').click(function (event) {

			event.preventDefault();
			jQuery.featherlight(jQuery('#account-login-box'));
			return false;

		});

		jQuery('#loginbox-btn-action').click(function (element) {
			element.preventDefault();

			clearElements('.messages');

			jQuery('#login-box-loading').show();

			jQuery.post(
				'<?php echo str_replace(array('https://', 'http://'), '//', $this->getUrl('customer/account/loginBoxPost')) ?>',
				jQuery(".featherlight-content #login-form-box").serialize(),
				function (data) {
					var result = eval("(" + data + ")");
					if (result.urlRedirect) {
						window.location = result.urlRedirect;
					} else if (result.logined) {
						window.location.reload(true);
					} else {
						addError('.featherlight-content #login-form-box', result.error);
					}
				});
		});
	});

	function addError(element, message) {
		jQuery(element).append('<ul class="messages"><li class="error-msg"><ul><li><span>' + message + '</span></li></ul></li></ul>');
		jQuery('#login-box-loading').hide();
	}

	function clearElements(classPattern) {
		jQuery('.featherlight-content #login-form-box .messages').remove();
	}

</script>