<div class="up-footer">
	<div class="news-social-container">
		<div class="news">
			<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
				<?php echo $this->getChildHtml('global_messages'); ?>
				<span class="title">Receba nossas notícias</span>
				<br>
				<input placeholder="Digite o seu e-mail" type="text" name="email" id="newsletter"/>
				<button type="submit">Enviar</button>
			</form>
		</div>
		<div class="social">
			<a href="#" target="_blank">
				<i class="fa fa-facebook-square fa-4x"></i>
			</a>
			<a href="#" target="_blank">
				<i class="fa fa-twitter-square fa-4x"></i>
			</a>
			<a href="#" target="_blank">
				<i class="fa fa-google-plus-square fa-4x"></i>
			</a>
			<a href="#" target="_blank">
				<i class="fa fa-instagram fa-4x"></i>
			</a>
		</div>
	</div>
</div>