</div>
</div>
</div>

<div class="idexx-breadcrumb">
	<div class="inner default-page-width">
		<img src="<?php echo $this->getSkinUrl('images/category/breadcrumb/equipamentos.png'); ?>" border="0" width="284" height="75" class="overlay" />
		<img id="145158" src="<?php echo $this->getSkinUrl('images/category/breadcrumb/breadcrumb.jpg'); ?>" border="0" width="950" height="75" orgWidth="950" orgHeight="75" usemap="#145158" alt="" />
		<map name="145158" id="145158">
			<area id="home" alt="Home" title="Home" href="/" shape="rect" coords="0,0,195,75" style="outline:none;" target="_self"     />
			<area id="cag" alt="Animais de companhia" title="Animais de companhia" href="/cag" shape="rect" coords="195,0,405,75" style="outline:none;" target="_self"     />
			<area id="snaps" alt="Snaps" title="Snaps" href="/cag/snaps" shape="rect" coords="409,0,642,75" style="outline:none;" target="_self"     />
			<area id="equipamentos" alt="Equipamentos" title="Equipamentos" href="/cag/equipamentos" shape="rect" coords="643,0,909,75" style="outline:none;" target="_self"     />
		</map>
	</div>
</div>

<div class="idexx-breadcrumb-mobile">
	<a href="<?php echo Mage::getBaseUrl() ?>"><i class="fa fa-home"></i></a>
	<i class="fa fa-angle-right"></i>
	<a href="/cag">Animais de companhia</a>
	<i class="fa fa-angle-right"></i>
	<span>Equipamentos</span>
</div>

<div style="background-image: url(<?php echo $this->getSkinUrl('images/category/equipamentos/1.jpg'); ?>)" class="category-image">
	<div class="page-title category-title">
		<div class="inner">
			<h1>Analisadores IDEXX</h1>
			<p class="subtitle">Autonomia em <strong>diagnósticos</strong> para clínicas e hospitais <strong>veterinários</strong></p>
		</div>
	</div>
	<div class="category-title-image">
		<img src="<?php echo $this->getSkinUrl('images/category/equipamentos/2.png'); ?>" width="690" height="279" />
	</div>
</div>

<div class="main-container container col1-layout default-page-width">
	<div class="main">
		<div class="col-main">



			<div class="block1 two-columns">
				<div class="column left">
					<div class="image">
						<img class="lazy"
							 data-original="<?php echo $this->getSkinUrl('images/category/equipamentos/3.jpg'); ?>"
							 alt="IDEXX VetLab Station" width="518" height="519"/>
					</div>
				</div>
				<div class="column right">
					<div class="text">
						<h1>IDEXX VetLab Station</h1>
						<h2>Integração total entre ferramentas
							diagnósticas com o mais alto nível de
							confiabilidade</h2>
					</div>
				</div>
				<div class="clear"></div>
			</div>

			<div class="block2 tree-columns">
				<div class="column left">
					<img class="lazy"
						 data-original="<?php echo $this->getSkinUrl('images/category/equipamentos/4.jpg'); ?>"
						 alt="IDEXX VetLab Station" width="186" height="184"/>
					<br /><br />
					<h1>integração</h1>
				</div>
				<div class="column middle">
					<img class="lazy"
						 data-original="<?php echo $this->getSkinUrl('images/category/equipamentos/5.jpg'); ?>"
						 alt="IDEXX VetLab Station" width="186" height="184"/>
					<br /><br />
					<h1>eficiência</h1>
				</div>
				<div class="column right">
					<img class="lazy"
						 data-original="<?php echo $this->getSkinUrl('images/category/equipamentos/6.jpg'); ?>"
						 alt="IDEXX VetLab Station" width="186" height="184"/>
					<br /><br />
					<h1>confiabilidade</h1>
				</div>
				<div class="clear"></div>
			</div>

			<div class="block3">
				<h2>Conjunto de analisadores que trabalham de forma independente ou <strong>integrada</strong>, com <strong>relatório único</strong> de fácil leitura e laudo comentado.<br />
					Operação simples e intuitiva, com <strong>touch-screen</strong> de fácil utilização.<br />
					Exames de alta <strong>precisão</strong> em diversas especialidades: hematologia, bioquímica, eletrólitos, gasometria, urinálise e coagulação.<br />
					Acesso ao IDEXX <strong>SmartService</strong>, o mais alto nível em atenção ao cliente.</h2>
			</div>

			<h1>Exames Hematológicos</h1>
			<hr class="hundred" />

			<br /><br /><br /><br />

			<div class="block4 two-columns">
				<div class="column left">
					<img class="lazy"
						 data-original="<?php echo $this->getSkinUrl('images/category/equipamentos/7.jpg'); ?>"
						 alt="IDEXX VetLab Station" width="218" height="279"/>
				</div>
				<div class="column right">
					<h4>Analisador Hematológico ProCyte Dx®</h4>
					<br />
					<p>Exames avançados diretamente em sua clínica, com resultados prontos em 2 minutos para 26 parâmetros sanguíneos.<br />
						Avançada contagem diferencial de 5 partes da série branca, além da contagem absoluta de reticulócitos e detecção de neutrófilos imaturos (bastonetes).<br />
						3 metodologias em um único equipamento, proporcionando rapidez e precisão em seus resultados: Citometria de Fluxo a Laser; Fluorescência Óptica e Impedância de Fluxo Laminar.<br />
						Fácil manuseio e manutenção: totalmente automatizado, sem preparo de amostra ou reagentes.</p>
				</div>
				<div class="clear"></div>
			</div>

			<div class="block4-divisor">
				<hr />
			</div>

			<div class="block4 two-columns">
				<div class="column left">
					<img class="lazy"
						 data-original="<?php echo $this->getSkinUrl('images/category/equipamentos/8.jpg'); ?>"
						 alt="IDEXX VetLab Station" width="259" height="269"/>
				</div>
				<div class="column right">
					<h4>Analisador Hematológico LaserCyte Dx®</h4>
					<br />
					<p>Resultados validados para 24 parâmetros sanguíneos. Contagem completa de células sanguíneas, incluindo contagem diferencial de 5 partes da série branca: análise completa e interpretação precisa dos 5 diferentes tipos celulares.<br />
						Contagem absoluta de reticulócitos que auxilia no diagnóstico de anemias.<br />
						Contagem precisa de plaquetas.<br />
						Fácil manuseio e manutenção: totalmente automatizado, sem preparo de amostra ou reagentes.</p>
				</div>
				<div class="clear"></div>
			</div>

			<div class="block4-divisor">
				<hr />
			</div>

			<div class="block4 two-columns">
				<div class="column left">
					<img class="lazy"
						 data-original="<?php echo $this->getSkinUrl('images/category/equipamentos/9.jpg'); ?>"
						 alt="IDEXX VetLab Station" width="292" height="229"/>
				</div>
				<div class="column right">
					<h4>Analisador Hematológico VetAutoread®</h4>
					<br />
					<p>O analisador hematológico IDEXX VetAutoread® oferece informação de maneira imediata e permite a realização de check-ups de rotina, exames pré-anestésicos e avaliação da saúde geral dos pacientes.<br />
						Realiza triagem minuciosa, análise pré-cirúrgica e exames de parâmetros sanguíneos em geral: Hematócrito (%); Hemoglobina (g/dl); MCHC; WBC (leucócitos totais); Granulócitos (% e absoluto); Eosinófilos (absoluto somente em cães); Neutrófilos; Linfócitos e Monócitos; plaquetas; eritrócitos nucleados (nRBCs) e Reticulócitos.</p>
				</div>
				<div class="clear"></div>
			</div>

			<h1>Exames Bioquímicos + Eletrólitos</h1>
			<hr class="hundred" />

			<br /><br /><br /><br />

			<div class="block4 two-columns">
				<div class="column left">
					<img class="lazy"
						 data-original="<?php echo $this->getSkinUrl('images/category/equipamentos/10.jpg'); ?>"
						 alt="IDEXX VetLab Station" width="259" height="334"/>
				</div>
				<div class="column right">
					<h4>Analisador Bioquímico + Eletrólitos Catalyst One®</h4>
					<br />
					<p>Analisador de última geração que realiza em sua clínica exames <strong>bioquímicos + eletrólitos</strong> (CI, K, Na) com alta precisão, em tempo real.<br />
						Apresenta resultados em 8 minutos, a partir de uma única amostra.<br />
						Menu de 30 parâmetros, incluindo <strong>frutosamina, fenobarbital, T4 total</strong> e <strong>Relação Proteína/Creatinina</strong> na urina.<br />
						Tecnologia de “placa seca”, que garante resultados precisos, mesmo a partir de amostras comprometidas (presença de hemólise, lipemia e/ou icterícia).</p>
				</div>
				<div class="clear"></div>
			</div>

			<div class="block4-divisor">
				<hr />
			</div>

			<div class="block4 two-columns">
				<div class="column left">
					<img class="lazy"
						 data-original="<?php echo $this->getSkinUrl('images/category/equipamentos/11.jpg'); ?>"
						 alt="IDEXX VetLab Station" width="274" height="310"/>
				</div>
				<div class="column right">
					<h4>Analisador Bioquímico + Eletrólitos Catalyst Dx®</h4>
					<br />
					<p>Velocidade, rendimento e flexibilidade, com menos tempo de operação.<br />
						Resultados mais rápidos e a capacidade de executar várias amostras simultaneamente: analisa 28 parâmetros individuais ou 7 painéis pré-estabelecidos.<br />
						Executa 25 parâmetros em uma única amostra.<br />
						Respostas em tempo real para o exame pré-anestésico.<br />
						Analisa Frutosamina, Fenobarbital.<br />
						Analisa a relação Proteína/Creatinina na urina.<br />
						Análise de eletrólitos (CI, K, Na).</p>
				</div>
				<div class="clear"></div>
			</div>

			<div class="block4-divisor">
				<hr />
			</div>

			<div class="block4 two-columns">
				<div class="column left">
					<img class="lazy"
						 data-original="<?php echo $this->getSkinUrl('images/category/equipamentos/12.jpg'); ?>"
						 alt="IDEXX VetLab Station" width="274" height="310"/>
				</div>
				<div class="column right">
					<h4>Analisador Bioquímico VetTest®</h4>
					<br />
					<p>Exclusivo para diagnóstico veterinário, com referências para 39 espécies.<br />
						Capaz de analisar 26 parâmetros individuais ou 7 painéis pré-estabelecidos.<br />
						Tecnologia de “placa-seca” (resultados precisos, evitando interferência de substâncias indesejáveis).<br />
						Atualizações gratuitas de software.<br />
						Analisa a relação Proteína/Creatinina na urina.</p>
				</div>
				<div class="clear"></div>
			</div>

			<h1>Equipamentos Complementares</h1>
			<hr class="hundred" />

			<br /><br /><br /><br />

			<div class="block4 two-columns">
				<div class="column left">
					<img class="lazy"
						 data-original="<?php echo $this->getSkinUrl('images/category/equipamentos/13.jpg'); ?>"
						 alt="IDEXX VetLab Station" width="308" height="254"/>
				</div>
				<div class="column right">
					<h4>Analisador VetLab UA®</h4>
					<br />
					<p>Economiza tempo e elimina erros de leitura com o acionamento de apenas um botão e resultados em cerca de 80 segundos. As tiras IDEXX UA ® podem ser interpretadas de forma manual ou com analisador IDEXX VetLab® UA.</p>
				</div>
				<div class="clear"></div>
			</div>

			<div class="block4-divisor">
				<hr />
			</div>

			<div class="block4 two-columns">
				<div class="column left">
					<img class="lazy"
						 data-original="<?php echo $this->getSkinUrl('images/category/equipamentos/14.jpg'); ?>"
						 alt="IDEXX VetLab Station" width="285" height="141"/>
				</div>
				<div class="column right">
					<h4>Analisador VetStat®</h4>
					<br />
					<p>Análise de gases sanguíneos, eletrólitos, equilíbrio ácido-base, cálcio ionizado e glicose em amostras de sangue total, plasma ou soro.</p>
				</div>
				<div class="clear"></div>
			</div>

			<div class="block4-divisor">
				<hr />
			</div>

			<div class="block4 two-columns">
				<div class="column left">
					<img class="lazy"
						 data-original="<?php echo $this->getSkinUrl('images/category/equipamentos/15.jpg'); ?>"
						 alt="IDEXX VetLab Station" width="302" height="150"/>
				</div>
				<div class="column right">
					<h4>Analisador Coag Dx®</h4>
					<br />
					<p>Analisa riscos de hemorragias. Utiliza metodologia end point fibrin clot, padrão ouro em coagulação. TP e TTPA em sangue fresco ou citratado.</p>
				</div>
				<div class="clear"></div>
			</div>