</div>
</div>
</div>

<div class="idexx-breadcrumb">
	<div class="inner default-page-width">
		<img src="<?php echo $this->getSkinUrl('images/category/breadcrumb/cag.png'); ?>" border="0" width="264" height="75" class="overlay" />
		<img id="145158" src="<?php echo $this->getSkinUrl('images/category/breadcrumb/breadcrumb.jpg'); ?>" border="0" width="950" height="75" orgWidth="950" orgHeight="75" usemap="#145158" alt="" />
		<map name="145158" id="145158">
			<area id="home" alt="Home" title="Home" href="/" shape="rect" coords="0,0,195,75" style="outline:none;" target="_self"     />
			<area id="cag" alt="Animais de companhia" title="Animais de companhia" href="/cag" shape="rect" coords="195,0,405,75" style="outline:none;" target="_self"     />
			<area id="snaps" alt="Snaps" title="Snaps" href="/cag/snaps" shape="rect" coords="409,0,642,75" style="outline:none;" target="_self"     />
			<area id="equipamentos" alt="Equipamentos" title="Equipamentos" href="/cag/equipamentos" shape="rect" coords="643,0,909,75" style="outline:none;" target="_self"     />
		</map>
	</div>
</div>

<div class="idexx-breadcrumb-mobile">
	<a href="<?php echo Mage::getBaseUrl() ?>"><i class="fa fa-home"></i></a>
	<i class="fa fa-angle-right"></i>
	<span>Animais de companhia</span>
</div>

<div class="block1" id="block1">
	<div class="bk-image">
		<div class="bk-text">
			<div class="bk-text-content">
				<a href="#" alt="Idexx" id="lk-block1">
					<img src="<?php echo $this->getSkinUrl('images/category/pequenos_animais/16.png'); ?>" alt=""/>
				</a>
			</div>
		</div>
	</div>
</div>

<div class="block2" id="block2">
	<div class="bk2-container">
		<div class="col1">
			<img src="<?php echo $this->getSkinUrl('images/category/pequenos_animais/icon1.png'); ?>" alt=""/>
			<span class="title">Informações Confiáveis e Imediatas</span>
			<div class="clear"></div>
			<span class="description">Tenha em sua clínica informações imediatas e confiáveis sobre a saúde de seus pacientes.</span>
		</div>

		<div class="col2">
			<img src="<?php echo $this->getSkinUrl('images/category/pequenos_animais/icon2.png'); ?>" alt=""/>
			<span class="title">Exames de Alta Precisão em Diversas Especialidades</span>
			<div class="clear"></div>
		<span class="description">Com os analisadores IDEXX você realiza em sua clínica exames de alta precisão, em diversas especialidades.</span>
		</div>
	</div>
</div>

<div class="block3" id="block3">
	<div class="bk-image">
		<div class="bk-text">
			<div class="bk-text-content">
				<a href="#" alt="Idexx" id="lk-block3">
					<img src="<?php echo $this->getSkinUrl('images/category/pequenos_animais/18.png'); ?>" alt=""/>
				</a>
			</div>
		</div>
	</div>
</div>

<div class="block4" id="block4">
	<div class="bk-text">
		<div class="fit">
			<h3>Testes rápidos <span>SNAP&#174;</span></h3>
			<br />

			<p>SNAP é o teste rápido ideal para clínicas veterinárias de todos os portes. Usando a tecnologia ELISA, o SNAP® é um exame de alta confiabilidade, apresentando resultados imediatos.</p>
			<a href="<?php echo Mage::helper('categoryattribute')->getCategoryByUrlKey('cag', 'snaps')->getUrl(); ?>" class="link-saiba-mais">Saiba mais sobre SNAP&nbsp&nbsp&nbsp<i class="fa fa-angle-right"></i></a>
		</div>
	</div>
	<div class="bk-image">
		<img src="<?php echo $this->getSkinUrl('images/category/pequenos_animais/30.jpg'); ?>" alt=""/>
	</div>
</div>

<div class="block5" id="block5">
	<div class="bk5-container">
	<div class="bk-image">
		<img src="<?php echo $this->getSkinUrl('images/category/pequenos_animais/31.jpg'); ?>" alt=""/>
	</div>
	<div class="bk-text">
		<div class="fit">
			<h3>Equipamentos para <span>Análises</span></h3>

			<div class="trace"></div>

			<div class="clear"></div>

			<p>Com os analisadores IDEXX você realiza em sua clínica exames de alta precisão, em diversas especialidades. Tenha em suas mãos informações rápidas e confiáveis na hora em que você precisa, com resultados integrados em um único relatório de fácil leitura e interpretação.</p>
			<p>VetLab Station / Hematologia / Bioquímica / Gasometria / Coagulação / Urinálise / SNAP Pro</p>

			<div class="clear"></div>

			<a href="<?php echo Mage::helper('categoryattribute')->getCategoryByUrlKey('cag', 'equipamentos')->getUrl(); ?>" class="link-saiba-mais">Saiba mais sobre equipamentos&nbsp&nbsp&nbsp<i class="fa fa-angle-right"></i></a>
		</div>
	</div>
		</div>
</div>

<br /><br /><br /><br /><br /><br />

<div class="block6" id="block6">
	<div class="bk6-container">

		<div class="header">
			<h3>Resultados em apenas 10 minutos</h3>
			<h4>Veja como a IDEXX pode otimizar seu atendimento</h4>
		</div>
		<br />

		<div class="trace"></div>

		<div class="time-col">
			<img class="lazy"
					 data-original="<?php echo $this->getSkinUrl('images/category/pequenos_animais/19.png'); ?>"
					 alt="Cliente" width="168" height="168"/><br>
			<span class="title">14:00</span>
			<span class="description">cliente chega ao consultório</span>
		</div>

		<div class="time-col">
			<img class="lazy"
					 data-original="<?php echo $this->getSkinUrl('images/category/pequenos_animais/20.png'); ?>"
					 alt="Cliente" width="168" height="168"/><br>
			<span class="title">14:05</span>
			<span class="description">colheita de exame</span>
		</div>
		<div class="time-col">
			<img class="lazy"
					 data-original="<?php echo $this->getSkinUrl('images/category/pequenos_animais/21.png'); ?>"
					 alt="Cliente" width="168" height="168"/><br>
			<span class="title">14:12</span>
			<span class="description">realização do teste IDEXX</span>
		</div>
		<div class="time-col">
			<img class="lazy"
					 data-original="<?php echo $this->getSkinUrl('images/category/pequenos_animais/22.png'); ?>"
					 alt="Cliente" width="168" height="168"/><br>
			<span class="title">14:21</span>
			<span class="description">resultados e diagnóstico</span>
		</div>
		<div class="time-col">
			<img class="lazy"
					 data-original="<?php echo $this->getSkinUrl('images/category/pequenos_animais/23.png'); ?>"
					 alt="Cliente" width="168" height="168"/><br>
			<span class="title">14:27</span>
			<span class="description">cliente liberado</span>
		</div>

	</div>
</div>

<?php echo $this->getChildHtml('contact'); ?>

<script>
	jQuery('#lk-block1').click(function(el) {
		el.preventDefault();

		jQuery('html,body').animate({scrollTop: jQuery("#block2").offset().top},'slow');

		return false;
	});

	jQuery('#lk-block3').click(function(el) {
		el.preventDefault();

		jQuery('html,body').animate({scrollTop: jQuery("#block4").offset().top},'slow');

		return false;
	});
</script>

<div class="main-container container col1-layout main-home">
	<div class="main">
		<div class="col-main">