</div>
</div>
</div>

<div class="idexx-breadcrumb">
	<div class="inner default-page-width">
		<img src="<?php echo $this->getSkinUrl('images/category/breadcrumb/snap.png'); ?>" border="0" width="277" height="75" class="overlay" />
		<img id="145158" src="<?php echo $this->getSkinUrl('images/category/breadcrumb/breadcrumb.jpg'); ?>" border="0" width="950" height="75" orgWidth="950" orgHeight="75" usemap="#145158" alt="" />
		<map name="145158" id="145158">
			<area id="home" alt="Home" title="Home" href="/" shape="rect" coords="0,0,195,75" style="outline:none;" target="_self"     />
			<area id="cag" alt="Animais de companhia" title="Animais de companhia" href="/cag" shape="rect" coords="195,0,405,75" style="outline:none;" target="_self"     />
			<area id="snaps" alt="Snaps" title="Snaps" href="/cag/snaps" shape="rect" coords="409,0,642,75" style="outline:none;" target="_self"     />
			<area id="equipamentos" alt="Equipamentos" title="Equipamentos" href="/cag/equipamentos" shape="rect" coords="643,0,909,75" style="outline:none;" target="_self"     />
		</map>
	</div>
</div>

<div class="idexx-breadcrumb-mobile">
	<a href="<?php echo Mage::getBaseUrl() ?>"><i class="fa fa-home"></i></a>
	<i class="fa fa-angle-right"></i>
	<a href="/cag">Animais de companhia</a>
	<i class="fa fa-angle-right"></i>
	<span>SNAP</span>
</div>


<div style="background-image: url(<?php echo $this->getSkinUrl('images/category/snaps/1.jpg'); ?>)" class="category-image">
	<div class="page-title category-title">
		<div class="inner">
			<h1>Pense rápido, pense <strong>snap</strong></h1>
			<p class="subtitle">Os testes SNAP utilizam a tecnologia IDEXX ELISA (Enzyme-Linked Immunosorbent Assay), fornecendo em minutos análises de alta precisão, equivalentes às realizadas em um laboratório de referência.</p>
		</div>
	</div>
</div>

<div class="main-container container col1-layout default-page-width">
	<div class="main">
		<div class="col-main">



<div class="block1 two-columns">
	<div class="column left border fat">
		<h1>Sensibilidade e especificidade que geram confiabilidade</h1>
		<p>A tecnologia ELISA presente no SNAP® utiliza conjugado e substrato exclusivos que amplificam os resultados. O processo de fluxo bidirecional evidencia a ligação antígeno-anticorpo, proporcionando alta sensibilidade e resultados confiáveis. Preciso, simples e econômico, SNAP® é a tecnologia de diagnóstico rápido ideal para uso em consultórios, clínicas e hospitais veterinários.</p>
		<br /><br /><br /><br />
		<div class="two-columns">
			<div class="column left">
				<h3>Doenças Infecciosas</h3>
				<ul class="level1">
					<li>
<!--						<a href="/snap-canino-4dx-1x30-plus" title="4Dx Plus">-->
							<i class="fa fa-angle-right"></i> 4Dx Plus
							<ul class="level2">
								<li>
									- Anaplasma
								</li>
								<li>
									- Dirofilaria
								</li>
								<li>
									- Doença de Lyme
								</li>
								<li>
									- Ehrlichia
								</li>
							</ul>
<!--						</a>-->
					</li>
					<li>
<!--						<a href="/snap-canino-4dx-1x30-plus" title="Leishmani">-->
							<i class="fa fa-angle-right"></i> Leishmania
<!--						</a>-->
					</li>
					<li>
<!--						<a href="/snap-canino-4dx-1x30-plus" title="Combo Felino">-->
							<i class="fa fa-angle-right"></i> Combo Felino
							<ul class="level2">
								<li>
									- FeLV
								</li>
								<li>
									- FIV
								</li>
							</ul>
<!--						</a>-->
					</li>
					<li>
<!--						<a href="/snap-canino-4dx-1x30-plus" title="Parvovirose">-->
							<i class="fa fa-angle-right"></i> Parvovirose
<!--						</a>-->
					</li>
					<li>
<!--						<a href="/snap-canino-4dx-1x30-plus" title="Giardia">-->
							<i class="fa fa-angle-right"></i> Giardia
<!--						</a>-->
					</li>
				</ul>

			</div>
			<div class="column right">
				<h3>Pancreáticos</h3>
				<ul class="level1">
					<li>
<!--						<a href="/snap-canino-4dx-1x30-plus" title="cPL">-->
							<i class="fa fa-angle-right"></i> cPL
<!--						</a>-->
					</li>
					<li>
<!--						<a href="/snap-canino-4dx-1x30-plus" title="fPL">-->
							<i class="fa fa-angle-right"></i> fPL
<!--						</a>-->
					</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="column right thin">
		<div class="image">
			<img class="lazy"
				 data-original="<?php echo $this->getSkinUrl('images/category/snaps/2.jpg'); ?>"
				 alt="Cliente" width="332" height="547"/>
		</div>
		<p>Automatize o seu fluxo de trabalho.<br />Reduza a chance de erros humanos e integre os resultados do seu SNAP® com o Dispositivo Móvel SNAP Pro™ .</p>
	</div>
	<div class="clear"></div>
</div>

<div class="block2">
	<h1>Modo de usar</h1>
	<hr class="hundred" />
	<br /><br /><br />
	<div class="image">
		<img class="lazy"
			 data-original="<?php echo $this->getSkinUrl('images/category/snaps/3.jpg'); ?>"
			 alt="Modo de usar" width="977" height="599"/>
	</div>
</div>

<div class="block3">
	<h1>Como funciona</h1>
	<hr class="hundred" />
	<br /><br /><br />
	<img class="lazy"
		 data-original="<?php echo $this->getSkinUrl('images/category/snaps/4.jpg'); ?>"
		 alt="Legenda" width="301" height="94"/>

	<br /><br /><br /><br /><br />

	<div class="image">
		<img class="lazy"
			 data-original="<?php echo $this->getSkinUrl('images/category/snaps/5.jpg'); ?>"
			 alt="Legenda" width="968" height="631"/>
	</div>

	<br /><br /><br /><br /><br /><br /><br />

	<div class="image">
		<img class="lazy"
			 data-original="<?php echo $this->getSkinUrl('images/category/snaps/6.jpg'); ?>"
			 alt="Legenda" width="971" height="705"/>
	</div>
</div>