<?php
    $_helper    = $this->helper('catalog/output');
	if (!$_category = $this->getCurrentCategory())
	{
		$_category = Mage::getModel('catalog/category')->load($this->getCategoryId());
	}
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
    
?>
<div class="brands-block">
	<?php if ($this->getTitle()) : ?>
		<h1><?php echo $this->getTitle(); ?></h1>
	<?php else : ?>
    	<h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
	<?php endif; ?>

	<hr />

	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

	<?php if($_description=$_category->getDescription()): ?>
    <div class="category-description std">
        <?php echo $_helper->categoryAttribute($_category, $_description, 'description'); ?>
    </div>
    <?php endif; ?>

	<?php echo $this->getChildHtml('brands_list'); ?>
</div>

<br /><br />
