<?php

require_once '../../../app/Mage.php';
umask(0);

ini_set('display_errors', 1);
ini_set('max_execution_time', 600);

Mage::app()->setCurrentStore(8);


$websiteId = 5;

//goto read;

Echo 'Atualizando a base de cliente do Vladimir:'. "\n";


$array = array(

	array(
		'11' => array(
			array("1001","ANIMAL DE ESTIMAÇAO PET SHOP VET. LTDA M","animaldestimacao@yahoo.com.br"),
			array("1002","HERDOG COMERCIO DE RAÇOES ACESS. LTDA","herdog@terra.com.br"),
			array("1006","ADRIANA CRISTINA SPARACIALI PET SHOP - M"),
			array("1034","BICHO AMIGO PET SHOP LTDA"),
			array("1038","BICHO NAO FALA COM LTDA ME"),
			array("1043","CAMILA LOUISE BATISTA","camilalouise@uol.com.br"),
			array("1190","ODRACIR E OIGRES AVICULTURA LTDA","romulo_urbano@uol.com.br"),
			array("1229","SHEILA LUCIA FERREIRA","sheila_vet@hotmail.com"),
			array("1258","PET FARMA COMERCIO DE RACOES LTDA"),
			array("1305","ROSELAINE VICENTIN"),
			array("1307","S & QUINTAL AVICULTURA LTDA"),
			array("1405","ARCA DE NOE COM LTDA ME","petarcadenoe@bol.com.br"),
			array("1429","ADILSON MANDARI ORTIZ ME","cabecadebagre@hotmail.com.br"),
			array("1435","ALCIONE ALCIDES DA SILVA","alcione.alcides@ig.com.br"),
			array("1437","AMANDA RODRIGUES DE OLIVEIRA","amanda_med_vet@hotmail.com"),
			array("1443","ANDREI JOSE GENEROSO MARQUI","ajgmvet@hotmail.com"),
			array("1492","ANNE LOVISE LAUBACH"),
			array("1493","AVICULTURA D ABRIL LTDA ME"),
			array("1495","AVICULTURA ITANGA LTDA ME","wdmzloti@terra.com.br"),
			array("1500","CAO PESCADOR AGROPECUARIA LTDA ME","caopescador@hotmail.com"),
			array("1502","CHEYANNE MAZIVIERO","cheyanne@uol.com.br"),
			array("1519","CHRISTIAN MIGUEL GUILLARDUCCI PET SHOP M","cristianch@superig.com.br"),
			array("1523","CLAUDIA PIMENTEL DA SILVA SANTOS","claudiaesergio@globo.com"),
			array("1647","CLAYDE MARIA DOMINGUES SANTO ME"),
			array("1653","DILAN AVICULTURA LTDA ME","cccenter@uol.com.br"),
			array("1656","DOG CHIC BANHO E TOSA LTDA ME"),
			array("1659","EDUARDO SANTANA DA ROCHA","eduardosant@uol.com.br"),
			array("1661","ELTON ANTONIO DOS REIS","vacinacaovet@ig.com.br"),
			array("1663","FABIO ALVES RODRIGUES PET SHOP ME","saudeanimalpet@hotmail.com"),
			array("1666","FABIO CARLOS RAMALHO","fcramalho@hotmail.com"),
			array("1668","FABIOLA UVO ME","fabiola.uvo@bol.com.br"),
			array("1669","FELIPE HENRIQUES PEREIRA"),
			array("1672","CASA DE RACOES RIO BRANCO LTDA ME","casaderacaoriobranco@hotmail.com"),
			array("1673","GILDABERTO LOPES DE MEDEIROS - ME"),
			array("1674","GILSON APARECIDO GOMES DA SILVA ME","giabsolut@hotmail.com"),
			array("1677","IOLANDO TADEU CASALECCHI ME","tadeucasalecchi@ig.com.br"),
			array("1678","IRMAOS BELTRAME COMERCIAL E AGRO. LTDA M","gemmius@hotmail.com"),
			array("1679","ISMAEL DE CAMARGO ABBADE","vetcaicara@hotmail.com"),
			array("1680","JACKSON DE ALMEIDA PIMENTEL AVICULTURA M","petmaximo@ig.com.br"),
			array("1681","JAIR P DE ALMEIDA AVICULTURA ME","jpires5218@terra.com.br"),
			array("1685","JP AGRO CENTER COMERCIAL AGROPECUARIA LT","jpagrocenter@uol.com.br"),
			array("1686","JULIO TAKASHI SAKAI ME","julio.sakai@ig.com.br"),
			array("1687","LUCIMARA SANTOS DOS REIS","lului6@ig.com.br"),
			array("1693","MARCIO JOSE MASSELA ME"),
			array("1694","MARIELA HERNANDEZ","clivetmed@hotmail.com"),
			array("1696","MAXIMO E SILVA COM DE RACOES LTDA ME"),
			array("1697","MENDONÇA & QUINTAL LTDA ME"),
			array("1699","MR PINSHER PET SHOP LTDA ME","mrbarno@ig.com.br"),
			array("1700","NELSON JOSE ROMERO"),
			array("1703","PET BULL COM. DE RAÇOES LTDA ME","filas@contimax.com.br"),
			array("1704","PET FIORELLI PET SHOP LTDA ME","regeto@terra.com.br"),
			array("1705","PET SHOP PICA PAU LTDA ME","rudl@ig.com.br"),
			array("1706","PET SHOP SCOOBY DOO LTDA","leostecanella@yahoo.com.br"),
			array("1708","PET VIDA COMERCIO DE PRODUTOS P/ ANIMAIS","petlive@hotmail.com"),
			array("1711","PROJETO BICHO COM. DE RAÇOES E ART. P/ A","aljperera@yahoo.com.br"),
			array("1712","RABUGENTOS PET SHOP LTDA ME","ronaldo.beltron@uol.com.br"),
			array("1713","RACAOLANDIA COMERCIAL LTDA"),
			array("1715","RAIMUNDA MARIA COELHO ME","julicoelhof@hotmail.com"),
			array("1716","RAQUEL APARECIDA GOMES ME"),
			array("1717","REGIANE STINNPEL ME","bicharadaciabella@hotmail.com"),
			array("1718","REGINA C.C. PERUSSO ME","reginaperusso@hotmail.com"),
			array("1719","REGINA IONAMINE NAKAMA ME","nutripetracoes@bol.com.br"),
			array("1720","RENATA APARECIDA SILVA PET SHOP  ME","fernanda.ap.silva@gmail.com"),
			array("1722","ROGERIO PALMEIRA ME"),
			array("1724","SABRINA MAYUME FUJIY CLINICA VETERINARIA","tocadosbichos@hotmail.com"),
			array("1725","SANDRA ANTONIA NASCIMENTO","aviculturapan@uol.com.br"),
			array("1732","SUSETE P. NUNES PASSOS AVICULTURA ME"),
			array("1733","THIAGO SILVA OLBI ME","afamiliapet@live.com"),
			array("1736","VANDERLEI SAPUCAIA DOS SANTOS"),
			array("1738","ZULEIMAR & TAIS COMERCIO DE RAÇOES LTDA"),
			array("1810","AVICULTURA A P LTDA*"),
			array("1811","AVICULTURA QUATRO PATAS LTDA ME*","quatropataspetshop@ig.com.br"),
			array("1815","BIG VET COML LTDA ME*"),
			array("1971","GREEN PET VETERINARIA LTDA","vetgreenpet@gmail.com"),
			array("1975","SPEED DOG PET SHOP RAÇOES E JARDIM LTDA","roberto.cruz6@gmail.com"),
			array("2112","DAVID LOPES MIRANDA"),
			array("2163","JOAO WAGNER CORREA LEMOS","veterinario.lemos@ig.com.br"),
			array("2185","CRISTIANO FERREIRA DE LIMA - RAÇÕES","rmrações.cristiano@hotmail.com"),
			array("2265","SOLIS ARTIGOS P/ ANIMAIS E PESCA LTDA","chicosolis69@yahoo.com.br"),
			array("2314","HOSPITAL CAIEIRAS VETERINARIA LTDA","hcvmitiko@yahoo.com.br"),
			array("2336","KARINA MARCOS CASSANDRE ME","veterinariasaudepet@gmail.com"),
			array("2350","AVICULTURA SOL COMERCIAL LTDA"),
			array("2380","PAULO OLIVEIRA DOS SANTOS ME"),
			array("2447","CICERO PEDRO DA SILVA AVICULTURA-ME"),
			array("2486","PIRITUCAO COMERCIAL LTDA ME"),
			array("2536","AUGUSTO CESAR DANTAS PATITUCCI-ME"),
			array("2592","E.M. DOS SANTOS SILVA RAÇÕES ME","joaoalvessilva2010@hotmail.com"),
			array("2659","VANESSA MAGNUSSON","vanmagnu@yahoo.com.br"),
			array("2676","FERNANDA REGINA CAJERON","frcajeron@yahoo.com.br"),
			array("2706","UBIRAJARA PRECHEDES DE SOUZA","ubirajarasouza@yahoo.com.br"),
			array("2742","AGROVET CLINICA VETERINARIA LTDA - EPP","ionealarcon@gmail.com"),
			array("2782","DIEGO POLIDO GALERA - ME","agropetsaomiguel@ig.com.br"),
			array("2847","MEDIVAC COMERCIO DE PRODUTOS AGROPECUARI","medivac@ig.com.br"),
			array("2876","SUELEN MARIANO DA SILVA ME SPA PET CARE","spapetcare@hotmail.com"),
			array("2877","DGA GURGEL ME","gurgelvet@hotmail.com"),
			array("2889","MARCIA CONCEICAO DE MORAIS - ME","marcia.mgarcia@yahoo.com.br"),
			array("2919","PET CLARIS COMERCIO DE RACAO EIRELI - ME","petclaris@gmail.com"),
			array("2926","AMA CLINICA VETERINARIAE COMERCIO","amaveterinaria@hotmail.com"),
			array("2936","FERNANDA DOS SANTOS GOMES"),
			array("2941","R.M.N. ARAUJO PET SHOP - ME","financeiro@puppyecia.com.br"),
			array("2964","SILVIA DAS GRACAS B. MASSELA - ME","agroveracenter@gmail.com"),
			array("2976","RODRIGO DE CASTRO NOVAES - ME","francopet193@gmail.com"),
			array("3006","PET CENTER FREGUESIA LTDA - ME","vendas@petcenterfreguesia.com.br"),
			array("3010","CAROLINA ROCHA HELENO PET BBMAX - ME","petbbmax@gmail.com"),
			array("3019","JULIETA PEREIRA PET - SHOP","danielapaulopoli@hotmail.com"),
			array("3020","FERNANDA DOS SANTOS ARAUJO TRINTADE - ME","maucao.maluats@gmail.com"),
			array("3035","EDSON LAZARO FRANCISCON DE MORAES"),
			array("3038","W.CESAR GUIMARAES-RACOES - ME"),
			array("3049","ESPACO CAO PET SHOP VETERINARIA LTDA - M","espacocaoecia@gmail.com"),
			array("3089","JUVENAL SOARES DO NASCIMENTO 03702714839","j-soares-nascimento2014@bol.com.br"),
			array("3093","ERICA BELAUS ROMERA 28091241836","petshopbichofofo@hotmail.com"),
			array("3100","MARCIO INFORZATO SOARES DE CAMARGO-ME","marcioinforzato@gmail.com"),
			array("3119","FARO PET SHOP VETERINARIA LTDA - ME","saudeanimalpet@hotmail.com")
		),
		'23' => array(
			array("1007","AVICULTURA FURLAN LTDA ME","furlanpetshop@hotmail.com"),
			array("1010","ADRIANE APARECIDA POSSATO PET SHOP -EPP","dripossatto@hotmail.com"),
			array("1017","ADRIANO VILLAS PET COM. DE RAÇOES LTDA M","villapet@superig.com.br"),
			array("1025","ALPHA CAES COMERCIAL LTDA ME"),
			array("1028","ALPHA CONDE COMERCIO PROD. VET. DE SERVI","atendimento@veterinarioalphaconde.com.br"),
			array("1033","ALPHA STAR PET & SHOP COM. ALIM.P/ ANIM.","alphastar.petshop@interair.com.br"),
			array("1041","ANDREA GRANZOTTO ME","vet.del@uol.com.br"),
			array("1048","ANIMAL PLACE PET SHOP"),
			array("1052","ARCA DOS BICHOS PET CLIN. VETERINARIA LT","arcadosbichos@uol.com.br"),
			array("1055","AVICULTURA DESTRA LTDA ME"),
			array("1063","BENESI COMERCIO DE RAÇOES LTDA ME","masiandrade@terra.com.br"),
			array("1066","CANELLO COM. DE ARTIGOS VETERINARIOS","vetgil@ig.com.br"),
			array("1073","CARLOS EDUARDO DA SILVA AVICULTURA ME","ciadogpetshop@ciadogpetshop.com.br"),
			array("1082","CENTRO VETERINARIO BUENO VET LTDA ME","buenovetrx@gmail.com"),
			array("1087","CLIDAPRI PET & SHOP COM. ALIM. P/ ANIM.","clidapri.petshop@yahoo.com.br"),
			array("1095","COMERCIO VETERINARIO BRITANIA LTDA"),
			array("1097","CRISTINA TEIXEIRA GONÇALVES ME","financeiro@viladoscaes.com.br"),
			array("1100","DELCIO RIZZO","vet.rizzo@ig.com.br"),
			array("1101","DOGAO RAÇOES E AGROPECUARIA LTDA ME","dogaoracoes@hotmail.com"),
			array("1104","EDUARDO ANDRE FERNANDES VETERINARIA ME","duafvet@gmail.com"),
			array("1105","PET SHOP CHACARA INGLESA LTDA - ME","elianemteodoro@hotmail.com"),
			array("1106","ENISTI COMERCIO DE ALIMENTOS PARA ANIMAI","enisti@hotmail.com"),
			array("1107","FABIO AURIEMA E DANIELA GIRALDI PET SHOP","companhiaanimal@uol.com.br"),
			array("1109","FASHION PET COMERCIO E SERVIÇOS LTDA","fashionpet.vet@uol.com.br"),
			array("1111","FLOR E AVICULTURA JARDIM FELICIDADE LTDA","jdfelicidadepetshop@ig.com.br"),
			array("1114","FRANCISCO CELIO LEITE DE ARAUJO PET SHOP","celiopet@hotmail.com"),
			array("1117","GILDO ALEGRI","mi_alegri@hotmail.com"),
			array("1126","PET SPA MORADA DOS BICHOS EIRELI-ME","gunia@chateaudosbichos.com.br"),
			array("1128","HOSPITAL VETERINARIO VET CARE LTDA ME","lila.sanchez@uol.com.br"),
			array("1133","JAQUELINE LUIS FRANKLIN"),
			array("1137","JESUS RAÇOES E MERCEARIAS LTDA ME"),
			array("1154","JOSE EUGENIO FREDIANI ME","eugenio.frediani@hotmail.com"),
			array("1164","MAHO PET SHOP LTDA ME","tkeshitkr@uol.com.br"),
			array("1210","MARGARETE PIRES DE SOUZA","margarete_aumihau@hotmail.com"),
			array("1211","MARIA DO CARMO DE OLIVEIRA PAULINO PET S","eduardonishida@uol.com.br"),
			array("1212","MIMANIMAL CLINICA VETERINARIA E PET SHOP","afukuya@ig.com.br"),
			array("1215","PAULO HENRIQUE DE LIMA"),
			array("1218","PET SHOP JAGUARA LTDA ME","petshopjaguara@hotmail.com"),
			array("1220","PET VILLE COMERCIAL LTDA ME","sauaia@superig.com.br"),
			array("1222","PONTO CAO COMERCIO E SERVIÇOS LTDA ME"),
			array("1223","RENATA APARECIDA PEREIRA CHAVES ME","renatapmaurus@hotmail.com"),
			array("1224","RENATA MATHIAZO DANTE","renata@petsafari.com.br"),
			array("1226","RICHARD PERCEVAL ME"),
			array("1227","SERGIO ROBERTO DALHA VALHE","sergiovalhes@terra.com.br"),
			array("1228","SERGIO SOUZA SOARES ME"),
			array("1232","TATIANA MANCZYK"),
			array("1234","VET CAO COM. ANIMAIS ESTIMAÇAO PET SHOP","vetcao@vetcao.com.br"),
			array("1236","ZAPPABARROS COM. DE PRODUTOS P/ ANIMAIS","ed-gb@hotmail.com"),
			array("1434","AMOR D'CAO PET SHOP LTDA","sarafarjado@ig.com.br"),
			array("1436","RAFAELA D' ARCO - ME","rafaela.darco@itelefonica.com.br"),
			array("1438","ANGELA PEREIRA DA COSTA SUMAN - ME"),
			array("1463","BICHO VERDE AGUA CLINICA VETERINARIA LTD"),
			array("1467","C BUENO & P FONSECA COM. DE RACAO LTDA","paulafonseca@terra.com.br"),
			array("1469","C LIMA DA SILVA ME"),
			array("1489","CARLOS EDUARDO MEYER","edu.meyer@uol.com.br"),
			array("1522","CLINICA VETERINARIA HIKARU","122388.174@cofrenfe.com.br"),
			array("1545","CLINICA VETERINARIA REINO DOS PETS LTDA","reinodospets@hotmail.com"),
			array("1547","PET SHOP E CLINICA VETERINARIA  FINOCCHI","angela.regina.finocchiaro@gmail.com"),
			array("1568","DANTAS & NOGUEIRA PET SHOP LTDA ME","clinvet.animal@hotmail.com"),
			array("1577","EVANDRO GIACOSA CORATO BANHO E TOSA ME","vivicorato@hotmail.com"),
			array("1608","JOAO LEANDRO DO NASCIMENTO"),
			array("1650","KM 18 PET SHOP & CLINICA VETERINARIA LTD","clinicakm18@hotmail.com"),
			array("1742","MAR & FAB COMERCIO DE RACOES LTDA ME","epg.1001@gmail.com"),
			array("1744","MARIA DE LOURDES FONSECA PET SHOP"),
			array("1754","MILTON YUKIO KOMATSU PET SHOP ME","marcelo.pedro2007@ig.com.br"),
			array("1758","OSASVET PRODUTOS E SERVICOS VETERINARIOS","osasvet@bol.com.br"),
			array("1763","PET MANIA CORINTINHA COM DE ARTIGOS VET"),
			array("1765","PET SHOP MARCELO ONISHI LTDA ME","marceloonishi@uol.com.br"),
			array("1768","PET SHOP POINT ARTIGOS P/ANIMAIS LTDA ME"),
			array("1771","PET SHOW DOG COM. E SERV LTDA","elizabethpolachini@hotmail.com"),
			array("1790","SANTA TEREZA COMERCIO DE RAÇOES P/ ANIM.","everton.vieira@superig.com.br"),
			array("1797","TRINTA PET SHOP E VETERINARIA LTDA ME","claytoncarvalho@hotmail.com"),
			array("1799","VALQUIRIA ARANTES FERNANDES GOMES ME"),
			array("1803","VET COMPANY PET SHOP LTDA ME"),
			array("1806","FABIANO GARCIA NAVES ME"),
			array("1926","PEREIRA & SILVA CAMPING  AVICULTURA LTDA","candidomotense@terra.com.br"),
			array("1948","SEKAY COMERCIO E REPRESENTAÇAO LTDA*","compras@caesegatos24h.com.br"),
			array("1961","BELO BICHO PET SHOP COMERCIO DE ANIMAIS"),
			array("1962","COMERCIAL AGROPECUARIA I.R.F.G LTDA ME"),
			array("1966","LKA COM. DE ART. PARA ANIMAIS DE ESTIMAÇ","sandrakomatu@uol.com.br"),
			array("1967","M. MORATO ALPHAVILLE CANIL LTDA"),
			array("1969","POLICLINICA VETERINÁRIA PORTINARI S/C LT","polivetportinari@ig.com.br"),
			array("1999","ADRIANA CONCEIÇAO PELLEGRINI"),
			array("2090","PET SHOP COMERCIAL LTDA ME LOJA 01","amoraoslatidos@hotmail.com"),
			array("2107","MAHO PET SHOP LTDA ME","mahopetshop@uol.com.br"),
			array("2178","LUCIANA MARIA TALARICU PORTO","kingveterinaria@gmail.com"),
			array("2251","JOSE ARAUJO DE MORAIS FILHO*","camilazanqueta@hotmail.com"),
			array("2311","MED CENTER PET SHOP LTDA ME","lelotati@msn.com"),
			array("2351","GATO PONTO CÃO CLÍNICA VETERINÁRIA E PET","cattdogs@hotmail.com"),
			array("2394","CATARINA CAMPOS CORTEZ","catarina_cortez@hotmail.com"),
			array("2419","ZULEIKA FERREIRA NUNES DOS REIS","centrodeesteticacarina@hotmail.com"),
			array("2460","ELIEL MARTINS DE ALMEIDA ME","aviculturatatui@gmail.com"),
			array("2473","EDUARDO KAWAGUTI FUJIMURA-ME","edukf@yahoo.com.br"),
			array("2495","DANIELLE APARECIDA DE ALMEIDA GONÇALVES","danielleaparecida2005@yahoo.com.br"),
			array("2513","PET SHOP MOURA LTDA EPP","petshopmoura@gmail.com"),
			array("2554","ESPACO ANIMAL COMERCIAL DE RACOES E PLAN","espacoanimal2011@gmail.com"),
			array("2627","MELINA PRUDENTE CORREA ME","tania_prudente@ig.com.br"),
			array("2634","CRISTIANO MILESI GIORDANO","milleri_ariane@hotmail.com"),
			array("2677","EDUARDO FERREIRA ME","alphapet.alphaville@gmail.com"),
			array("2701","ROBERTA SILVEIRA","clinic_pet@hotmail.com"),
			array("2713","ADRIANE APARECIDA POSSATTO PET SHOP - ME","dripossatto@hotmail.com"),
			array("2716","JENNIFER VERISSIMO DE LIMA","marcelo_carvalhoadm@hotmail.com"),
			array("2736","ATACADAO DA RAÇÃO COM. DIST. LTDA - EPP","atacadaodaracao@uol.com.br"),
			array("2745","D ANDREOLI COM. E SERV. DE PET SHOP","pataspetshop@hotmail.com"),
			array("2781","LAMUSSI GUZO PET SHOP LTDA - ME","strangisvete@terra.com.br"),
			array("2794","STAR DOG PET SHOP COM DE RACAO ACESS E S","gilberto.iwashita@uol.com.br"),
			array("2821","NOVA GRANADA PET SHOP LTDA - EPP","granadapet@gmail.com"),
			array("2864","ROGERIO CARVALHO VETERINARIO - ME","clinicarogervet@hotmail.com"),
			array("2872","JOAN ROBERT B. PALAZZO","joanrobert@uol.com.br"),
			array("2881","KEILA REGINA RODRIGUES OLIVEIRA 35132881"),
			array("2887","MICHELE PALADINE YUNAN","patitas2665@yahoo.com.br"),
			array("2894","R.S.MORAES COMERCIO E SERVICOS DE PET SH","pataspetshop@hotmail.com"),
			array("2904","PET MED COMERCIO E EMBELEZAMENTO LTDA -","edukf@yahoo.com.br"),
			array("2921","CLINICA & PET SHOP ALDEIA EIRELI","aldeiapet@gmail.com"),
			array("2938","PET SHOP ARAGAO&SOUZA COM.VAREJISTA DE A","caminhodospets@gmail.com"),
			array("2940","GABRIELA CASTELLON FIGUEIREDO - ME","studiopet.studiopet@gmail.com"),
			array("2947","CENTRO VETERINARIO E COMERCIAL HEATH & C","katia.massoneto@uol.com.br"),
			array("2952","RENOVA PET SHOP LTDA ME","renovapet@outlook.com"),
			array("2981","EDUARDO GAUDENCIO ADRIANO","elianemteodora@hotmail.com"),
			array("3000","VET MAIS SAUDE LTDA - ME"),
			array("3025","CRISTIANE GIMENEZ THIZON-ME","qlate@qlateecompanhia.com.br"),
			array("3032","SERGIO HORODENKO SOARES","hgs.vet@gmail.com"),
			array("3052","KELLY HARUMI GOMES MOTOORI - ME","leandro.motoori@hotmail.com"),
			array("3109","LAERCIO MARTINS GONÇALVES","laerciomedvet@uol.com.br")
		),
		'38' => array(
			array("1432","AGROPLUS PRODUTOS AGROPECUARIOS LTDA","agroplus@itelefonica.com.br"),
			array("1442","AGRO AVICULTURA ZANETTI LTDA - ME"),
			array("1461","AVICULTURA MONTE ALEGRE LTDA ME"),
			array("1466","BOUTIQUE LATIDOS & MIADOS LTDA ME","boutique.dosbichos@hotmail.com"),
			array("1494","CASA DE RACOES EXOTICA LTDA EPP","exoticanfe@uol.com.br"),
			array("1499","CAVALEIRO PET SHOP LTDA ME","marcinha_vet@hotmail.com"),
			array("1501","CELEIRO DO EMBU COMERCIAL LTDA ME","celeirodoembu@terra.com.br"),
			array("1504","CERCADO GRANDE COM.DE RACOES LTDA","cercadogrande@hotmail.com"),
			array("1509","CHERLE RENCK PRODUTOS VETERINARIOS LTDA","bottas@ig.com.br"),
			array("1512","CHINO'S EMPORIO ANIMAL LTDA"),
			array("1520","CLINICA VETERINARIA ELEOTERIO LTDA ME","andressaeleoterio@hotmail.com"),
			array("1524","CLINICA VETERINARIA MORADA DOS ANIMAIS","moradadosanimais@bol.com.br"),
			array("1552","COMERCIO DE PRODUTOS PIRAJUSSARA LTDA ME","clandosbichos1@gmail.com"),
			array("1554","COMERCIAL IMAGON LTDA ME","claudio_barreiros@hotmail.com"),
			array("1557","COMERCIO DE ARTIGOS VETERINARIOS LTDA ME"),
			array("1564","DALY VET COMERCIO LTDA ME","canilcaodemel@uol.com.br"),
			array("1569","DIEGO LUIZ HENRIQUES ME","petshopninos@yahoo.com.br"),
			array("1570","DU DOG CLINICA DE ESTETICA ANIMAL LTDA M","contato@dudog.com.br"),
			array("1571","EDSON DALEFFE - ME","secretaria@dredsom.com.br"),
			array("1572","EDUARDO MENCK"),
			array("1573","ELISABETH TOSHIMI MARUYAMA FLORICULTURA"),
			array("1576","ESTILO CAO PET SHOP LTDA ME "),
			array("1584","FIEIS FERINHAS LTDA ME","fieisferinhas@hotmail.com"),
			array("1593","FRANCINE AZEVEDO SILVA PET SHOP LTDA ME","francine.vet@hotmail.com"),
			array("1594","FRANCISCO E ESCOLASTICA COM. AGRO LTDA M","vovonunes@ig.com.br"),
			array("1595","GIMATH PET SHOP LTDA ME","gilbertobaba@yahoo.com.br"),
			array("1600","GIOVANA VICCARO ME","clinicaveterinariagv@hotmail.com"),
			array("1652","KOZAKA COM. DE PROD. VET LTDA ME","cladosbichos2@gmail.com"),
			array("1665","LUCIANA YASSUDA - EPP","patasgarras2004@hotmail.com"),
			array("1739","LUCIMAR DA SILVA BARUERI ME","mayara_morokawa@hotmail.com"),
			array("1747","MARILDA IUMI CANIGUTI ROCHA"),
			array("1750","MAXI CENTER CAUCAIA COMERCIO DE PROD.AGR","gilberto2354@terra.com.br"),
			array("1752","CASA DO PEQUENO CRIADOR LTDA"),
			array("1753","MI PAGNI DE CARVALHO RACOES ME","daniellepagni@hotmail.com"),
			array("1757","OCTAVIO DE MELLO NERY ME","octavionery@hotmail.com"),
			array("1759","PATRICIA AMERICA NOVELLI E SILVA ME","animania.patricia@gmail.com"),
			array("1766","PET SHOP MONTE ALEGRE LTDA ME"),
			array("1770","PET SHOP SIQUEIRA DE CASTRO LTDA ME","clinicavettaboao@gmail.com"),
			array("1773","PIERRO COMERCIO DE PRODUTOS VETERINARIOS"),
			array("1777","RACOES MONTE AZUL LTDA ME","fiscal1@camiscontabilidade.com.br"),
			array("1779","RANCHO BRANCA LUZ LTDA ME","brancaluz2010@bol.com.br"),
			array("1781","RMJ PEREIRA TOSA ME","rmjvet@gmail.com"),
			array("1782","RUMO CERTO COMERCIO DE PRODUTOS VETERINA","rumocertopetshop@gmail.com"),
			array("1785","SAMIL F CHALUP"),
			array("1786","SANDRA BUCANA DE CAMIS"),
			array("1788","SANTA CATARINA COMERCIO DE RAÇOES E CERE","eujimenes@terra.com.br"),
			array("1791","SAXA´S DOG COMERCIO LTDA ME","simba49@ig.com.br"),
			array("1792","SOS ANIMAL COMERCIAL DE PRODUTOS VET LTD","luciano.vet@uol.com.br"),
			array("1793","TABA PRODUTOS AGROPECUARIOS LTDA ME","taba.agro@hotmail.com"),
			array("1795","TIJUCO RAÇOES LTDA ME"),
			array("1796","TREVO PROD AGROPECUARIOS LTDA ME","trevo-agropecuaria@ig.com.br"),
			array("1801","VARGEM GRANDE PAULISTA PET LTDA ME","cleide.rafa@gmail.com"),
			array("1802","VET E CIA CLINICA VETERINARIA LTDA","vetcia@hotmail.com.br"),
			array("1805","VIDA DO ANIMAL PET SHOP LTDA ME","puppylandssp2@hotmail.com"),
			array("1879","CLINICA  VETERINARIA SALVADOR FELIS LTDA","clinicavsf@uol.com.br"),
			array("1880","COMERCIO DE ARTIGOS PARA CHACAREIRO TIKO","racoestiko@bytes.com.br"),
			array("1934","PET SHOP GRANJA VIANA LTDA ME*","puppylandgerencia@gmail.com"),
			array("1942","RACOES COUNTRY SHOP LTDA*","countryshop@countryshop.com.br"),
			array("1950","SHARON REIBSCHEID GOLDMANN ME*","danisha@uol.com.br"),
			array("1984","ABE E EF COMERCIO DE RAÇOES LTDA ME"),
			array("1995","PET SHOP  POLICLINICA COMERCIAL LTDA","policlin@uol.com.br"),
			array("2114","GRANVET  CLINICA VETERINARIA LTDA ME","nelsonpalla@yahoo.com"),
			array("2209","ANA PAULA SCHULLER ME"),
			array("2222","PET SHOP CHIC TOSA LTDA ME"),
			array("2224","RACOES JC COTIA LTDA ME"),
			array("2287","ANDERSON AUGUSTO GONCALVES ME","racoes23@hotmail.com"),
			array("2414","AGROCENTER L.W.S. COMERCIAL LTDA ME"),
			array("2567","PLANETA VILLAGE PET RACOES LTDA ME","atendimento@villagepetshop.com.br"),
			array("2570","RODRIGO PARENTE CHIABAL ME","carol_maglio@hotmail.com"),
			array("2572","CASA DE RAÇÕES KAMERAN LTDA ME"),
			array("2588","ROBERTA MARIA LEITE ME","viannapet@ig.com.br"),
			array("2589","SHIRLEY DOS ANJOS BRITfloripacv@hotmail.comO ME"),
			array("2611","JANDIRA PET SHOP LTDA ME"),
			array("2628","POLICLINICA VETERINARIA TABOAO DA SERRA","polivet.taboao@hotmail.com"),
			array("2656","HAYLA CLINICA VETERINARIA LTDA ME","petvipbanhoetosa@gmail.com"),
			array("2658","CLINIVET CENTRO DE ATENDIMENTO VETERINAR","vet.fabiana@hotmail.com"),
			array("2717","PET E VET COMERCIO VAREJISTA DE ARTIGOS","dra.crysvet@gmail.com"),
			array("2734","RUBENS LANCEROTTI - ME"),
			array("2741","DANIELA M. FERREIRA DOS SANTOS - ME","cabelereira@oh.com.br"),
			array("2753","REGIVAL DA SILVA MACEDO OSASCO - ME"),
			array("2762","ANA VIEIRA DE MENEZES OSASCO - ME","dvldiniz@hotmail.com"),
			array("2763","PET SHOP AMIGO LEGAL LTDA - ME","alnaragoni@gmail.com"),
			array("2776","LLMP PET SHOP EIRELI - ME","andreatta2002@ig.com.br"),
			array("2786","ELI TRIGO REIS - ME."),
			array("2810","MARCIO GARBUGLIO - CENTRO VETERINARIO LT","mag_vet@hotmail.com"),
			array("2834","NISHIDOG PET CENTER LTDA - ME","nichidog@terra.com.br"),
			array("2837","PASCINI & ROQUE PET SHOP LTDA - ME","leo_pascini@hotmail.com"),
			array("2845","RODRIGO GONCALVES - ME","caninderacoes@r7.com"),
			array("2851","MURILO SALES PASCHOAL-ME","minducaopetshop@gmail.com"),
			array("2857","NELSON LADOGANO","a.ladogano@uol.com.br"),
			array("2859","CAMILA CARDOSO ROLO 32606436806","formosapetandcare@gmail.com"),
			array("2870","KARINA DA SILVA PEREIRA 38282942863","ka_sinicio@hotmail.com"),
			array("2874","FABIO VAZ DE OLIVEIRA - ME","janiasantos71@hotmail.com"),
			array("2897","RENATA BATISTA DE QUEIROZ"),
			array("2906","VIDA MANSA PET CENTER LTDA - ME","info@chasse.com.br"),
			array("2922","KELLY CRISTINA TUMIATE PET -SHOP - ME"),
			array("2989","COMERCIAL BOLINHA DE OSASCO LTDA-ME","pahoshino@hotmail.com"),
			array("3015","ADRIANA GARCIA PEREIRA SILVA ITAPEVI - M","kellen_cacau@yahoo.com.br"),
			array("3027","PRAJA COMERCIO E SERVIÇOS LTDA - ME"),
			array("3028","FABIANA DE MATOS PEREIRA - ME","fabimatos_pereira@hotmail.com"),
			array("3045","SOLANGE MESQUITA DE SOUSA MALAGUJIM - ME","financeiro@ipanemablocos.com.br"),
			array("3103","ROMMEL & ROSSI AGROPLUS COMERCIO DE RACO","agroplus.silavana@hotmail.co"),
			array("3121","ELEN B. DUCATTI VETERINARIA - ME","elenducatti@gmail.com")
		),
		'37' => array(
			array("1147","BERNARDO JOSE DICEZARE"),
			array("1150","BICHARADA ARTIGOS PARA ANIMAIS LTDA","bicharada@bicharada.com.br"),
			array("1165","C.V. VETERINARIO JD. BONFIGLIOLI S/C LTD","vetjdonfa@ig.com.br"),
			array("1169","CASA DE RAÇÕES AGUA BRANCA LTDA","lie.uehara@uol.com.br"),
			array("1171","CHIC DOG ALIMENTOS ACESSORIOS P/ CAES GA","valdeci@terra.com.br"),
			array("1193","CLINICA VETERINARIA PACAEMBU LTDA","contato @ centroveterinariopacaembu.com.br"),
			array("1195","CLINICA VETERINARIA POMPEIA PET SHOP LTD","adminstracao@hovetpompeia.com.br"),
			array("1197","COMERCIO DE ARTIGOS PARA CHACAREIRO TIKO","racoestiko@bytes.com.br"),
			array("1200","DOMINGOS ANTONIO MUCCIACITO JUNIOR ME","fauna.perdizes@gmail.com"),
			array("1203","ENCRENQUINHAS PET SHOP LTDA ME","stefano@encrenquinhas.com.br"),
			array("1431","MERCEARIA DO ANIMAL COM RACOES LTDA ME","carlos@merceariadoanimal.com.br"),
			array("1448","NOGEIRA & SANCHEZ RAÇOES LTDA ME"),
			array("1455","PET GARDEN CENTER COM LTDA","simone@qualipet.com.br"),
			array("1458","PET SHOP BIG HOUSE COMERCIO E SERV. LTDA","petbighouse@uol.com.br"),
			array("1460","PET SHOP GRANJA VIANA LTDA ME","puppylandgerencia@gmail.com"),
			array("1462","PET SHOP SANTOS COM.DE RAÇOES P/ CAES E","flavio.petshopsantos@gmail.com"),
			array("1474","PRO VIDA ANIMAL CLIN VET E PET SHOP LTDA","rodrigo@provida.com.br"),
			array("1475","RACOES COUNTRY SHOP LTDA","countryshop@countryshop.com.br"),
			array("1478","ROSA ALICE RODRIGUES TERUEL ME","clinicaveterinariapontapora@ajato.com.br"),
			array("1482","SEKAY COMERCIO E REPRESENTAÇAO LTDA","compras@caesegatos24h.com.br"),
			array("1484","SHARON REIBSCHEID GOLDMANN ME","danisha@uol.com.br"),
			array("1510","VITALI SAUDE ANIMAL E AMBIENTAL LTDA","nfe01@vitaliambiental.com.br"),
			array("1825","COMERCIO VAREJISTA DE PROD VET PET MAXI","petmaxiengenheiro@gmail.com"),
			array("1826","CONSULADO DA RACAO LTDA EPP*","santaines@consuladodaracao.com.br"),
			array("1827","CONSULADO DOS BICHOS PET SHOP LTDA EPP*","cantareira@consuladodaracao.com.br"),
			array("1836","FOCCUS COMERCIO DE ARTIGOS P/ ANIMAIS LT","adm2@hvetfoccus.com.br"),
			array("1857","HOSPITAL VETERINARIO SANTA INES LTDA*","pacheco@santainesvet.com.br"),
			array("1860","KI DOG PET SHOP LTDA*","andre@breeds.com.br"),
			array("1873","MORDE CAO COMERCIO E VETERINARIA LTDA*"),
			array("1892","PET MAXI COMERCIO DE ARTIGOS PARA ANIMAI","petmaxiinajar1@gmail.com"),
			array("1913","JOAO FRANCISCO GRANDINI JR PET SHOP ME*","grandinivet@hotmail.com"),
			array("2167","ANIMAL PLACE PET SHOP*"),
			array("2173","TAVELLI & TEIXEIRA COM.DE ART.P/ ANIM. D","bichosecoisas@terra.com.br"),
			array("2202","ANIMAL HEALTH CAES E GATOS LTDA*","compras@caesegatos24h.com.br"),
			array("2410","BANHO E TOSA MONTE ALEGRE LTDA -ME","caodella@uol.com.br"),
			array("2484","CANETE & CAVALCANTE PET SHOP LTDA-ME","dravanessa@puraamizade.com.br"),
			array("2527","EDSON FERREIRA DA SILVA ALOJAMENTO DE AN","angeli_ribeiro@globo.com"),
			array("2571","PET SHOP SE PRODUTOS VETERINARIOS LTDA M"),
			array("2603","CONSULADO DA RACAO LTDA - ME ***","dumont@consuladodaracao.com.br"),
			array("2784","ANIMAL PLACE PET SHOP LTDA ME","animalplace@hotmail.com"),
			array("2831","CONSULADO DA RACAO EIRELI - ME","benjamim@consuladodaracao.com.br"),
			array("2848","COMERCIO VAREJISTA DE PROD VET PETMAXI E","petmaxijacana@gmail.com"),
			array("2909","ALMEIDA & OLIVEIRA PET SHOP LTDA - EPP","stefano@encrenquinhas.com.br"),
			array("2910","COLLIE CENTRO CANINO LTDA - EPP","stefano@encrenquinhas.com.br"),
			array("2918","GRAZIELA GARIMA GRANDINI RIZZATO PET SHO","grazielagrandini@hotmail.com")
		),
		'40' => array(
			array("1238","ADAO SIQUEIRA  CAMPOS ME","racoeshercules@uol.com.br"),
			array("1239","ADRIANO BARILE DORA ME","rh@arca24h.com.br"),
			array("1241","ALL DOG COM. RAÇOES P/ ANIMAIS LTDA ME","elidio@terra.com.br"),
			array("1242","ALPHA PET CARE LTDA","alpha@alphaveterinaria.com.br"),
			array("1243","AMILCAR SILVA JUNIOR","guaruvet@gmail.com"),
			array("1249","AVICULTURA CHICO TRIPA LTDA ME","contkoyama@uol.com.br"),
			array("1251","AVICULTURA JOAO PAULO I LTDA ME","nagisamatsucka@bol.com.br"),
			array("1253","BIO DOG PET SHOP LTDA"),
			array("1261","BRASIL PET SHOP COM. DE ARTIG. P/ ANIMAI","brasil.pet@uol.com.br"),
			array("1264","CANIS FELIX COMERCIO E SERVIÇOS VET.LTDA","robertassa@hotmail.com.br"),
			array("1265","CAOCEIÇAO PET SHOP COMERCIO E SERVIÇOS L"),
			array("1268","CARDIAL COMERCIO DE RAÇOES LTDA ME","clinicavetcardial@hotmail.com"),
			array("1269","CARLOS VINICIUS OLIVEIRA DE ALMEIDA","contato@alamodog.com.br"),
			array("1276","CELSO LAUER DO NASCIMENTO ME","petshopcajuru@ig.com.br"),
			array("1282","CHM PET SHOP LTDA ME","marofas@ig.com.br"),
			array("1286","CLAUDIA DESTRO VIEIRA ME","atendimento@gautz.com.br"),
			array("1287","CLEUZA MARIA ORLANDO CALIMAN ME","glaucocaliman@hotmail.com"),
			array("1290","CLINICA VETERINARIA VALDEMAR PEREIRA ME","vetcat@ig.com.br"),
			array("1292","CLINICA VETERINARIA FRANCISCAO LTDA ME","franciscao@clinicafranciscao.com.br"),
			array("1293","CLINICA VETERINARIA PONTE GRANDE LTDA","pontegrande1982@hotmail.com"),
			array("1297","CLINICA VETERINARIA VILLA MARIA LTDA","contato@villamaria.com.br"),
			array("1301","CMKB CLINICA VETERINARIA LTDA"),
			array("1304","COLOSSO AVICULTURA LTDA","lamtwitter@terra.com.br"),
			array("1306","COMERCIO DE PRODUTOS VET. KIYOHARA LTDA","umekyhara@gmail.com"),
			array("1311","CRIS PET COMERCIO DE PROD. VETERINARIOS","piazzola@ig.com.br"),
			array("1312","DANIELA DE OLIVEIRA SOUZA ME"),
			array("1314","DUQUE DOG COM. DE ART. P/ ANIMAIS LTDA E","adrianafavaron@uol.com.br"),
			array("1315","ECOLOGICA COMERCIO DE ART. P/ ANIMAIS LT","nyvass@terra.com.br"),
			array("1316","EDEN TEIXEIRA DA CRUZ ME"),
			array("1321","GENAURA GUIMARAES SANTANA ME","aumiau@globomail.com"),
			array("1322","GIL COMERCIAL LTDA","doghouse@ig.com.br"),
			array("1324","TSUYOSHI YAMAGUTI"),
			array("1325","IARA CRISTINA PERES"),
			array("1326","ISHII VET COMERCIO DE PRODUTOS P/ ANIMAI","ka.ishii@hotmail.com"),
			array("1330","KATIA MAYUMI  HINO","k.ceu@hotmail.com"),
			array("1337","MI AU AVICULTURA E COMERCIO RAÇAO LTDA M"),
			array("1338","MILTON FERREIRA LIMA RAÇAO ME","petarany@hotmail.com"),
			array("1340","MISTER M PET SHOP LTDA ME","mister.m.petshop@gmail.com"),
			array("1341","MORGADOG COMERCIO DE RAÇOES LTDA ME","bionicao@petshopbionicao.com.br"),
			array("1347","PET SHOP BICHO SOLTO LTDA ME","kkavet@hotmail.com"),
			array("1348","PET SHOP BONINI LTDA ME","petshopbonini@hotmail.com"),
			array("1350","PET SHOP DROGARIA VILA GALVAO LTDA ME","petvetvilagalvao@gmail.com"),
			array("1351","PET SHOP GARRA MATRIZ LTDA ME","contato@petshopgarra.com.br"),
			array("1352","PET SHOP NICIMAR LTDA ME","marisol_mizuno@yahoo.com.br"),
			array("1354","PIXOXO PET SHOP LTDA","priscila.pixoxo@uol.com.br"),
			array("1358","R2 PET SHOP E SERVIÇOS VETERINARIOS LTDA","alvorada.guarulhos@uol.com.br"),
			array("1360","REGIANE GARCIA MARESCA ME","drikavet2002@hotmail.com"),
			array("1362","RICAO COMERCIO DE RAÇOES LTDA ME","acmctonico@ig.com.br"),
			array("1363","RL DE CARVALHO CONSULTORIO VETERINARIO L","recava@yahoo.com.br"),
			array("1364","ROBERTO ISAO MIYOSHI ME","veterinariacumbica@gmail.com"),
			array("1366","ROGERIO ARNO MIRANDA","r.a.miranda@estadao.com.br"),
			array("1367","ROSELI DA SILVA PEREIRA RODRIGUES ME","roselispr@hotmail.com"),
			array("1370","SILVA NEGRI COMERCIO DE RAÇOES LTDA ME","tonykao@superig.com.br"),
			array("1371","SIMPATICAO ARTIGOS PARA ANIMAIS  LTDA ME"),
			array("1373","TAVELLI & TEXEIRA COM.DE ART.P/ ANIM. DO","bichosecoisas@terra.com.br"),
			array("1375","VET LIFE COMERCIO PRODUTOS VETERINARIOS","vet-life@uol.com.br"),
			array("1376","VITA ANIMALLE PET SHOP CLINICA VETERINAR","animalle@yahoo.com"),
			array("1377","VIVAZ CLINICA VETERINARIA 24 HORAS LTDA","vivazvet@yahoo.com.br"),
			array("1378","XANDOGS  PET SHOP LTDA ME","xandogspetshop@hotmail.com"),
			array("1379","YANKEE  CONVENIENCIA ANIMAL LTDA ME","taniaferri@yahoo.com.br"),
			array("1536","BICHANUS PET SHOP LTDA ME","contabilidade@bichanus.com.br"),
			array("1601","MALUCAO PET SHOP COM LTDA ME","mpsmalucao@ig.com.br"),
			array("2092","CLINICA VETERINARIA DRA PRISCILA MAHLMEI"),
			array("2111","CLINICA VETERINARIA PAULISTANO LTDA EPP","paulistano24h@gmail.com"),
			array("2124","LARA FERNANDES PIRES"),
			array("2154","ARANY PET SHOP LTDA ME"),
			array("2166","PET SHOP RACOES RENATA LTDA ME"),
			array("2170","AGOSTINHO DE AGRELA AVICULTURA LTDA*","petqueroquero@hotmail.com"),
			array("2171","AVICULTURA CANTO LINDO LTDA ME*","cantolindopet@hotmail.com"),
			array("2176","JULIANNA COMERCIO DE RAÇÕES LTDA","bichofeliz@uol.com.br"),
			array("2184","ESTACAO ANIMAL PRODUTOS VETERINARIOS LTD"),
			array("2189","ELISABETE MENDES OLIVEIRA ME","machadopet2@ig.com.br"),
			array("2200","CAT & CAO PET SHOP E CONSULTORIO VETERIN"),
			array("2210","CEVET SFA CENTRO VET.LTDA ME","info@cevetsfa.com.br"),
			array("2213","PET FAMA LTDA"),
			array("2318","KENNEDY DA SILVA MARTINS ME"),
			array("2324","MARINA NAMIKO MORIKAWA SHINODA ME"),
			array("2325","RR 5 PATAS PET SHOP LTDA EPP"),
			array("2333","CASA DE RACOES BICHO FELIZ LTDA"),
			array("2347","BELA VIDA PET SHOP LTDA ME","reginavida2007@hotmail.com"),
			array("2398","SAO FRANCISCO SAUDE ANIMAL LTDA ME","iacy.fernandes@uol.com.br"),
			array("2441","G E G CLINICA VETERINARIA LTDA","graziellepileggi@gmail.com.br"),
			array("2462","PATRICIA HATSUMI AKAGI","patriciahakagi@ig.com.br"),
			array("2465","PET STORE GATO CAO LTDA ME","gato.cao2012@hotmail.com"),
			array("2476","CLARA DE ASSIS PET SHOP LTDA"),
			array("2522","CLINICA VETERINARIA VILA GALVAO LTDA"),
			array("2562","GUIDO BOY PET SHOP LTDA ME","boyboypetshop@yahoo.com.br"),
			array("2583","UNIPET CURSOS PROFISSIONALIZANTES LTDA M","ines@unipetsp.com.br"),
			array("2618","CYNTIA ROSENDO MARQUES ME"),
			array("2649","CAMILLA MENDES VISCIANO - ME","clintatapet@ig.com.br"),
			array("2660","PLANET PET CENTER COMERCIAL LTDA -EPP","nfeguarulhos@planetpetcenter.com.br"),
			array("2665","PEREIRA DE ROSSI - PET SHOP LTDA ME"),
			array("2678","MAROFAS PET SHOP LTDA -ME","marofas@ig.com.br"),
			array("2686","PET SHOP PONTE GRANDE ARTS P/ CAES E GAT","pontegrande1982@hotmail.com"),
			array("2698","PET SHOP BIG MANIA COMERCIO DE RAÇÃO LTD"),
			array("2704","ELCIO FREIRE","banhoecia08@hotmail.com"),
			array("2709","PET MY LIFE LTDA - ME","clauidiaregina22@yahoo.com.br"),
			array("2727","MAYARA MORO GARCIA","babylhotes@hotmail.com"),
			array("2730","MARINA MARTINS PRODUTOS VETERINARIO","andre@canilfaccioni.com.br"),
			array("2758","VIVIAN MAYUMMI OBI - ME"),
			array("2801","VERONICA DE OLIVEIRA VIANA ALMEIDA 33929"),
			array("2802","YAHZOO EQUIPAMENTOS  VETERINARIOS LTDA","ines@unipetsp.com.br"),
			array("2804","LEANDRO TELES CORREA - ME","brunapaulateles@hotmail.com"),
			array("2806","AVS ARLINDO VITOR DE SOUZA PET STORE LTD","vitor@petstorelilicao.com.br"),
			array("2811","MADALENA AZARIAS 02828220893","marizaceu@ibest.com.br"),
			array("2836","PET PARIS - PET SHOP E CLINICA VETERINAR"),
			array("2852","R & M COMERCIO VAREJISTA DE RAÇÕES LTDA-","petshopnossobicho@hotmail.com"),
			array("2866","PET SHOP QUERO BANHO LTDA-ME"),
			array("2875","VINICIUS MICHILIN - ME","vinimichilin@hotmail.com"),
			array("2893","PAULO CAVILHA PET SHOP - ME","maisa220@gmail.com"),
			array("2908","FERNANDA CRISTINA BERNABE PROSPERO-EPP"),
			array("2914","RR 5 PATAS PET SHOP LTDA - EPP"),
			array("2933","PET CLUB SIMONE OLIVEIRA LTDA - ME","simonejj@ig.com.br"),
			array("2943","CARLOS TAKASHI MIYAHARA-ME"),
			array("2948","RLA LIMAO PET SHOP-ME"),
			array("2955","PET PARA PETS COMERCIO E PARTICIPACOES E","xml@petparapets.com.br"),
			array("2959","RM DE MELLO SALVADOR RACOES -ME","amikaopetshop@gmail.com"),
			array("2963","ROSANGELA CRISTINA BRAGA 32286971854"),
			array("2965","TAMIRES PRACHEDES DA SILVA 36198596800","meumundopet@gmail.com"),
			array("2969","PLANET PET CENTER COMERCIAL  LTDA - EPP","nfearuja@planetpetcenter.com.br"),
			array("2980","BRUNA DE PAULA TELES - ME","brunapaulateles@hotmail.com"),
			array("2987","PRISCILA DE SOUZA FERREIRA 33923069839"),
			array("3004","CENTRO VETERINARIO YAYA LTDA - EPP","rafael.fnandrade@hotmail.com"),
			array("3007","MONDE PET'S PET SHOP LTDA. - ME","emoraisproducoes@gmail.com"),
			array("3011","MATEUS MAGALHAES SOUTO PETSHOP - ME"),
			array("3012","DOGS BABY PET STORE LTDA - ME"),
			array("3013","BILOCAO BANHO E TOSA LTDA - ME","rberaldio@yahoo.com.br"),
			array("3030","JOSE GILSON DA SILVEIRA ME","petshoppontealta@hotmail.com"),
			array("3036","ERIKA CRISTINA BARBOSA TARADA - ME","reiner.trinca@hotmail.com"),
			array("3041","PET SHOP CLIN.DE REAB. E HOT. DE ANIMAIS","thaisccavalcantevet@gmail.com"),
			array("3091","PET SHOP BONINI LTDA. ME","petshopbonini@hotmail.com"),
			array("3092","FABIO CELIDONIO POGLIANI - CLINICA VETER","ahc.vet@gmail.com"),
			array("3105","PET SHOP CASTRO LTDA - ME","renatozucon@hotmail.com"),
			array("3106","ELIANA ASSAE NAKAOKA HIRAMATSU PET SHOP","elianahiramatsu@msn.com"),
			array("3112","VIVAZ PET SHOP LTDA - ME","vivazvet@yahoo.com.br"),
			array("3117","C. VINICIUS O. DE ALMEIDA - ME","contato@alamodog.com.br")
		),
		'41' => array(
			array("1172","PET SHOP LEAL COMPANHEIRO LTDA","deabernardo@terra.com.br"),
			array("1199","DOG COMPANY COMERCIO DE ART. PARA ANIMAI","dogcompany@gmail.com"),
			array("1422","JOAO FRANCISCO GRANDINI JR PET SHOP ME","grandinivet@yahoo.com.br"),
			array("1430","MERCADO ANIMAL PET SHOP RACOES LTDA","marcio@mercadoanimal.com.br"),
			array("1471","POLICLINICA VET. E PET SHOP CERRO CORA L","jandreafe@terra.com.br"),
			array("1473","PRISCILA SODRE QUERINO FERREIRA","contato@petcidadejardim.com.br"),
			array("1527","ALOISIO CUNHA DE CARVALHO","acarvalhovet@hotmail.com"),
			array("1532","ARMAZEM DE BICHOS VET E PETCETERA COM RA","wallveterinaria@ig.com.br"),
			array("1538","MAGIC ANIMAL LTDA","diany.martins@gmail.com"),
			array("1544","CITY ZOO PET SHOP COMERCIO LTDA ME","gilbertospessoto@hotmail.com"),
			array("1556","CINTIA CRISTINA SOUZA SILVA","petlocao@hotmail.com"),
			array("1558","DANIEL PADRAO BARBOSA ME","fernandaballes@hotmail.com"),
			array("1560","DANIELA MOL VALLE"),
			array("1562","DK COMERCIO E SERVICOS PARA ANIMAIS LTDA"),
			array("1563","DOCTOR PET CLINICA VETERINARIA LTDA ME","jfvet@hotmail.com"),
			array("1579","EDUARDO TADEU RODRIGUES ME","petshopcardeal@bol.com.br"),
			array("1581","FABIANA DE BRITO CARNEVALE GAEDKE ME"),
			array("1583","FABIANA ZAMPOLLO DE OLIVEIRA CAMPOS","fa.zampollo@bol.com.br"),
			array("1585","FE & FE COMERCIO DE RACOES LTDA EPP","notasnf@contabilidadelm.com.br"),
			array("1586","FRADIKAO PET SHOP LTDA ME","marinadelmotte@hotmail.com"),
			array("1592","M & N PET SHOP COM RACOES LTDA"),
			array("1599","CLINICA VETERINARIA DRA MAGALI ANSELMO","gsantos@ecmcontabil.com.br"),
			array("1602","MANIA DE BICHINHOS LTDA","eduardobotter2011@hotmail.com"),
			array("1604","MANO´S COMERCIO & PET SHOP LTDA","ddfi@hotmail.com"),
			array("1612","MARIELA PET SHOP LTDA ME"),
			array("1615","NIMMAISPET - PET SHOP COMERCIO E SERVICO","rescana @hotmail.com"),
			array("1622","PET & CARE COM SERV P/ ANIM LTDA ME","pet.care@uol.com.br"),
			array("1624","PET SHOP BOM DE BICHO LTDA","contato@petbomdebicho.com.br"),
			array("1625","PET SHOP HIGIENOPOLIS LTDA ME"),
			array("1626","PET SHOP MASTER PROD P/ ANIM LTDA ME"),
			array("1627","PET SHOP MORATO COELHO LTDA EPP","rchalpern@yahoo.com.br"),
			array("1636","SAO LAZARO COM PET SHOP P/ CAES GATOS LT"),
			array("1638","STAR DOGS CONFEC E COM LTDA ME","star.dogs@hotmail.com"),
			array("1639","TOBY PET SHOP & ACESS LTDA ME"),
			array("1644","VET E SHOP LTDA ME"),
			array("1767","ANIMAL´S WORLD COMERCIAL LTDA *","animalsworld@hotmail.com"),
			array("1807","V.S.F. COMERCIO E SERVIÇOS LTDA ME"),
			array("1838","ALIR DE BIAGGI FILHO*","alir@acdg.com.br"),
			array("1839","AMANDA MEDEIROS GIROTO ME*","amanda@caodilheiras.com.br"),
			array("1840","AMARILIS POGGETTI ME*","lucineia.vitalino@yahoo.com.br"),
			array("1842","ANDREA REGINA CARDOSO DE ALMEIDA MOREIRA","bichoerabicho@terra.com.br"),
			array("1843","ANDREIA FONSECA DO NASCIMENTO ME*","a.nascimento@ig.com.br"),
			array("1850","BABA CAO COM. DE ARTIGOS VETERINARIOS LT","rosano@veterinariorosano.com.br"),
			array("1851","BAD DOG COM. PROD. VET. E SERV. LTDA ME*","baddogpetshop@uol.com.br"),
			array("1852","BERNARDO JOSE DICEZARE PET SHOP -ME","vetdicezare@hotmail.com"),
			array("1853","BICHARADA ARTIGOS PARA ANIMAIS LTDA*","bicharada@bicharada.com.br"),
			array("1854","BRANDS COM. E PROD. P/ ANIMAIS LTDA ME*","fabiana.neres@ig.com.br"),
			array("1862","CASA DE RAÇÕES AGUA BRANCA LTDA*","lie.uehara@uol.com.br"),
			array("1864","CHIC DOG ALIMENTOS ACESSORIOS P/ CAES GA","valdeci@terra.com.br"),
			array("1876","CLINICA VET PACAEMBU LTDA*","contato @ centroveterinariopacaembu.com.br"),
			array("1878","CLINICA VETERINARIA  POMPEIA PET SHOP LT","adminstracao@hovetpompeia.com.br"),
			array("1883","DOMINGOS ANTONIO MUCCIACITO JUNIOR ME*","fauna.perdizes@gmail.com"),
			array("1885","EMPORIO DO ANIMAL LTDA ME*","mkt@emporiodoanimal.com.br"),
			array("1886","GERALDO MONTANHEIRO*","geraldomonta@uol.com.br"),
			array("1887","GILBERTO CELIDONIO DE MELLO REIS NETO -","procao@procao.com.br"),
			array("1890","JEFFERSON TADEU RIBEIRO GAROTTI ME*","contato@clinicanis.com.br"),
			array("1912","JK FISH PET SHOP LTDA*","klebercomenale@gmail.com"),
			array("1915","MAJOO ARIEL PET SHOP E ACESS. LTDA ME*","hardiiy@ig.com.br"),
			array("1916","MEGA PET SHOP E COMERCIO LTDA ME*","petstop2@gmail.com"),
			array("1918","MERCEARIA DO ANIMAL COM RACOES LTDA ME*","carlos@merceariadoanimal.com.br"),
			array("1920","MIYATA PET SHOP COMERCIO E SERVIÇOS LTDA","mirian@bobson.com.br"),
			array("1921","MULTIMAIS COMERCIO LTDA*","multimais@hotmail.com"),
			array("1923","OH MY DOG COM. E SERV. LTDA ME*","ohmydog@terra.com.br"),
			array("1924","PATAS URBANAS COMERCIO DE RAÇOES P/ ANIM","leticiaduwal@gmail.com"),
			array("1925","PERALTAS PET SHOP LTDA ME*"),
			array("1930","PET SHOP AMIGO LTDA ME*","veterinariapetamigo@gmail.com"),
			array("1931","PET SHOP BELLE COMERCIAL LTDA ME*","danielagusmao@ig.com.br"),
			array("1932","PET SHOP BIG HOUSE COMERCIO E SERV. LTDA","petbighouse@uol.com.br"),
			array("1935","PET SHOP SANTOS COM.DE RAÇOES P/ CAES E","flavio.petshopsantos@gmail.com"),
			array("1936","PETIT AMI COMERCIO E PET SHOP LTDA ME*","petitami.vet@gmail.com"),
			array("1939","POMPEIA PET COM.DE PROD. E SERV.P/ ANIMA","ritakarina@yahoo.com.br"),
			array("1941","PRO VIDA ANIMAL CLIN VET E PET SHOP LTDA","rodrigo@provida.com.br"),
			array("1945","ROSA ALICE RODRIGUES TERUEL ME*","clinicaveterinariapontapora@ajato.com.br"),
			array("1946","ROSE´S PET SHOP COM ART P/ ANIM LTDA*","wilma@advisercontabil.com.br"),
			array("1949","SEPETIBA PET SHOP COM SER BANHO TOSA LTD","kharenperine@yahoo.com.br"),
			array("1951","TRUSTY PET CLIN VET EST COM RACAO LTDA*","trustypet@yahoo.com.br"),
			array("1952","UNIAO INTERNACIONAL PROTETORA DOS ANIMAI"),
			array("1953","VALERIA WENSKO ME*","valwensko@gmail.com"),
			array("1956","VITALI SAUDE ANIMAL E AMBIENTAL LTDA*","nfe01@vitaliambiental.com.br"),
			array("1957","VITTA VET PETS COMERCIO DE ART P/ ANIM L","vittavet@globo.com"),
			array("1958","VT COLOSSO COM PROD VET E RAC LTDA ME*","vetrafa@yahoo.com.br"),
			array("1959","WALTER AMBROZIO ME*","walterambroz@hotmail.com"),
			array("2094","ENCRENQUINHAS PET SHOP LTDA ME *"),
			array("2104","BICHO E TAL CLINICA VETERINARIA PET SHOP","andre_anlee@yahoo.com.br"),
			array("2122","LAURA MIADAIRA","lauramiadaira@hotmail.com"),
			array("2131","FABIO ELIAS RANDI"),
			array("2137","NOGUEIRA & SANCHES RACOES LTDA ME*","edu-nogueira11@hotmail.com"),
			array("2198","CLINICA VETERINARIA JD ESTHER ME"),
			array("2208","AGROTOTAL COMERCIAL LTDA *","agrosp@terra.com.br"),
			array("2237","A.V.RAMOS PET SHOP ME"),
			array("2249","DOG CARE PET SHOP LTDA ME","petdogcare@hotmail.com"),
			array("2266","XAU XAU PETS COM.DE ARTIGOS P/ANIMAIS ME","janainakfranca@ig.com.br"),
			array("2288","PET SHOP RAFAN COM. DE ARTIGOS PARA ANIM","rafaaugusto_moraes@hotmail.com"),
			array("2293","SPAZZIO PET LTDA ME*","dra.renata@spazziopet.com.br"),
			array("2296","PITOCO PET SHOP LTDA ME"),
			array("2339","A.R DA SILVA PET SHOP ME*","animapet@animapet.com.br"),
			array("2409","MOIRA COMÉRCIO E PRESTAÇÃO DE SERV. LTDA","kerayr@kob.com.br"),
			array("2415","BANHO E TOSA MONTE ALEGRE LTDA ME*","caodella@uol.com.br"),
			array("2416","ROBERTO DE LA MADRID GOMES ME*"),
			array("2417","MINORCAO PET SHOP LTDA-ME"),
			array("2429","FABIANNA MASCAVO VALENTE-ME","caocunvet@hotmail.com"),
			array("2433","ORTEGA UNI PET SHOP LTDA-ME"),
			array("2472","ARMAZEM CONFIANCA COM. DE GENEROS ALIM.","armazemconfinacacadastro@uol.com.br"),
			array("2478","RENATA GASPAR VIEIRA","contato@africapet.com.br"),
			array("2494","DANIELA SANTOS CICHIELO"),
			array("2498","COMERCIAL PET SHOP JORGE FERREIRA"),
			array("2526","EDSON FERREIRA DA SILVA ALOJAMENTO DE AN","angeli_ribeiro@globo.com"),
			array("2534","PET CARE PACAEMBU LTDA","mauricio.nicoletto@petcare.com.br"),
			array("2561","MULTIMAIS COMERCIAL LTDA ME #"),
			array("2615","GRAZIELA GARIMA GRANDINI RIZZATO PET SHO","grazielagrandini@hotmail.com"),
			array("2630","VIRA A LATA HOTEL, CRECHE E CUIDADOS PAR","contato@viraalata.com.br"),
			array("2637","PAO KAYWU FERRAZ DE OLIVEIRA","veterinariapetamigo@gmail.com"),
			array("2643","PET SHOP SE PRODUTOS VETERINARIOS LTDA M"),
			array("2645","CSA PRODUTOS SERVIÇOS VETERINARIOS"),
			array("2646","RENATO ZONZINE BOCABELLO - ME","natoclinica@hotmail.com"),
			array("2651","BOAS MARCAS COMERCIO EXP. LTDA ME","dafonsecaja@bol.com.br"),
			array("2655","BICHOTOTAL PET SHOP COMERCIO DE RAÇÃO E"),
			array("2711","VILLA E VILLA COMERCIO LTDA - ME","tadeuvilla@bol.com.br"),
			array("2728","PET SHOP PAULA & FRED LTDA - ME","maniadebicho012@gmail.com"),
			array("2729","MISTER GATITO PET SHOP LTDA -ME","levimrpet@hotmail.com"),
			array("2752","PROBICHO CENTRO VET E COM DE ART P/ ANIM","probicho@probicho.com.br"),
			array("2759","CINTIA RAHAL CUNHA ME","cintiarahal@yahoo.com.br"),
			array("2773","A & R PETS COM DE ART P/ ANIAMIS LTDA -","arthur.alonso@cvbvet.com.br"),
			array("2817","CONSULTORIO VETERINARIO EDGARD MORALES B","embrito@terra.com.br"),
			array("2822","ELEUTERIO PET SHOP LTDA - ME"),
			array("2869","AQUARELA CARE PET SHOP LTDA","isabel_moura84@yahoo.com.br"),
			array("2880","VIVIANE MATIAZZO PINTO","vivianematiazzo.vet@gmail.com"),
			array("2895","CAROLINA GAMA DE OLIVEIRA","olharvet@hotmail.com"),
			array("2907","PET CENTRO ANIMAL LTDA - ME"),
			array("2924","UNIVERSAL DOG SERV.ESPECIALIZADOS P/MASC","eesteticao@yahoo.com.br"),
			array("2957","FISIOANIMAL PET SHOP LTDA","maira@fisioanimal.com"),
			array("2967","CENTRO MANUEL LOPES EIRELI","centro.veterinario713@gmail.com"),
			array("2988","PET HELP COMERCIO DE PRODUTOS PARA ANIMA","danielamungioli@gmail.com"),
			array("2995","CANALT PET SHOP SERV.DE.EMBLZ.ALOJ.DE.AN","natalia_peres@hotmail.com"),
			array("2997","SBW BRAS PET SHOP - EIRELI","contato@heccalifornia.com.br"),
			array("3001","PET SUPREMO LTDA - ME","contato@petsupremo.com.br"),
			array("3009","PET DOS PRINCIPES COMERCIO DE PRODUTOS P"),
			array("3033","LAPET PET SHOP - EIRELI - ME","lapet.petshop@gmail.com"),
			array("3034","ANGEL LUCK PET SHOP LTDA - ME","angelluck@gmail.com"),
			array("3051","V.S.F. - COMERCIO & SERVICOS LTDA - ME","banhotosa.vetvilasaofrancisco@gmail.com"),
			array("3056","CENTRO VETERINARIO DA VILA LTDA - ME","petavet@petavet.com.br"),
			array("3110","PELUDAO COMERCIO DE ARTIGOS DE PET SHOP","nunescontab@nunescontab.com.br")
		),
		'44' => array(
			array("1011","ALEXANDRE AUGUSTO TATSUOKA PROSPERO ME"),
			array("1012","ALLAN TADEU JULIANI","allantjuliani@ig.com.br"),
			array("1018","ANDREA APARECIDA NARDI ME"),
			array("1021","ANIMAL MUNDI PET SHOP E CLINICA VETERINA"),
			array("1026","AVICULTURA DINOSSAURO LTDA ME"),
			array("1029","AVICULTURA VAMP LTDA","sergioferro50@yahoo.com.br"),
			array("1047","CASA DOS ANIMAIS COMERCIAL LTDA ME","casa-dos-animais@hotmail.com"),
			array("1054","CLIN VET DR CASSIO SCARABOTTOLO LTDA","cscarabotolovet@uol.com.br"),
			array("1064","COMERCIO VAREJISTA DE PROD VET PET MAXI","petmaxiengenheiro@gmail.com"),
			array("1065","CONSULADO DA RACAO LTDA EPP","santaines@consuladodaracao.com.br"),
			array("1067","CONSULADO DOS BICHOS PET SHOP LTDA EPP","cantareira@consuladodaracao.com.br"),
			array("1070","DORACI GARROPHO PINCELLI ME"),
			array("1080","ELIANE BEATRIZ DOS SANTOS","clinicaveterinariabichuchu@yahoo.com.br"),
			array("1115","FOCCUS COMERCIO DE ARTIGOS P/ ANIMAIS LT","adm2@hvetfoccus.com.br"),
			array("1116","FOCINHOS E RABINHOS COM P/ ANIM LTDA","rosa.simoes@uol.com.br"),
			array("1144","GRUPO BRASIL CDJ PET SHOP LTDA ME","petshopmalucao@yahoo.com.br"),
			array("1145","GUERJIKAO PET SHOP LTDA ME","marcia.guerjik@hotmail.com"),
			array("1148","GUIDO & FREITAS PET SHOP LTDA ME","guidoefreitas@gmail.com"),
			array("1156","HOSPITAL VETERINARIO SANTA INES LTDA","pacheco@santainesvet.com.br"),
			array("1167","KI DOG PET SHOP LTDA","andre@breeds.com.br"),
			array("1173","L A SHIMAOKA ME","l.ashimaoka@terra.com.br"),
			array("1175","LEONIRDES PASCHOEL PUGIN RAÇOES ME","novacampeao@hotmail.com"),
			array("1178","MARCIO DE OLIVEIRA ANDRADE ME"),
			array("1182","MARIA TERESA BERNARDO ME"),
			array("1187","MORDE CAO COMERCIO E VETERINARIA LTDA"),
			array("1191","P D COMERCIO DE RACOES LTDA","planetadog@uol.com.br"),
			array("1192","PARADA DOG COMERCIO DE ARTIGOS P/ ANIM L","marcel.mello@ig.com.br"),
			array("1256","PATAKI PATAKOLA PET SHOP LTDA ME"),
			array("1259","PET MAXI COMERCIO DE ARTIGOS PARA ANIMAI","petmaxiinajar1@gmail.com"),
			array("1262","PET POINT COM PROD VET LTDA ME"),
			array("1263","PET SHOP BARBOSA E GALEGO LTDA ME"),
			array("1266","PET SHOP CHIC ESTETICA ANIMAL E VET LTDA"),
			array("1273","PET SHOP MORDE CAO COML LTDA ME"),
			array("1274","SOLANGE MINIERO - ME","o.dfernandes@hotmail.com"),
			array("1277","PET SPA COMERCIO PRESTACAO DE SERVICOS L","petspa@yahoo.com.br"),
			array("1280","PONEY AVICULTURA LTDA ME"),
			array("1296","ROBERTO LUIZ SCORVO"),
			array("1298","RODRIGO SPADA RIBEIRO ME"),
			array("1303","ROSALIA FERREIRA"),
			array("1309","S.CAMARGO URBANO PET SHOP EPP","globalpet@globalpet.com.br"),
			array("1313","DOG BOY PET SHOP LTDA ME","contato@planetadog.com"),
			array("1390","TERESA LEMBO TEXEIRA","lemboteresa@hotmail.com"),
			array("1393","VALENTE & VALENTE COM ART P/ ANIM LTDA","contato@clinicadecaesegatos.com.br"),
			array("1407","CONSULADO PET LTDA EPP","consuladopet@hotmail.com"),
			array("1726","SANDRA HELENA D IMPERIO BUENO","faustobueno@hotmail.com"),
			array("1808","AMORE DI CANE PET SHOP LTDA ME*"),
			array("1809","ANDRE LUIZ BUSSAMARA DE FREITAS*"),
			array("1813","BEM LOCAO COM RACOES LTDA*","bemlocaoengenheiro@outlook.com"),
			array("1814","BICHO CRIADO PET SHOP LTDA*","bichocriado@yahoo.com.br"),
			array("1816","CAO Q LATE COM RACOES LTDA*","financeiro@caoqlate.com.br"),
			array("1817","CETA CENTRO ESPEC. TRAT. ANIM. LTDA*","irtavares@uol.com.br"),
			array("1818","CLINICA VETERINARIA PALMEIRAS LTDA*"),
			array("1819","CLINICA VETERINARIA CONDE LTDA ME*","melhor.amigo@terra.com.br"),
			array("1822","CLINICA VET SOS PELUDOS LTDA ME*","finan.sospeludos@hotmail.com"),
			array("1823","CLYJAN COM DE ART P/ ANIM DOM LTDA ME*","marcio.polatto@terra.com.br"),
			array("1824","COMERCIO DE RACOES ANIMACAO PET SHOP LTD","contato@animacaopetshop.com.br"),
			array("1828","GABRIELLI COMERCIO DE RACOES LTDA - ME","caomaradas@ig.com.br"),
			array("1829","EDSON DE OLIVEIRA AZA ME*","praticao@ig.com.br"),
			array("1830","EDUARDO MANEZE GABRIELLI RACOES ME*","caomarada@ig.com.br"),
			array("1831","EKT COM DE ANIM PROD VET LTDA EPP*","atendimento@petstoresantana.com.br"),
			array("1832","ELIELSON MARTINS ESTEVES AVICULTURA ME*"),
			array("1833","ESPACO NATURAL SHOP COM LTDA ME*"),
			array("1834","ESTILO CAO PET SHOP LTDA ME*","estilocao@hotmail.com"),
			array("1848","GATTO PET SHOP LTDA ME*","gattopet@hotmail.com"),
			array("1855","HM MERCADOCAO PET SHOP LTDA ME*","rodrigoakiss@hotmail.com"),
			array("1856","HOSPITAL DE CLINICAS VETERINARIAS LTDA*","ricardo.sanches1@gmail.com"),
			array("1867","LEONARDO PEREIRA LIMA VETERINARIA*","companhia-animal@uol.com.br"),
			array("1868","LUIZ FERNANDO LONGUINI & CIA LTDA ME*","claudialonguini@ig.com.br"),
			array("1869","MARCOS ROBERTO DE CASTRO FORNAZARI VETER","vetfor@terra.com.br"),
			array("1870","MARVIC´S EMPREENDIMENTOS E PARTICIPAÇAO","jcaciani@uniquegarden.com.br"),
			array("1871","MENU DOG´S ALIM ACESS P/ CAES GATOS ME*"),
			array("1872","MILDRED GENOVE WIDMER POGGETTI ME*","falecomdoguegatao@uol.com.br"),
			array("1874","MTANOS PET SHOP LTDA ME*","edileudarodrigues@yahoo.com.br"),
			array("1891","PATA PELUDA PET SHOP LTDA ME*"),
			array("1893","PET NARQUI COM VAREJ ART P/ ANIM LTDA ME","archis@globo.com"),
			array("1894","PET SHOP IVREA PRODUTOS VETERINARIOS LTD","annagannam@yahoo.com.br"),
			array("1895","PET SHOP L & E LTDA ME*","giovanamedina@hotmail.com"),
			array("1898","PLANETA DOG RACOES LTDA ME*","planetadog@uol.com.br"),
			array("1899","PRO PETS PET SHOP LTDA ME*","pro_pets@hotmail.com"),
			array("1900","PRONT VET COM DE ART P/ ANIM EST LTDA*","prontvet@globo.com"),
			array("1902","RMB PRODS P/ ANIMAIS LTDA ME*","raquelbeirao@terra.com.br"),
			array("1903","S SOARES JUNIOR PET SHOP ME*","hbn.hbn@hotmail.com"),
			array("1904","SAN PUPS AGRO COMERCIAL LTDA*"),
			array("1905","SEBASTIAO ABEL DOS SANTOS*","bene.b.santos@gmail.com"),
			array("1907","SOA KAO COMERCIO DE RACOES LTDA ME*","edgard@escritoriosantana.com.br"),
			array("1908","VEMKA PET SHOP LTDA ME*","herzi@uol.com.br"),
			array("1909","VET PALMAS PET SHOP LTDA*","contato@vetpalmas.com.br"),
			array("1910","VIRA LATA COM RACOES LTDA ME*","viralata.racoes@yahoo.com.br"),
			array("1911","VITORIA APARECIDA MARQUES DINIZ*"),
			array("1980","ANJOS STAR PET SHOP E CONSULTORIO VETERI","anjosstar@anjosstar.com.br"),
			array("2016","ANIMAL PARK COM. DE ARTIGOS P/ ANIMAIS L"),
			array("2081","SONIA MARIA CORTESI ME"),
			array("2108","CYNTHIA APRAHAMIAN","cynthiavet02@gmail.com"),
			array("2161","JOAO JOSE D AQUINO - RACOES","bemlocaojoao@ig.com.br"),
			array("2172","PATINHAS & CIA PET SHOP LTDA ME*","marcia@patinhasecia.com.br"),
			array("2218","ASSOCIACAO PROTETORA ANIMAIS SAO FRANCIS"),
			array("2238","KAREN GUEDES MENEZES DONHA PET SHOP ME","maniakao@yahoo.com.br"),
			array("2286","PET EM FOCO COM. DE PRODUTOS PARA ANIMAI"),
			array("2291","PAPA CAPIM AVICULTURA COM.LTDA"),
			array("2345","LUIZ FILIPI PALUMBO TELES"),
			array("2431","LETICIA DE LIMA COM. DE PROD. ANIMAIS ME","petpaineiras@hotmail.com"),
			array("2452","ACACIO FERREIRA DE TOLEDO"),
			array("2499","PET ZOOM IMPORTACAO E COMERCIO DE PRODUT"),
			array("2524","PET SHOP BICHOS & BICHOS LTDA ME","contato@caomaravilha.com.br"),
			array("2535","CONSELHEIRO PET SHOP COM DE RACOES LTDA","bemlocaopet@ig.com.br"),
			array("2549","FRE-MBI COMERCIO DE PRODUTOS VETERINARIO"),
			array("2559","PORTUCAO COMERCIO E PET SHOP EIRELI - ME","portucao@gmail.com"),
			array("2579","BENEDITO LUA BOMFIM CLINICA VET HORTO-ME","clinicaveterinariahorto@hotmail.com"),
			array("2633","CONSULADO DA RACAO LTDA- ME ***","dumont@consuladodaracao.com.br"),
			array("2654","FERNANDA JUSTI RAMALHO","fe_justi@hotmail.com"),
			array("2685","LEON DENS DE MEDEIROS PET SHOP ME"),
			array("2696","ESTETICA ANIMAL INES LTDA ME","larissa.carrasco@santainesvet.com.br"),
			array("2772","LIASI AVICULTURA LTDA - ME","andreacalori20102010@hotmail.com"),
			array("2808","PLANETA DOG RACOES LTDA","planetadog@uol.com.br"),
			array("2826","CONSULADO DA RACAO EIRELI - ME","benjamim@consuladodaracao.com.br"),
			array("2849","COMERCIO VAREJISTA DE PROD VET PETMAXI E","petmaxijacana@gmail.com"),
			array("2861","PATRICIA PEREIRA 12838690809","oanastacio@uol.com.br"),
			array("2865","AVICULTURA  E PET SHOP UAU UAU LTDA - ME","luciene.cfv@globo.com"),
			array("2868","JOAO JOSE D AQUINO JUNIOR - PET SHOP","bemlocaovilamaria@ig.com.br"),
			array("2871","PET CHARLOTE EIRELI - ME","jtdalmeida@gmail.com"),
			array("2883","ERIKA HELENA DE ARAUJO TEIXEIRA 22873733","erikahelenaa@hotmail.com"),
			array("2902","AVICULTURA E PET SHOP LANA LTDA - ME","adrigosi05@hotmail.com"),
			array("2911","PELUDINHOS PET SHOP & BANHO E TOSA LTDA","claudiogordo.detan@gmail.com"),
			array("2916","GUTEMBERG BARRETO NOVAES - ME"),
			array("2930","VIRGINIA MARIA SILVA 12569646890","virginiamsilva@superig.com.br"),
			array("2931","VAGNER WILLIAN DA COSTA","vagnerwillian_@hotmail.com"),
			array("2932","HUMBERTO LEONCIO PELOSO","humberto.vet@terra.com.br"),
			array("2935","PATVET PET SHOP LTDA-ME","patvetclinica@gmail.com"),
			array("2945","ELIZABETE REGINA DE ABREU","tocadosbichospetshop@hotmail.com"),
			array("2961","GIULIANO AUGUSTO PIRES","giulianopires30@hotmail.com"),
			array("2972","VINICIUS ABE FERRARDO - ME","clinvetmazzei@ig.com.br"),
			array("2984","SHOPPING DOS BICHOS EIRELLI-ME","jupmiranda@hotmail.com"),
			array("2992","PET SHOP SAUSALITO EIRELI-ME"),
			array("2996","NP PET SHOP COM. E SERV. LTDA - ME","fabiano@petshopnovopet.com.br"),
			array("2999","PERI CAO ESTETICA ANIMAL E BOUTIQUE LTDA","pericao@clinicapericao.com.br"),
			array("3014","FERNANDA JUSTI RAMALHO  31663048860","fe_justi@hotmail.com"),
			array("3024","ESTACAO PET SHOP TREMEMBE LTDA","petshoptremembe@hotmail.com"),
			array("3043","GUILHERME ISIDORO SOARES DA ROSA - ME","guilherme.ifi@hotmail.com"),
			array("3044","VERONA & SGUARIO RACOES E ARTIGOS PARA A","adriana@obichocomestilo.com.br"),
			array("3046","NORI PET SHOP LTDA - ME","noripetshop@gmail.com"),
			array("3055","BENEDITO LUA BOMFIM","clinicaveterinariahorto@hotmail.com"),
			array("3087","LEOPOLDINO DE MORAES PEDROSO NETO - ME","racoesmairipora@hotmail.com"),
			array("3097","MONTE CELESTE ARTIGOS DE PET SHOP LTDA -","petshopmonteceleste@yahoo.com.br"),
			array("3101","VITOR DE ABREU ALVES - EPP","tocadosbichospetshop@hotmail.com"),
			array("3116","ALINE CRISTINA DA SILVA SANTANA 37155974","erikahelenaa@hotmail.com"),
			array("3118","LUCINEIA MARIA BATISTA 27046750823"),
			array("3120","RENATO FERNANDO DE SOUZA RACOES - ME","planetadog@uol.com.br")
		),
		'45' => array(
			array("1037","BICHO DA CASA PET SHOP LTDA ME"),
			array("1050","CLAUDIO ALBANO CONTRERAS"),
			array("1061","COM. ROAM LTDA ME"),
			array("1071","CAO CHANEL PET SHOP ME"),
			array("1078","ELEGANCE FLORES PET SHOP COM LTDA"),
			array("1086","ESTILO CAO PET SHOP LTA ME","estilocao@hotmail.com"),
			array("1092","FLOR. E AVICULTURA TIZIU LTDA ME"),
			array("1094","COMERCIAL AGRO LENA LTDA","agrolena@hotmail.com"),
			array("1102","DOUGLAS FELIX  MARTINS ME","douglasfelismartins@hotmail.com"),
			array("1103","EDSON HITOSHI TANE"),
			array("1108","FABIO HENRIQUE BIAGGI"),
			array("1121","HELENA VOLOCHINI MEKHAIAN ME"),
			array("1123","HENRIQUE DE OLIVEIRA GONÇALVES ME"),
			array("1141","GORNY´S PET SHOP LTDA ME"),
			array("1181","MARIA LUZIA CAVASSINI ME"),
			array("1219","PET SHOP PITUKA LTDA ME","andrea_veter@ig.com.br"),
			array("1225","RICARDO AUGUSTO CARRATO"),
			array("1400","VITORIA PINTAUDI"),
			array("1409","ALESSANDRA DURAN FRARATIO"),
			array("1491","ANIMAL DE ESTIMACAO PET SHOP VET LTDA ME","sarasimone@uol.com.br"),
			array("1503","CELSO COELHO DE MIRANDA ME","ccoelhomiranda@bol.com.br"),
			array("1521","CICERO PEDRO DE OLIVEIRA"),
			array("1533","AVICULTURA A G J LTDA ME"),
			array("1535","BACANA PET SHOP LTDA ME"),
			array("1543","CENTRO DE ESTETICA E SAUDE ANI SAO PAULO","cesasp@terra.com.br"),
			array("1567","DOIS AMIGOS PET SHOP E SERVICOS LTDA ME"),
			array("1645","CLAUMIDA FERES DE MIRANDA"),
			array("1655","DIVA MARIA FONSECA DE FARIAS ME"),
			array("1658","EDUARDO E EDGAR COM. DE RACOES LTDA-ME","pet_stopdog@yahoo.com.br"),
			array("1670","FERNANDA DE ALMEIDA TANAJURA SCABIN"),
			array("1682","JENIFER THAIS ROCHA DA SILVA"),
			array("1683","JOAQUIM JORGE DA COSTA"),
			array("1689","M MONICA GOMES PET SHOP LTDA"),
			array("1707","PET SHOP TEKA PRODUTOS PARA ANIMAIS LTDA"),
			array("1730","SOLIS ARTIGOS PARA ANIMAIS E PESCA LTDA","chicosolis69@yahoo.com.br"),
			array("1784","SALSON BONFATI AVICULTURA ME"),
			array("1858","C.V. VETERINARIO JD. BONFIGLIOLI S/C LTD","vetjdonfa@ig.com.br"),
			array("1929","PET GARDEN CENTER COM LTDA*","simone@qualipet.com.br"),
			array("1954","VET SHOP PROD VETERINARIOS LTDA ME*","vetshop@bol.com.br"),
			array("1987","CAMILA PEREIRA DE OLIVEIRA VETERINARIA","camilap.o@ig.com.br"),
			array("2002","CLAUDIO AKIRA SAKAGUTI"),
			array("2005","DARCI GOMES LUIS"),
			array("2018","AVICULTURA SILMAR LTDA"),
			array("2027","DULCE AKEMI KUWABARA","petfortvet@ig.com.br"),
			array("2028","EDNA MARIA DE ARAUJO"),
			array("2127","TOP SERVICE COMERCIO DE PRODUTOS E SERVI","vendas@doctorsvetonline.com.br"),
			array("2174","PROJETO BICHO COM. DE RAÇOES E ART. P/ A","aljperera@yahoo.com.br"),
			array("2335","ROBERTO DE LA MADRID GOMES ME"),
			array("2434","AGC PET SHOP LTDA-ME"),
			array("2451","MARCELO FAGUNDES VALERIOTE - ME"),
			array("2457","KEILA JIMENEZ TORRICO"),
			array("2538","TATIANE RODRIGUES MACHADO"),
			array("2545","FLAVIO DE SOUZA BARBOSA","docflavio@terra.com.br"),
			array("2700","BIANCA FABRETI MENDES LLAMAZALEZ"),
			array("2751","PET SHOP DGM - ME","daniellegaldeano@bol.com.br"),
			array("2774","BANHO E TOSA DOG MEL LTDA - M.E.","contato@petshopdogmel.com.br"),
			array("2796","EDUARDO DE OLIVEIRA DA COSTA 31588082857","pet-shop2011@bol.com.br"),
			array("2971","CARLOS ROBERTO MORAES PEREIRA LIMA FILHO","fabinho.dearaujo@gmail.com.br"),
			array("2974","MARIA INEZ DE SOUZA KODAMA PET SHOP - ME","kodama.inz449@gmail.com"),
			array("2978","WESLLEY DELA COLETA NETO 43179400862","petshopclean@hotmail.com"),
			array("2985","AVICULTURA SANTA IZABEL LTDA - ME"),
			array("3003","ELAINE REGINA CARDOSO DA SILVA 263713708"),
			array("3040","CANIL ESPACO CANTINHO FELIZ","julianavsilveira@hotmail.com")
		)
	)
);



$clientesNaoEncontrados = array();
$clientesAtualizadosDepois = array();
$customersToSave = '';

foreach ($array as $salesrep)
{
	foreach ($salesrep as $rep => $customers)
	{
		$rep = Mage::getModel('fvets_salesrep/salesrep
		')->load($rep, 'id_erp');
		foreach ($customers as $customer)
		{
			echo '-';
			$model = Mage::getModel('customer/customer')
				->getCollection()
				->addAttributeToSelect('fvets_salesrep')
				->addAttributeToSelect('id_erp')
				->addAttributeToFilter('id_erp', $customer[0])
				->addAttributeToFilter('website_id', '5')
				->getFirstItem()
				;
			if ($model->getId()) {
				//echo $rep->getId() . ' | ' . $model->getFvetsSalesrep() . ' - ' . $customer[2] . ' | ' . $model->getEmail() . ' - ' . $model->getUpdatedAt() . ' - ' . $model->getCreatedAt() . "\n";

				//Se já existir esse uruário para ser atualizado, utiliza ele mesmo
				if (isset($customersToSave[$model->getId()]))
				{
					$model = $customersToSave[$model->getId()];
				}

				$data = explode(' ', $model->getUpdatedAt());

				if (strtotime($data[0] . ' 00:00:00') > strtotime('2015-04-01 00:00:00'))
				{
					$clientesAtualizadosDepois[] = array_merge($customer, $model->getData());
				}
				else
				{
					if (isset($customer[2]) && filter_var(trim($customer[2]), FILTER_VALIDATE_EMAIL) && trim($model->getEmail()) != trim($customer[2]))
					{
						$model->setEmail(trim($customer[2]));
					}
				}

				if (isset($customersToSave[$model->getId()]))
				{
					$model->setFvetsSalesrep($model->getFvetsSalesrep() . ',' . $rep->getId());
				}
				else
				{
					$model->setFvetsSalesrep($rep->getId());
				}

				$customersToSave[$model->getId()] = $model;

			}
			else
			{
				$clientesNaoEncontrados[] = $customer;
			}
		}
	}
}

echo "\n";

$errors = array();

$string  = "\n" . 'Clientes atualizados: ' . "\n\n\n";

foreach ($customersToSave as $customer)
{
	echo '+';
	try
	{
		$customer->save();
		$string .= implode(',', $customer->getData()) . "\n";
	}
	catch (Exception $e){
		$errors[] = (string)$e->getMessage() . ',' . implode(',', $customer->getData());
	}


}

$string  .= "\n\n\n\n\n\n\n\n" . 'Clientes não encontrados na base: ' . "\n\n\n";

foreach($clientesNaoEncontrados as $customer)
{
	$string .= implode(',', $customer) . "\n";
}

$string  .= "\n\n\n\n\n\n\n\n" . 'Clientes não atualizados pois a data de atualização é maior do que 01/04/2015: ' . "\n\n\n";

foreach($clientesAtualizadosDepois as $customer)
{
	$string .= implode(',', $customer) . "\n";
}

$string  .= "\n\n\n\n\n\n\n\n" . 'Erros ao tentar salvar clientes: ' . "\n\n\n";

foreach($errors as $error)
{
	$string .= (string)$error . "\n";
}

echo count($clientesNaoEncontrados) . ' - Clientes não encontrados na base'."\n";
echo count($clientesAtualizadosDepois) . ' - Clientes não atualizados pois a data de atualização é maior do que 01/04/2015'."\n";
echo count($customersToSave) . ' - Clientes atualizados'."\n";
echo count($errors) . ' - Erros ao tentar salvar clientes'."\n";

file_put_contents('extras/'.date('Ymd').'-arrumar-dados-clientes-representantesxemail.csv', $string);

//read:


$customers  = array(
	array("prontvet@gmail.com","prontvet@globo.com"),
	array("fabiorpmlog@hotmail.com","atendimento@petstoresantana.com.br"),
	array("floripacv@gmail.com","floripacv@hotmail.com"),
	array("emilianagallo@bol.com.br","contato@lafaiete.com"),
	array("marcio@espaconaturalpet.com.br","jaques.almeida@hotmail.com"),
	array("regianestimpel@hotmail.com","bicharadaciabella@hotmail.com"),
	array("natassia_nati@hotmail.com","cristiane.vet@uol.com.br"),
	array("padrao@petshoppadrao.com","fernandaballes@hotmail.com"),
	array("flaviayumi@uol.com.br","yoma@yomapetcenter.com.br"),
	array("mv.camilalira@gmail.com","bichoerabicho@terra.com.br"),
	array("rosespet@ig.com.br","wilma@advisercontabil.com.br"),
	array("stefano@encrenquinhas.com.br","hotelfazenda@encrenquinhas.com.br"),
	array("santecentroveterinario@gmail.com","abjoia@uol.com.br"),
	array("lie.uehara@uol.com.br","lie.uehara@uol.com"),
	array("patasurbanasrecepcao@gmail.com","leticiaduwal@gmail.com"),
	array("rodrigo@merceariadoanimal.com.br","carlos@merceariadoanimal.com.br"),
	array("cta.vetshop@gmail.com","vetshop@bol.com.br"),
	array("clinica@vetguaipa.com","clinica@vetguaipa.com.br"),
	array("ssantanadeoliveira@hotmail.com","TERRAABIRACHED@HOTMAIL.COM"),
	array("vetvilasboas2@gmail.com","larissabodo@hotmail.com"),
	array("nutripetracoes@bol.com.br","nokama.crm@globo.com"),
	array("simonemaziviero@hotmail.com","LULURODRIGUES05@HOTMAIL.COM"),
	array("deise_dkd@hotmail.com","laravet@uol.com.br"),
	array("petshop_bichosolto@hotmail.com","kkavet@hotmail.com"),
	array("bicho.feliz@uol.com.br","bichofeliz@uol.com.br"),
	array("mister.m.petshop@gmail.com","pr_ismachado@yahoo.com.br"),
	array("robsonpetgarra@hotmail.com","pontual.contabeis@bol.com.br"),
	array("cristina@petshopbionicao.com.br","bionicao@petshopbionicao.com.br"),
	array("pixoxopet@uol.com.br","contato@pixoxo.com.br"),
	array("roselispr@hotmail.com","roselispr@hotmail.com.br"),
	array("marcelo.barletta@hotmail.com","crikaberetta@yahoo.com.br"),
	array("petshopyankee@yahoo.com.br ","taniaferri@yahoo.com.br"),
	array("pet-zoolandia@ig.com.br","pet_zoolandia@ig.com.br"),
	array("mateusmsouto@hotmail.com","danidiol@yahoo.com.br"),
	array("amaral.pet@hotmail.com","miurax8@gmail.com"),
	array("contato@veterinariapontegrande.com.br","pontegrande1982@hotmail.com"),
	array("ka.hisama@hotmail.com","k.ceu@hotmail.com"),
	array("alvorada.guarulhos@gmail.com","alvorada.guarulhos@uol.com.br"),
	array("biancaspetcare@gmail.com","biiancaspetcare@gmail.com"),
	array("pmarialutigarda@yahoo.com.br","M.PENDLOSKI13.MP@GMAIL.COM"),
	array("mv.fernando@gmail.com","CELESTE_BATISTA@HOTMAIL.COM"),
	array("hcveterinario@gmail.com","ricardo.sanches1@gmail.com"),
	array("agropetcasadalavoura@gmail.com","agropetcasadalavoura@ig.com.br"),
	array("viralata.racoes@gmail.com","vira-lata.racoes@hotmail.com"),
	array("petserra@petserra.com.br","diretoria@compulaserg.com.br"),
	array("carlacaccia@ig.com.br","contcassia@ig.com.br"),
	array("agrogibeon@hotmail.com","contabilidadesilva.nfe@gmail.com"),
	array("vet-care@hotmail.com","lila.sanchez@uol.com.br"),
	array("administrativo@petz.com.br","logistica@petcentermarginal.com.br"),
	array("rafael.lancerotte@hotmail.com","rafael@aquasete.com.br"),
	array("sanvete@yahoo.com.br","sanvet@yahoo.com.br"),
	array("carmen.l.bertin@gmail.com","arcadosbichos@uol.com.br"),
	array("vidaanimalbarueri@hotmail.com","afukuya@ig.com.br"),
	array("brunohpc@ig.com.br ","melinapcornea@ig.com.br"),
	array("pataspetshop@hotmail.com","tatapetshop@hotmail.com"),
	array("alphastarpet@hotmail.com","alphastar.petshop@interair.com.br"),
	array("sauaia@superig.com.br","LU.CAMARGOCRUZ@HOTMAIL.COM"),
	array("racoestiko@racoestiko.com.br ","racoestiko@bytes.com.br"),
	array("countryshop@uol.com.br","countryshop@countryshop.com.br"),
	array("clinvetsalvadorfelis@gmail.com","clinicavsf@uol.com.br"),
	array("pupilandigerencia@gmail.com","dr.michelcotia@terra.com.br"),
	array("vetcia@hotmail.com.br","contato@vetecompanhia.com.br"),
	array("cassiana.santoli@gmail.com","racoes_cotia@hotmail.com"),
	array("fernandacortizo@hotmail.com","luciano.vet@uol.com.br"),
	array("racoesjc@hotmail.com","contabilidade.nancy@uol.com.br"),
	array("flaviosalles@hotmail.com","pequenaspatinhas@yahoo.com.br"),
	array("patasegarras2004@hotmail.com","patasgarras2004@hotmail.com"),
	array("secretaria@dredsom.com.br","secretaria@dredson.com.br"),
	array("dudog.pet@hotmail.com","contato@dudog.com.br"),
	array("camilap.o@hotmail.com","camilap.o@ig.com.br"),
	array("carlos.meyer@uol.com.br","edu.meyer@uol.com.br"),
	array("vet.vetca@gmail.com","banhotosa.vetvilasaofrancisco@gmail.com"),
	array("financeiro@osasvet.com.br","osasvet@bol.com.br"),
	array("petshoprrainha@hotmail.com","animalpoente@uol.com.br"),
	array("mirian@lilloelelo.com.br","daloliofranco@yahoo.com.br"),
	array("centrodeesteticacanina@hotmail.com","centrodeesteticacarina@hotmail.com"),
	array("andreza.caroamigo@gmail.com","122388.174@cofrenfe.com.br"),
	array("quel_pimentel@hotmail.com","liliane_tna@hotmail.com"),
	array("kelly_motoori@hotmail.com","leandro.motoori@hotmail.com"),
	array("cattdogs@hotmail.com","catdogs@hotmail.com"),
	array("celiopet@hotmail.com","celipet@hotmail.com"),
	array("mjgli22@gmail.com","epg.1001@gmail.com"),
	array("clinvet.animal@hotmail.com","clinvetanimal@hotmail.com"),
	array("lis_701@hotmail.com","contato@petshopdogmel.com.br"),
	array("dripossatto@hotmail.com","marcomoretti13@hotmail.com"),
	array("sandra@petclinic.com.br","sandrakomatri@uol.com.br"),
	array("alphapet.alphaville@gmail.com","atracco@gmail.com"),
	array("masiandrade@terra.com.br","si_monny@hotmail.com"),
	array("clinicavettaboao@gmail.com","clinicavetaboao@gmail.com"),
	array("gilsantc@gmail.com","erikasxc@gmail.com"),
	array("cladosbichos1@gmail.com","clandosbichos1@gmail.com"),
	array("cleide.rafa@gmail.com","lovinpet.lovinpet@gmail.com.br"),
	array("trevoagropecuaria@gmail.com","trevo_agropecuaria@ig.com.br"),
	array("eujimenes@hotmail.com","eujimenes@terra.com.br"),
	array("allantjuliani@ig.com.br","allantjuliano@ig.com.br"),
	array("paulacfonseca@terra.com.br","datacenter@pronfe.com.br"),
	array("cristianch@superig.com.br","christianamg@hotmail.com"),
	array("r.a.moreno@bol.com.br","rosanamoreno@br.inter.net"),
	array("marcos@vetclinical.com.br","faustobueno@hotmail.com"),
	array("ceta.clinvet@uol.com.br","irtavares@uol.com.br"),
	array("cintia@breeds.com.br","andre@breeds.com.br"),
	array("francisco@emporiodoanimal.com.br","mkt@emporiodoanimal.com.br"),
	array("ivosobraldebrito@msn.com","ivosobraldebrio@msn.com"),
	array("puppyecia@puppyecia.com.br","financeiro@puppyecia.com.br"),
	array("compras@agroveterinaria.com.br","compras@prolicitacoes.com.br"),
	array("mahopetshop@uol.com.br","tkeshitkr@uol.com.br"),
	array("compras@caesegatos24h.com.br","sekay@superig.com.br"),
	array("caodellapetshop@gmail.com","caodella@gmail.com"),
	array("suprimentos@petcare.com.br","est.pacaembu@petcare.com.br"),
	array("matheusdusk@yahoo.com.br ","matheusdusl@yahoo.com.br"),
	array("egidio@bergamini.com.br","nfehiper@bergamini.com.br"),
	array("nferecebidas@petcentermarginal.com.br","logistica.recebimento@petcentermarginal.com.br"),
	array("viannapet@ig.com.br","canicasta@terra.com.br"),
	array("a.ladogano@gmail.com","a.ladogano@uol.com.br"),
	array("mauricio.ramos@petz.com.br","mauricio.ramos@petcentermarginal.com.br alana.zacarioto@petcentermarginal.com.br"),
	array("loja@petshopuauau.com","luciene.cfv@globo.com"),
	array("a.c.augusto@ibest.com.br","claudiogordo.detan@gmail.com"),
	array("adm@planetpetcenter.com.br ","nfeguarulhos@planetpetcenter.com.br"),
	array("hermeslima@terra.com.br","herdog@terra.com.br"),
	array("bemlocaoengenheiro@outlook.com","bemlocaopet@ig.com.br"),
	array("falecom@fernandaconde.com.br","melhor.amigo@terra.com.br"),
	array("cvidiretoria@gmail.com ","cscarabotolovet@uol.com.br"),
	array("consulado@consuladodaracao.com.br","consuladosantaines@gmail.com"),
	array("eduardo@micracom.com.br","ciadogpetshop@ciadogpetshop.com.br"),
	array("contatoestilocao@gmail.com","estilocao@hotmail.com"),
	array("petshopbestfriends@yahoo.com.br","clidapri.petshop@yahoo.com.br"),
	array("pettiziu@yahoo.com.br ","petgil@yahoo.com.br "),
	array("fabiano-batista2006@ig.com.br","patasfelizes@hotmail.com"),
	array("douglasfelixmartins@hotmail.com","douglasfelismartins@hotmail.com"),
	array("edsonhtvet@hotmail.com","edsonhtvel@hotmail.com"),
	array("eduardogadriano@gmail.com","elianemteodora@hotmail.com"),
	array("shebb.vet@uol.com.br","fashionpet.vet@uol.com.br"),
	array("jdfelicidadepetshop@hotmail.com","jdfelicidadepetshop@ig.com.br"),
	array("gildoalegri@yahoo.com.br ","mi_alegri@hotmail.com"),
	array("alirveter@yahoo.com","alir@acdg.com.br"),
	array("grazielagrandini@hotmail.com","ca.vet@gmail.com"),
	array("giroto.caodilheiras@terra.com.br ","giroto.caoeilheiras@terra.com.br "),
	array("animaisworld@hotmail.com","animailworld@hotmail.com"),
	array("veterinario.lemos@ig.com.br","veterinaria.lemos@ig.com.br"),
	array("marco.pacheco@santainesvet.com.br","agenda@santainesvet.com.br"),
	array("contato@lealcompanheiro.com.br","deabernardo@terra.com.br"),
	array("lashimaoka@terra.com.br ","l.ashinaoka@terra.com.br"),
	array("jupmiranda@hotmail.com ","claudialonguini@ig.com.br"),
	array("procao@ig.com.br","procao@procao.com.br"),
	array("mutimcao@hotmail.com","mutincao@terra.com.br"),
	array("animaldestimacao@yahoo.com.br","sarasimone@uol.com.br"),
	array("vetdicezare@hotmail.com","vetdicezari@hotmail.com"),
	array("petshopnovakilica@gmail.com","petshopkilica@hotmail.com"),
	array("debora@patinhasecia.com.br","marcia@patinhascia.com.br"),
	array("contato@alamodog.com.br","contato@alanodog.com.br"),
	array("gautz@bol.com.br","atendimento@gautz.com.br"),
	array("marizaceu@ibest.com.br","eddogpetshop@hotmail.com"),
	array("centroesteticoamigosdasferas@gmail.com","amigodasferas@ig.com.br"),
	array("glekaxinhos@hotmail.com","glekaxinhos@gmail.com"),
	array("sheila@globalpetshop.com.br","globalpet@globalpet.com.br"),
	array("maretto10@gmail.com","maretto@uol.com.br"),
	array("ishiii@uol.com.br","ka.ishii@hotmail.com"),
	array("dra.carol@villacani.com.br","dra.carolina@villacani.com.br"),
	array("veterinariamoradadosanimais@bol.com.br","moradadosanimais@bol.com.br"),
	array("sarafajardo@ig.com.br","sarafarjado@ig.com.br"),
	array("contato@clinicadecaesegatosvv.com.br","contato@clinicadecaesegatos.com.br"),
	array("contato@amadopet.com.br","carolinyvet@terra.com.br"),
	array("eduardoperusso@uol.com.br","reginaperusso@hotmail.com"),
	array("lamtwister@terra.com.br","lamtwitter@terra.com.br"),
	array("petbullracoes2013@live.com","filas@contimax.com.br"),
	array("jandrefe@terra.com.br","jandreafe@terra.com.br"),
	array("recarva@yahoo.com.br","recava@yahoo.com.br"),
	array("peraltaspetshop@gmail.com","rodrigo@planoacessoriacontabil.com.br"),
	array("carveca@ig.com.br","wagner@mercadospet.com.br"),
	array("ronaldo.beltran@uol.com.br","ronaldo.beltron@uol.com.br"),
	array("atendimento.mercearia@hotmail.com","notasnf@contabilidadelm.com.br"),
	array("ohmydogpet@live.com","ohmydog@terra.com.br"),
	array("rudld1@ig.com.br","rudl@ig.com.br"),
	array("adm.emporiumanimale@gmail.com","vgpetagro@yahoo.com.br"),
	array("danielapaulopoli@hotmail.com","danielpaulopoli@hotmail.com"),
	array("clinica.aguafria@gmail.com","herzi@uol.com.br"),
	array("pet.maximo@ig.com.br","petmaximo@ig.com.br"),
	array("clinicaveterinariaparadapet@ig.com.br","paradapet@ig.com.br"),
	array("dogsfamilipetshop@uol.com.br","dogsfamilipetshop@hotmail.com"),
	array("contato@animalypetshop.com.br","contato@anumalypetshop.com.br"),
	array("bmg19804@hotmail.com","sac@pinkao.com.br"),
	array("cibylleduran@hotmail.com","pbadejo@hotmail.com"),
	array("animalplace@hotmail.com","jorgemoraes@animalplace.com.br"),
	array("tatipacheco@hotmail.com","tatipacheco@quintaldosbichos.net"),
	array("emerson_navarro@globomail.com","emersonnavarro@globomail.com"),
	array("mondepets@outlook.com","emoraisproducoes@gmail.com"),
	array("petshop_clean@hotmail.com","petshopclean@hotmail.com"),
	array("katia.massonetto@uol.com.br","katia.massoneto@uol.com.br"),
	array("srkorber@ig.com.br","kerayr@kob.com.br"),
	array("thathyvet@hotmail.com","amaveterinaria@hotmail.com"),
	array("simoneojj@ig.com.br","simonejj@ig.com.br"),
	array("claytoncarvalhorosa@hotmail.com","claytoncarvalho@hotmail.com"),
	array("edu-nogueira11@hotmail.com","edu_nogueira11@hotmail.com"),
	array("iepetesteticaanimal@gmail.com","ieptesteticaanimal@gmail.com"),
	array("yorkstilo@gmail.com","marianoortizchernandez@gmail.com"),
	array("horodenkosoares@gmail.com","hgs.vet@gmail.com"),
	array("petcenteryaya@gmail.com","rafael.fnandrade@hotmail.com"),
	array("goldenvets@gmail.com","goldenvests@gmail.com"),
	array("atendimento@funnydogs.com.br","atendimento@funnydog.com.br"),
	array("fabio@manjerikao.com.br","fabinho.dearaujo@gmail.com.br"),
	array("diogogarcia10@hotmail.com","drikavet2002@hotmail.com"),
	array("animalle@yahoo.com.br","animalle@yahoo.com"),
	array("wagner.wcr@hotmail.com","petwave@hotmail.com"),
	array("soaresrlb.freitas@bol.com.br","edgard@escritoriosantana.com.br"),
	array("ortiz.carina@hotmail.com","cabeÃ§adebagre@hotmail.com.br"),
	array("compato@petshopfarofino.com.br","mirian@bobson.com.br"),
	array("veterinariapetshop@gmail.com","veterinariapetamigo@gmail.com"),
	array("petitami.vet@gmail.com","petitamivet@gmail.com"),
	array("natomveterinaria@gmail.com","natoclinica@hotmail.com"),
	array("clinicapontapora@gmail.com","clinicaveterinariapontapora@ajato.com.br"),
	array("valdirvertente@yahoo.com.br","wdmzloti@terra.com.br"),
	array("claudiaesergio@globo.com","canilmenorah@globo.com"),
	array("contato@petbichosetal.com.br","andre_anlee@yahoo.com.br"),
	array("pet.field@hotmail.com","fa.zampollo@bol.com.br"),
	array("contato@petsupremo.com.br","eduardobotter2011@hotmail.com"),
	array("patricia.pet.care@gmail.com","pet.care@uol.com.br"),
	array("ceve476@gmail.com","rchalpern@yahoo.com.br"),
	array("petshopeobicho@hotmail.com","rgalesco@uol.com.br"),
	array("clinica.vet.mutinga@hotmail.com","fcramalho@hotmail.com"),
	array("gustavo.saudepet@gmail.com","veterinariasaudepet@gmail.com"),
	array("aviculturapan@uol.com.br","jpires5218@terra.com.br"),
	array("vetgreenpet@gmail.com","smalaga@uol.com.br"),
	array("dr.train@bol.com.br","zoofarma@uol.com.br"),
	array("vetemporiodosbichos@gmail.com","octavionery@hotmail.com"),
	array("dalvarodrigues.2011@hotmail.com","fiscal1@camiscontabilidade.com.br"),
	array("leo_pascini@hotmail.com","reginaldo_moraes@terra.com.br"),
	array("puppylandsp2@hotmail.com","puppylandssp2@hotmail.com"),
	array("caomaradas2@ig.com.br","caomaradas@ig.com.br"),
	array("carlosalbertoestilo@uol.com.br","estilocao@hotmail.com"),
	array("janainakfranca@gmail.com","janainakfranca@ig.com.br"),
	array("vetpaulistano@gmail.com","paulistano24h@gmail.com"),
	array("rmracoes.cristiano@hotmail.com","rmraÃ§Ãµes.cristiano@hotmail.com"),
	array("carloshm76@yahoo.com.br","machadope2@ig.com.br"),
	array("info@cevtsfa.com.br","info@cevetsfa.com.br"),
	array("spazziopet@hotmail.com","dra.renata@spazziopet.com.br"),
	array("marcio@mgcentroveterinario.com.br","mag_vet@hotmail.com"),
	array("elirodrigues285@gmail.com","juniordouglas@ig.com.br"),
	array("contato@cvetap.com.br","marcos.roseli@uol.com.br"),
	array("contato@viraalata.com.br","zonesdri@hotmail.com"),
	array("vet.mascote@bol.com.br","marcio.alceu@uol.com.br")
);

echo 'Atualizando a base da Raira:' . "\n";


$clientesNaoEncontrados = array();
$clientesAtualizados = array();
$errors = array();

foreach ($customers as $customer)
{
	echo '+';
	$model = Mage::getModel('customer/customer')
		->getCollection()
		->addAttributeToSelect('email')
		->addAttributeToFilter('email', $customer[1])
		->addAttributeToFilter('website_id', '5')
		->getFirstItem();
	if ($model->getId())
	{
		try
		{
			$model->setEmail($customer[0]);
			$model->save();
			$clientesAtualizados[] = $model->getData();
		}
		catch(Exception $e)
		{
			$errors[] = (string)$e->getMessage() . ',' . implode(',', $model->getData());
		}
	}
	else
	{
		$clientesNaoEncontrados[] = $customer;
	}
}

$string = 'Clientes atualizados:' . "\n\n\n";
foreach($clientesAtualizados as $cliente)
{
	$string .= implode(',', $cliente)."\n";
}

$string  .= "\n\n\n\n\n\n\n\n" . 'Clientes não encontrados: ' . "\n\n\n";

foreach($clientesNaoEncontrados as $cliente)
{
	$string .= implode(',', $cliente)."\n";
}

$string  .= "\n\n\n\n\n\n\n\n" . 'Erros ao tentar salvar clientes: ' . "\n\n\n";

foreach($errors as $error)
{
	$string .= (string)$error . "\n";
}

echo "\n";
echo count($clientesAtualizados) . ' - Clientes atualizados' . "\n";
echo count($clientesNaoEncontrados) . ' - Clientes não encontrados' . "\n";
echo count($errors) . ' - Erros ao salvar clientes' . "\n";

file_put_contents('extras/'.date('Ymd').'-arrumar-dados-clientes-somente_email.csv', $string);

?>