<div class="bkg-cover" style="background-image: url(<?php echo $this->getSkinUrl('images/institutional/como_participar/hotsite_4_pg2_bkg.jpg') ?>)">

  <div class="como-participar default-page-width">
    <div class="menu">
      <div class="logo">
        <img src="<?php echo $this->getSkinUrl('images/institutional/como_participar/gatinho.png') ?>"/>
      </div>
      <div class="menu-content" style="display: none;">
        <p>CAMPANHA</p>
        <h1><strong>escute seu pet</strong></h1>
        <p>faça exames preventivos</p>
      </div>
      <div class="menu-buttons">
        <a class="active" href="/a-campanha">CAMPANHA</a>
        <a href="/clinicas-participantes">CLÍNICAS PARTICIPANTES</a>
      </div>
    </div>
    <div class="video">
      <video width="100%" controls="true"
             poster="<?php echo $this->getSkinUrl('images/institutional/como_participar/hotsite_4_pg1.jpg') ?>">
        <source src="/media/videos/idexx/video_campanha.mp4">
      </video>
    </div>
    <div class="content">
      <div class="data-header">
        <h1>
          Você pode fazer<br/> mais pelo seu animal de estimação
        </h1>
      </div>
      <div class="data-content">
        <p>Nós sabemos o quanto os animais de estimação são importantes para os seus donos. E a melhor forma de demonstrar o carinho que você tem pelo seu pet é cuidando da saúde dele.</p>

        <p>O maior movimento a favor dos cuidados preventivos com a saúde dos animais de estimação chega para promover uma profunda conscientização sobre os exames e diagnósticos para pets.</p>

        <p>Com o apoio de todos os veterinários e com a sua participação, a IDEXX assume esse importante compromisso: espalhar a importância dos cuidados preventivos.</p>

        <p>Aqui, você irá encontrar <a style="color: #ba2234;" href="/clinicas-participantes">a clínica participante mais próxima</a> de você para utilizar seu voucher.</p>

        <p>Retribua todo carinho que seu pet lhe dá. Junte-se a nós, espalhe essa ideia. Assim como a IDEXX, você sabe: pet bem cuidado é mais feliz e mais saudável.</p>
      </div>
    </div>
  </div>

</div>