<?php if ($this->getCollection() && $this->getCollection()->getSize()): ?>
    <div class="block block-category-topcategoryviewed">
        <div class="block-title">
            <strong><?php echo $this->__('Categorias mais vistas'); ?></strong>
        </div>
        <ul>
            <?php foreach ($this->getCollection() as $category): ?>
                <li><a href="<?php echo $category->getUrl(); ?>"><?php echo $category->getName(); ?></a></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>