<?php
$_coreHelper = $this->helper('core');
$checkoutHelper = Mage::helper('onestepcheckout/checkout');
?>
<div class="clear"></div>
<div class="onestepcheckout-summary-scroll">
	<table class="onestepcheckout-summary">
		<thead>
			<tr>
				<th class="name"><?php echo $this->__('Product'); ?></th>
				<th class="total"><?php echo $this->__(''); ?></th>
				<th class="qty"><?php echo $this->__('Qty'); ?></th>
				<th class="total"><?php echo $this->__('Subtotal'); ?></th>
				<?php if(Mage::getStoreConfig('onestepcheckout/general/show_tableprice_price')): ?>
					<th class="total"><?php echo $this->__('Total'); ?></th>
				<?php endif; ?>
			</tr>
		</thead>
		<?php foreach($this->getItems() as $item): ?>
		<tr>
			<td class="name">
				<?php echo $item->getName(); ?>
				<?php if($checkoutHelper->settings['show_custom_options']): ?>
					<?php $options = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct()); ?>
					<?php if(isset($options['options']) && count($options['options']) > 0): ?>
					<ul class="onestepcheckout-custom-options">
					<?php foreach($options['options'] as $option): ?>
						<li><b><?php echo $option['label'] . ':</b> ' . $option['value']; ?></li>
					<?php endforeach; ?>
					</ul>
					<?php endif; ?>

					<?php if($item->getProduct()->isConfigurable()): ?>

					<?php
					$configurable_options = $item->getProduct()->getTypeInstance(true)->getSelectedAttributesInfo($item->getProduct());
					?>

					<?php if(is_array($configurable_options) && count($configurable_options) > 0): ?>
					<ul class="onestepcheckout-custom-options">
					<?php foreach($configurable_options as $option): ?>
						<li><b><?php echo $option['label']; ?>:</b> <?php echo $option['value']; ?></li>
					<?php endforeach; ?>
					</ul>
					<?php endif; ?>

					<?php endif; ?>

				<?php endif; ?>
			</td>

			<td>
				<?php $_product = Mage::getModel('catalog/product')->load($item->getData('product_id')); ?>
				<?php echo Mage::helper('fvets_salesrule')->getLabelHtml($_product) ?>
			</td>

			<td class="qty"><?php echo $item->getQty(); ?></td>
			<?php if(Mage::getStoreConfig('onestepcheckout/general/show_tableprice_price')): ?>
				<td class="total">
					<?php if ($item->getOriginalPrice() * $item->getQty() > $this->helper('checkout')->getSubtotalInclTax($item)) : ?>
						<?php echo str_replace('R$', '', $this->helper('checkout')->formatPrice($item->getOriginalPrice() * $item->getQty(), true)); ?>
					<?php else : ?>
						<?php echo str_replace('R$', '', $this->helper('checkout')->formatPrice($this->helper('checkout')->getSubtotalInclTax($item), true)); ?>
					<?php endif; ?>
				</td>
			<?php endif; ?>
			<td class="total">
				<?php if($checkoutHelper->settings['display_tax_included']): ?>
					<?php $_price = $this->helper('checkout')->formatPrice($this->helper('checkout')->getSubtotalInclTax($item)); ?>
				<?php else: ?>
					<?php $_price = $this->helper('checkout')->formatPrice($item->getRowTotal()); ?>
				<?php endif; ?>
				<?php if(Mage::getStoreConfig('onestepcheckout/general/show_tableprice_price')): ?>
					<?php echo str_replace('R$', '', $_price); ?>
				<?php else: ?>
					<?php echo $_price; ?>
				<?php endif; ?>
			</td>
		</tr>
		<?php endforeach; ?>
	</table>
</div>

<table class="onestepcheckout-totals"><table class="onestepcheckout-totals" width="100%">
		<?php foreach($this->getTotals() as $total): ?>
			<?php if(!$total->getTitle()){continue;}?>
			<?php
			$fullInfo = $total->getFullInfo();

			if(!empty($fullInfo) && $checkoutHelper->settings['display_full_tax']):
				foreach ($fullInfo as $info):
					$rates = current($info['rates']);
					$amount = $info['amount'];
					?>
					<tr>
						<td class="title"><?php echo $rates['title'] ?> (<?php echo $rates['percent'] ?>%)</td><td class="value"><?php echo $this->helper('checkout')->formatPrice($amount); ?></td>
					</tr>
				<?php endforeach;
			endif;?>
			<tr class="<?php if($total->getCode() == 'grand_total'): ?>grand-total<?php endif; ?> <?php if(strpos($total->getCode(), 'discount') !== false || $total->getCode() == 'payment_condition'): ?>discount<?php endif; ?>">
				<td class="title">
					<?php

					$code = $total->getCode();
					$value = $total->getValue();


					if($code == 'subtotal')    {
						$total_name = $this->__('Subtotal');
					}
					elseif($code == 'shipping')    {
						$total_name = $this->__('Shipping');
						if($checkoutHelper->settings['display_tax_included'])   {
							$value += $this->getQuote()->getShippingAddress()->getShippingTaxAmount();
						}
					}
					elseif($code == 'grand_total')    {
						$total_name = $this->__('Grand total');
					}
					elseif($code == 'discount')
					{
						$total_name = $this->__('Discounts total');
					}
					else    {
						$total_name = $total->getTitle();
					}

					if(strpos($total->getCode(), 'discount') !== false || $total->getCode() == 'payment_condition'):
						echo '<a class="tooltip">' . $this->__($total_name);
						if ($rules = $total->getRules()) :
							echo '<span>
        					<strong>Desconto</strong><br>';
							foreach ($rules as $rule) :
								if ($description = $rule->getDescription()) :
									echo $description . '<br />';
								else :
									echo $rule->getName() . '<br />';
								endif;
							endforeach;
							echo '</span>';
						endif;
						echo '</a>';
					else :
						echo $total_name;
					endif;

					?>
				</td>
				<td class="value">
					<?php if(strpos($total->getCode(), 'discount') !== false || $total->getCode() == 'payment_condition'): ?>-<?php endif; ?><?php echo $this->helper('checkout')->formatPrice($value); ?>
				</td>
			</tr>
			<div class="total_rule_pupup">
				<?php

				?>
			</div>
		<?php endforeach; ?>
	</table>
<script type="text/javascript">
//<![CDATA[
var total = <?php echo $this->getGrandTotal();?>;
    if(payment.reloadcallback){
        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/paymentrefresh', array('_secure'=>true)); ?>';
        paymentrefresh(url);
        payment.countreload = 0;
        payment.reloadcallback = false;
    }

jQuery(".campaign-label a.tooltip").hover(function () {
	initProlabels();
});

//]]>
</script>
