<?php

/**
 * Widget Slider
 */
$widget = Mage::getModel('widget/widget_instance')->load(1);
$widgetSlider = $this
	->getLayout()
	->createBlock($widget->getType(),
		$widget->getTitle(),
		$widget->getWidgetParameters());


/**
 * Widget Banners
 */
$widget = Mage::getModel('widget/widget_instance')->load(2);
$widgetBanners = $this
	->getLayout()
	->createBlock($widget->getType(),
		$widget->getTitle(),
		$widget->getWidgetParameters());

?>


<div class="callout-home-top col2-set">
	<div class="col-1"><?php echo $widgetSlider->toHtml(); ?></div>
	<div class="col-2"><?php echo $widgetBanners->toHtml(); ?></div>
</div>

<div class="col-main"><?php echo $this->getChildHtml('brands_list') ?></div>

</div>
	</div>
		<hr />
	<div class="main">
<div>

<div class="col-main"><?php echo $this->getChildHtml('homepage_featured') ?></div>

</div>
	</div>
		<hr />
	<div class="main">
<div>

<div class="col-main"><?php echo $this->getChildHtml('homepage_new') ?></div>

</div>
	</div>
		<hr />
	<div class="main">
<div>

<div class="col-main"><?php echo $this->getChildHtml('home_bestseller') ?></div>