<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>

<?php
	$blockClassName = Mage::getConfig()->getBlockClassName('catalog/navigation');
	$block = new $blockClassName();
	$_helper    = $this->helper('catalog/output');
	$_category  = $this->getCurrentCategory();

	$_childrens = Mage::getModel('catalog/category')->load($_category->getId())->getChildrenCategories();
?>


<div class="block">
	<div class="block-title">
		<a href="<?php echo $block->getCategoryUrl($_category); ?>" alt="<?php echo $_category->getName(); ?>"><strong><?php echo $_category->getName(); ?></strong></a>
	</div>
	<div class="block-content">
			<dl id="narrow-by-list">
				<?php $i = 0; ?>
				<?php foreach ($_childrens as $_child) : ?>

						<dt><a href="<?php echo $block->getCategoryUrl($_child); ?>" alt="<?php echo $_child->getName() ?>"><?php echo $_child->getName() ?></a></dt>

				<?php endforeach; ?>
			</dl>
			<script type="text/javascript">decorateDataList('narrow-by-list')</script>
	</div>
</div>