<div class="up-footer">
	<div class="news-social-container">
		<div class="news">
			<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
				<?php echo $this->getChildHtml('global_messages'); ?>
				<span class="title">Receba nossas notícias</span>
				<br>
				<input placeholder="Digite o seu e-mail" type="text" name="email" id="newsletter"/>
				<button type="submit">Enviar</button>
			</form>
		</div>
		<div class="social">
			<h4>Redes sociais</h4>
			<div class="clear"></div>
			<a href="https://www.facebook.com/idexxbrasil">
				<i class="fa fa-facebook-square fa-4x"></i>
			</a>
			<a href="https://www.linkedin.com/company/idexx-laboratories">
				<i class="fa fa-linkedin-square fa-4x"></i>
			</a>
			<a href="https://www.youtube.com/user/idexxvideos">
				<i class="fa fa-youtube-square fa-4x"></i>
			</a>
		</div>
	</div>
</div>