<?php
    $_productCollection = $this->getLoadedProductCollection();
    $_helper            = $this->helper('catalog/output');
    $_collectionSize    = $_productCollection->count();
    $_columnCount       = $this->getColumnCount();
?>
<?php if (!$_collectionSize) : return; endif; ?>

<div class="category-products <?php echo $this->getClassName() ?>">
    <h1 class="block-title"><span><?php echo $this->__($this->getTitle()) ?></span></h1>
    <div class="block-content">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid cols-<?php echo $_columnCount ?>">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
				<h5 class="product-name"><a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h5>
				<div>
					Cód: <?php echo $_product->getSku(); ?>
				</div>
                <div class="prolabel-wrapper">

										<?php echo Mage::helper('fvets_salesrule')->getLabelHtml($_product) ?>

                    <a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200); ?>" width="200" height="200" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                </div>
                <?php echo $this->getLayout()->createBlock('prolabels/category')->setProduct($_product)->toHtml(); ?>
				<div>
					<a class="featured" href="<?php echo $this->getProductUrl($_product) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->__('See details'); ?> ></a>
				</div>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true, $this->getPriceSuffix()) ?>
				<div class="clear"></div>
				<?php if(Mage::helper('privatesales')->canShowPricesAndAddToCartButton()) { ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
						<div class="divQtd">
							<label for="qty" class="qtyLabel"><?php echo $this->__('Qty') ?></label>
							<div class="qtyButtons">
								<input type='button' value='-' class='qtyminus' field='qty-<?php echo $_product->getId(); ?>' />
								<input type='text' name='quantity' value='1' class='qty' id="qty-<?php echo $_product->getId(); ?>"/>
								<input type='button' value='+' class='qtyplus' field='qty-<?php echo $_product->getId(); ?>' />
							</div>
							<div class="clear"></div>
						</div>
						<div class="clear"></div>
                        <div>
							<button type="button" title="<?php echo $this->__('Add to Shopping Cart') ?>" class="button btn-cart" onclick="addToCart('<?php echo $this->getAddToCartUrl($_product) ?>', <?php echo $_product->getId(); ?>)"><span><span><?php echo $this->__('Add to Shopping Cart') ?></span></span></button>
						</div>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                </div>
				<?php } ?>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <div class="clearer"></div>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    </div>
</div>