<?php
/**
 * Customer Login Template for Community Edition 1.7
 *
 * @author     Design:Slider GbR <magento@design-slider.de>
 * @copyright  (C)Design:Slider GbR <www.design-slider.de>
 * @license    OSL <http://opensource.org/licenses/osl-3.0.php>
 * @link       http://www.design-slider.de/magento-onlineshop/magento-extensions/private-sales/
 * @package    DS_PrivateSales
 */

$helper = Mage::helper('privatesales');
/* @var $helper DS_PrivateSales_Helper_Data */

$storeName = Mage::getStoreConfig('general/store_information/name');

$canShowRegPanel = $helper->canShowRegistrationLoginPanel();
$customRegPanel = ($helper->getShowRegistrationLoginPanel()==2);
$customRegHeader = $helper->getRegistrationPanelHeader();
$customRegText = $helper->getRegistrationPanelText();
$canShowRegButton = $helper->canShowRegistrationPanelButton();
$customButtonText = $helper->getRegistrationPanelButtonText();
$isForgotPasswordEnabled = $helper->canShowForgotPassword();
$isRegistrationEnabled = $helper->canShowRegistration();
?>
<div class="hidden">
	<div id="newsletter-featherlight-login">
		<?php /* Extensions placeholder */ ?>
		<?php echo $this->getChildHtml('customer.form.login.extra')?>
		<form action="<?php echo str_replace(array('https://', 'http://'), '//', Mage::getBaseUrl()) . 'customer/account/loginByEmail' ?>" method="post" id="login-form">
			<?php echo $this->getBlockHtml('formkey'); ?>
			<div>
				<div class="registered-users">
					<div class="title">
						<h2>Você já é cliente <?php echo $storeName; ?></h2>
						<div>
							Você que já é cliente, está pré-cadastrado. Basta logar com seu e-mail.
						</div>
					</div>
					<div class="content">
						<ul class="form-list">
							<li class="input-group featured">
									<span class="input-group-addon"><i class="fa fa-user"></i></span>
									<input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" placeholder="email" class="input-text required-entry validate-email" title="<?php echo Mage::helper('customer')->__('Email Address') ?>" />
							</li>
							<?php echo $this->getChildHtml('form.additional.info'); ?>
						</ul>
						<br />
						<div class="action-buttons">
							<button type="submit" class="button btn-superAction" title="<?php echo Mage::helper('customer')->__('Fazer login') ?>" name="send" id="send2"><span><span><?php echo Mage::helper('customer')->__('Fazer login') ?></span></span></button>
						</div>

						<?php if ($canShowRegPanel): ?>
							<div class="new-users">
								<h4><span>OU</span></h4>
								<hr />
								<div class="clear"></div>
								<?php if (!$customRegPanel || $canShowRegButton): ?>
									<button type="button" title="<?php echo ($customRegPanel && strlen($customButtonText)) ? $customButtonText : Mage::helper('customer')->__('Register') ?>" class="button" onclick="window.location='<?php echo $this->getCreateAccountUrl() ?>';"><span><span><?php echo ($customRegPanel && strlen($customButtonText)) ? $customButtonText : Mage::helper('customer')->__('Register') ?></span></span></button>
								<?php else: ?>
									<button type="button" class="button" style="visibility:hidden;" disabled="disabled"><span><span></span></span></button>
								<?php endif; ?>
							</div>
						<?php endif; ?>
					</div>
				</div>
			</div>
		</form>
		<script type="text/javascript">
			//<![CDATA[
			var dataForm = new VarienForm('login-form', true);
			jQuery(document).ready(function() {
				var configuration = ({
					closeOnClick: false,
					closeOnEsc: true
				});
				jQuery.featherlight(jQuery('#newsletter-featherlight-login'), configuration);
			});
			//]]>
		</script>

	</div>
</div>