<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<?php $comments = $this->getComments() ?>
<?php if (count($comments) > 0): ?>
	<ul class="comment-list<?php if ($this->getParentId()): ?> children<?php endif; ?>">
		<?php foreach($comments as $comment): ?>
			<li class="comment" id="comment-<?php echo $comment->getId() ?>">
				<div class="comment-inner row">
					<div class="row">
						<?php if ($comment->getGravatarUrl()): ?>
							<div class="gravatar col-md-1">
								<img src="<?php echo $comment->getGravatarUrl() ?>" alt="<?php echo $this->escapeHtml($comment->getCommentAuthor()) ?>" class="img-thumbnail"/>
							</div>
						<?php endif; ?>
						<div class="comment-meta comment-date by <?php if ($comment->getGravatarUrl()): ?>col-md-11<?php else: ?>col-md-12<?php endif; ?>">
							<div class="row">
								<div class="comment-header"><strong><?php echo $this->escapeHtml($comment->getCommentAuthor()) ?></strong> <?php echo $this->__('%s at %s', Mage::helper('core')->formatDate($comment->getData('comment_date'), 'short', false) , $comment->getCommentTime()) ?></div>
							</div>
							<div class="row">
								<p class="comment-entry entry"><?php echo nl2br($this->escapeHtml($comment->getCommentContent())) ?></p>
							</div>
							<?php if ($this->canComment()): ?>
								<div class="reply">
									<a href="<?php echo $this->getPost()->getPermalink() ?>?replytocom=<?php echo $comment->getId() ?>#respond" class="comment-reply-link"><?php echo $this->__('Reply') ?></a>
								</div>
							<?php endif; ?>
						</div>

					</div>					
				</div>
				<?php echo $this->getChildrenCommentsHtml($comment) ?>
			</li>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>
<br />
<br />