<div class="blockcontact">
	<div class="bkcontact-container">
		<div class="description">
			<h2>Entre em contato</h2>
			<span>Se você tem alguma dúvida, deseja adquirir um produto ou quer saber mais <br /> sobre nossas soluções, entre em contato conosco!</span>
		</div>
		<div class="contact">
			<div class="telephone">
				<i class="fa fa-phone fa-3x"></i>
				<span><?php echo Mage::getStoreConfig('general/store_information/phone') ?></span>
			</div>
			<div class="email">
				<i class="fa fa-envelope-o fa-3x"></i>
				<span><?php echo Mage::getStoreConfig('trans_email/ident_general/email') ?></span>
			</div>
		</div>
	</div>
</div>