<?php $attribute = Mage::helper('fvets_attributemenu')->getAttribute(); ?>
<?php $productAttributeValue = Mage::app()->getRequest()->getParam($attribute->getAttributeCode()); ?>

<div class="brandContainer">
	<h1 class="block-title"><span><?php echo $this->__('Brands'); ?></span></h1>

	<?php

	$categories = $this->getStoreCategories(false, true, false);

	$categories = Mage::helper('fvets_attributemenu')->filterCategoriesByProductAttribute($categories, $attribute->getAttributeId(), $productAttributeValue);
	?>

	<?php $currentUrl = Mage::helper('core/url')->getCurrentUrl(); ?>
	<?php	$totalRegisters = count($categories);
	?>
	<?php if ($totalRegisters > 0): ?>
		<ul class="brands-list">
			<?php foreach ($categories as $category): ?>
				<?php $category = Mage::getModel('catalog/category')->load($category->getId()); ?>
				<?php $urlHeadImg = Mage::getBaseUrl('media') . 'catalog/category/' . $category->getImage(); ?>
				<?php $urlImg = Mage::getBaseUrl('media') . 'catalog/category/' . $category->getThumbnail(); ?>
				<?php if($category->getImage() == true) { ?>
					<img src="<?php echo $urlHeadImg ?>" alt="<?php echo $category->getName(); ?>" title="<?php echo $category->getName(); ?>">
				<?php } ?>
				<li>
					<a class="link-brands featherlight-login" href="<?php echo (strpos($currentUrl, '?') !== false ? ($currentUrl .'&cat=' . $category->getId()) : ($currentUrl .'?cat=' . $category->getId())) ?>">
						<img src="<?php echo $urlImg ?>" alt="<?php echo $category->getName(); ?>"
						title="<?php echo $category->getName(); ?>">
						</a>
						<?php if ($this->isCategoryActive($category)): ?>
							<?php $subcategories = $category->getChildren() ?>
							<?php if (count($subcategories) > 0): ?>
								<ul id="brands">
									<?php foreach ($subcategories as $subcategory): ?>
										<li>
											<a class="link-brands featherlight-login"
											href="<?php echo $helper->getCategoryUrl($subcategory) ?>"><?php echo $this->escapeHtml(trim($subcategory->getName(), '- ')) ?></a>
										</li>
									<?php endforeach; ?>
								</ul>
							<?php endif; ?>
						<?php endif; ?>
					</li>
				<?php endforeach; ?>
			</ul>
		<?php endif; ?>
		
		<div class="clear"></div>
	</div>