<?php
$formErrors = $this->getParentBlock()->formErrors;
$formErrors = (!empty($formErrors['billing_errors'])) ? $formErrors['billing_errors'] : array();

$helper = Mage::helper('onestepcheckout/checkout');
$dataHelper = Mage::helper('onestepcheckout');

$customer = $this->getCustomer();
if ($this->customerHasAddresses()) {
	$address = 	Mage::getModel('customer/address')->load($customer->getDefaultBillingAddress()->getId());
} else {
	$address = $this->getQuote()->getBillingAddress();
}

$customerFieldsComplete = array();
$customerFieldsIncomplete = array();

$addressFieldsComplete = array();
$addressFieldsIncomplete = array();

$show_save_button = false;
$hide_checkout_button = false;

$showFieldsText = array();

if ($customer->getTipopessoa() == 'PJ')
{
	$showFieldsText = array('razao_social', 'email', 'telephone', 'cpf', 'cnpj', 'street', 'city');
}
	else if ($customer->getTipopessoa() == 'PF')
{
	$showFieldsText = array('firstname', 'lastname', 'email', 'telephone', 'cpf', 'street', 'city');
}

if ($dataHelper->clearDash($address->getFirstname()) == '')
{
	$show_save_button = true;
	$hide_checkout_button = true;
	$customerFieldsIncomplete['firstname'] = '
					<div class="input-box input-firstname'.((in_array('firstname', $formErrors)) ? ' input-error' : '').'">
							<label for="billing:firstname">'.$this->__('First Name').' <span class="required">*</span></label><br />
							<input class="required-entry input-text" type="text" name="billing[firstname]" id="billing:firstname" value="'.$dataHelper->clearDash($address->getFirstname()).'" />
					</div>';
} else {
	$customerFieldsComplete['firstname'] = '';
	//if (in_array('firstname', $showFieldsText))
	//{
		$customerFieldsComplete['firstname'] .= '<strong>'.$dataHelper->clearDash($address->getFirstname()).'</strong>';
	//}
	$customerFieldsComplete['firstname'] .= '<input type="hidden" name="billing[firstname]" value="'.$dataHelper->clearDash($address->getFirstname()).'" />';
}

if ($dataHelper->clearDash($address->getLastname()) == '') :
	$show_save_button = true;
	$hide_checkout_button = true;
	$customerFieldsIncomplete['lastname'] = '
					<div class="input-box input-lastname'.((in_array('lastname', $formErrors)) ? ' input-error' : '').'">
							<label for="billing:lastname">'.$this->__('Last Name').' <span class="required">*</span></label><br />
							<input class="required-entry input-text" type="text" name="billing[lastname]" id="billing:lastname" value="'.$dataHelper->clearDash($address->getLastname()).'" />
					</div>';
else :
	$customerFieldsComplete['lastname'] = '';
	//if (in_array('lastname', $showFieldsText))
	//{
		$customerFieldsComplete['lastname'] .= '<strong>'.$dataHelper->clearDash($address->getLastname()).'</strong>';
	//}
	$customerFieldsComplete['lastname'] .= '<input type="hidden" name="billing[lastname]" value="'.$dataHelper->clearDash($address->getLastname()).'" />';
endif;

?>



<?php if(!$this->isCustomerLoggedIn() || in_array('email_registered', $formErrors)): ?>
	<?php $customerFieldsIncomplete['email'] = '
        <div class="clearfix" id="onestepcheckout-email-error" '.((!in_array('email_registered', $formErrors)) ? 'style="display: none"' : '').'>
            <div id="onestepcheckout-email-error-message" class="onestepcheckout-error">'.
		((in_array('email_registered', $formErrors)) ? $this->__('Email address already registered. Please <a href="#" onclick="login_popup.show(); return false;">login now</a> or use a different email address.') : $this->__('Invalid email address.'))
		.'</div>
        </div>';
	?>
<?php elseif(!$this->isCustomerLoggedIn()): ?>
	<?php $customerFieldsIncomplete['email'] = $billingFields['email'].'
        <div class="input-box input-email'.((in_array('email', $formErrors)) ? ' input-error' : '').'">
            <label for="billing:email">'.$this->__('Email Address').' <span class="required">*</span></label><br />
            <input type="email" name="billing[email]" id="billing:email" value="'.$dataHelper->clearDash($address->getEmail()).'" title="'.$this->__('Email Address') .'" class="validate-email required-entry input-text" />
        </div>';
	?>
<?php else: ?>
	<?php
		$customerFieldsComplete['email'] = '';
		//if (in_array('email', $showFieldsText))
		//{
			$customerFieldsComplete['email'] .= Mage::helper('onestepcheckout')->__('Email').': '.$dataHelper->clearDash($customer->getEmail());
		//}
		$customerFieldsComplete['email'] .= '<input type="hidden" name="billing[email]" value="'.$dataHelper->clearDash($customer->getEmail()).'" />';
	?>
<?php endif; ?>


<?php if(!$this->settings['exclude_telephone']):?>
	<?php if ($dataHelper->clearDash($address->getTelephone()) == '') :?>
		<?php $show_save_button = true; ?>
		<?php $hide_checkout_button = true; ?>
		<?php $customerFieldsIncomplete['telephone'] = '
					<div class="input-box input-telephone'.((in_array('telephone', $formErrors)) ? ' input-error' : '').'">
							<label for="billing:telephone">'.$this->__('Telephone').' <span class="required">*</span></label><br/>
							<input type="tel" name="billing[telephone]" value="'.$dataHelper->clearDash($address->getTelephone()).'" title="'.$this->__('Telephone').'" class="required-entry input-text" id="billing:telephone" />
					</div>';
		?>
	<?php else : ?>
		<?php
			$customerFieldsComplete['telephone'] = '';
			//if (in_array('telephone', $showFieldsText))
			//{
				$customerFieldsComplete['telephone'] .= Mage::helper('onestepcheckout')->__('Tel').': '.$dataHelper->clearDash($address->getTelephone());;
			//}
			$customerFieldsComplete['telephone'] .= '<input type="hidden" name="billing[telephone]" value="'.$dataHelper->clearDash($address->getTelephone()).'" />';
		?>
	<?php endif; ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_mobilephone']):?>
	<?php if ($dataHelper->clearDash($address->getMobilephone()) == '') :?>
		<?php $show_save_button = true; ?>
		<?php $hide_checkout_button = true; ?>
		<?php $customerFieldsIncomplete['mobilephone'] = '
					<div class="input-box input-mobilephone'.((in_array('mobilephone', $formErrors)) ? ' input-error' : '').'">
							<label for="billing:telephone">'.$this->__('Mobilephone').' <span class="required">*</span></label><br/>
							<input type="tel" name="billing[mobilephone]" value="'.$dataHelper->clearDash($address->getMobilephone()).'" title="'.$this->__('Mobilephone').'" class="required-entry input-text" id="billing:mobilephone" />
					</div>';
		?>
	<?php else : ?>
		<?php
			$customerFieldsComplete['mobilephone'] = '';
			//if (in_array('mobilephone', $showFieldsText))
			//{
				$customerFieldsComplete['mobilephone'] .= Mage::helper('onestepcheckout')->__('Cel').': '.$dataHelper->clearDash($address->getMobilephone());
			//}
			$customerFieldsComplete['mobilephone'] .= '<input type="hidden" name="billing[mobilephone]" value="'.$dataHelper->clearDash($address->getMobilephone()).'" />';
		?>
	<?php endif; ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_address']):?>
	<?php if(Mage::getStoreConfig('onestepcheckout/exclude_fields/enable_address_fields')):?>
		<?php
		$addressFieldsIncomplete['street'] = '';
		$addressFieldsComplete['street'] = '';
		for ($_i=1, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++){
			if ($dataHelper->clearDash($address->getStreet($_i)) == '') {
				$show_save_button = true;
				if ($_i < 3) :
					$hide_checkout_button = true;
				endif;
				$addressFieldsIncomplete['street'] .= '<div class="input-box input-address-short'.((in_array('address', $formErrors)) ? ' input-error' : '').'">
                    <input type="text" title="'.$this->__('Street Address '.$_i).'" name="billing[street]['.$_i.']" id="billing:street'.$_i.'" value="'.$dataHelper->clearDash($address->getStreet($_i)).'" class="';
					if ($_i < 3) :
						$addressFieldsIncomplete['street'] .= ' required-entry ';
					endif;
				$addressFieldsIncomplete['street'] .= 'form-control input-text onestepcheckout-address-line" placeholder="'.$this->__('Street Address '.$_i).'" />
                    </div>';
			} else {
				//if (in_array('street', $showFieldsText))
				//{
					$addressFieldsComplete['street'] .= $dataHelper->clearDash($address->getStreet($_i));
				//}
				$addressFieldsComplete['street'] .= '<input type="hidden" name="billing[street]['.$_i.']" value="'.$dataHelper->clearDash($address->getStreet($_i)).'" />';
			}
		}
		?>
	<?php else:?>
		<?php
		$addressFields = '';
		for ($_i=1, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++){

			$addressFields .= '<input type="text" title="'.$this->__('Street Address '.$_i).'" name="billing[street][]" id="billing:street'.$_i.'" value="'.$dataHelper->clearDash($address->getStreet($_i)).'" class="'.(($_i == 1)? 'required-entry ' : '').'input-text onestepcheckout-address-line" />';
			$addressFields .= (($_i != $this->helper('customer/address')->getStreetLines()) ? '<br/>': '');
		}
		$addressFieldsIncomplete['street'] = '
                <div class="input-box input-address'.((in_array('address', $formErrors)) ? ' input-error' : '').'">
                    <label for="billing:street1">'.$this->__('Address').' <span class="required">*</span></label><br />
                    '.$addressFields.'
                </div>';
		?>
	<?php endif; ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_country_id']):?>
	<?php
	$addressFieldsIncomplete['country_id'] = '
    <div class="input-box input-country'.((in_array('country', $formErrors)) ? ' input-error' : '').'">
        <label for="billing:country_id">'.$this->__('Country').' <span class="required">*</span></label><br />
            '.$this->getCountryHtmlSelect('billing').'
    </div>';
	?>
<?php else: ?>
	<?php $addressFieldsComplete['country_id'] = '
    <input type="hidden" name="billing[country_id]" id="billing:country_id" value="'.$this->settings['default_country'].'" />';
	?>
<?php endif; ?>
<?php if(!$this->settings['exclude_region']): ?>
	<?php if ($dataHelper->clearDash($address->getRegionId()) == '') :?>
		<?php $show_save_button = true; ?>
		<?php $hide_checkout_button = true; ?>
		<?php $addressFieldsIncomplete['region_id'] = '
					<div class="input-box input-region'.((in_array('region', $formErrors)) ? ' input-error' : '').'">
							<label for="billing:region">'.$this->__('State/Province').' <span class="required">*</span></label><br/>
							<select id="billing:region_id" name="billing[region_id]" title="'.$this->__('State/Province').'" class="validate-select required-entry" style="display:none">
									<option value="">'.$this->__('Please select region, state or province').'</option>
							</select>
							<script type="text/javascript">
									$("billing:region_id").setAttribute("defaultValue",  "'.$dataHelper->clearDash($address->getRegionId()).'");
							</script>
							<input type="text" id="billing:region" name="billing[region]" value="'.$dataHelper->clearDash($address->getRegion()).'"  title="'.$this->__('State/Province').'" class="required-entry input-text" style="display:none" />
					</div>';
		?>
	<?php else : ?>
		<?php $addressFieldsComplete['region_id'] = '';
			//if (in_array('region_id', $showFieldsText))
			//{
				$addressFieldsComplete['region_id'] .= $dataHelper->clearDash($address->getRegion());
			//}
			$addressFieldsComplete['region_id'] .= '<input type="hidden" name="billing[region_id]" value="'.$dataHelper->clearDash($address->getRegionId()).'" />';
		?>
	<?php endif; ?>
<?php endif; ?>
<?php if(!$this->settings['exclude_city']):?>
	<?php if ($dataHelper->clearDash($address->getCity()) == '') :?>
		<?php $show_save_button = true; ?>
		<?php $hide_checkout_button = true; ?>
		<?php $addressFieldsIncomplete['city'] = '
					<div class="input-box input-city'.((in_array('city', $formErrors)) ? ' input-error' : '').'">
							<label for="billing:city">'.$this->__('City').' <span class="required">*</span></label><br/>
							<input type="text" name="billing[city]" value="'.$dataHelper->clearDash($address->getCity()).'" title="'.$this->__('City').'" class="required-entry input-text" id="billing:city" />
					</div>';
		?>
	<?php else : ?>
		<?php
			$addressFieldsComplete['city'] = '';
			//if (in_array('city', $showFieldsText))
			//{
				$addressFieldsComplete['city'] .= $dataHelper->clearDash($address->getCity());
			//}
			$addressFieldsComplete['city'] .= '<input type="hidden" name="billing[city]" value="'.$dataHelper->clearDash($address->getCity()).'" />';
		?>
	<?php endif; ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_zip']): ?>
	<?php if ($dataHelper->clearDash($address->getPostcode()) == '') :?>
		<?php $show_save_button = true; ?>
		<?php $hide_checkout_button = true; ?>
		<?php $addressFieldsIncomplete['postcode'] = '
					<div class="input-box input-postcode'.((in_array('postcode', $formErrors)) ? ' input-error' : '').'" >
							<label for="billing:postcode">'.$this->__('Zip/Postal Code').' <span class="required">*</span></label><br />
							<input type="text" title="'.$this->__('Zip/Postal Code').'" name="billing[postcode]" id="billing:postcode" value="'.$dataHelper->clearDash($address->getPostcode()).'" class="validate-zip-international required-entry input-text mask-zip" />
					</div>';
		?>
	<?php else : ?>
		<?php
			$addressFieldsComplete['postcode'] = '';
			//if (in_array('postcode', $showFieldsText))
			//{
				$addressFieldsComplete['postcode'] .= $dataHelper->clearDash($address->getPostcode());
			//}
			$addressFieldsComplete['postcode'] .= '<input type="hidden" name="billing[postcode]" value="'.$dataHelper->clearDash($address->getPostcode()).'" />';
		?>
	<?php endif; ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_company']): ?>
	<?php $customerFieldsIncomplete['company'] = '
        <div class="input-box input-company'.((in_array('company', $formErrors)) ? ' input-error' : '').'">
            <label for="billing:company">'.$this->__('Company').'</label><br/>
            <input type="text" name="billing[company]" value="'.$dataHelper->clearDash($address->getCompany()).'" title="'.$this->__('Company').'" class="input-text" id="billing:company" />
        </div>';
	?>
<?php endif; ?>

<?php if(!$this->settings['exclude_fax']): ?>
	<?php $customerFieldsIncomplete['fax'] = '
        <div class="input-box input-fax'.((in_array('fax', $formErrors)) ? ' input-error' : '').'">
            <label for="billing:fax">'.$this->__('Fax').'</label><br/>
            <input type="text" name="billing[fax]" value="'.$dataHelper->clearDash($address->getFax()).'" title="'.$this->__('Fax').'" class="input-text" id="billing:fax" />
        </div>';
	?>
<?php endif; ?>

<?php if(!$this->settings['exclude_razao_social'] && $this->getQuote()->getCustomer()->getTipopessoa() == 'PJ'): ?>
	<?php if ($dataHelper->clearDash($customer->getRazaoSocial()) == '') : ?>
		<?php $show_save_button = true; ?>
		<?php $hide_checkout_button = true; ?>
		<?php $customerFieldsIncomplete['razao_social'] = '
					<div class="input-box input-razao_social'.((in_array('razao_social', $formErrors)) ? ' input-error' : '').'">
							<label for="billing:razao_social">'.$this->__('Company Name').'<span class="required">*</span></label><br/>
							<input type="text" name="billing[razao_social]" value="'.$dataHelper->clearDash($customer->getRazaoSocial()).'" title="'.$this->__('Company Name').'" class="input-text required-entry" id="billing:razao_social" />
					</div>';
		?>
	<?php else : ?>
		<?php
			$customerFieldsComplete['razao_social'] = '';
			//if (in_array('razao_social', $showFieldsText))
			//{
				$customerFieldsComplete['razao_social'] .= '<strong>'.$dataHelper->clearDash($customer->getRazaoSocial()).'</strong>';
			//}
			$customerFieldsComplete['razao_social'] .= '<input type="hidden" name="billing[razao_social]" value="'.$dataHelper->clearDash($customer->getRazaoSocial()).'" />';
		?>
	<?php endif; ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_cnpj'] && $this->getQuote()->getCustomer()->getTipopessoa() == 'PJ'): ?>
	<?php if ($dataHelper->clearDash($customer->getCnpj()) == '') : ?>
		<?php $show_save_button = true; ?>
		<?php $hide_checkout_button = true; ?>
		<?php $customerFieldsIncomplete['cnpj'] = '
					<div class="input-box input-cnpj'.((in_array('cnpj', $formErrors)) ? ' input-error' : '').'">
							<label for="billing:cnpj">'.$this->__('CNPJ').'<span class="required">*</span></label><br/>
							<input type="text" name="billing[cnpj]" value="'.$dataHelper->clearDash($customer->getCnpj()).'" title="'.$this->__('CNPJ').'" class="input-text mask-cnpj validate-cnpj" id="billing:cnpj" />
					</div>';
		?>
	<?php else : ?>
		<?php
			$customerFieldsComplete['cnpj'] = '';
			//if (in_array('cnpj', $showFieldsText))
			//{
				$customerFieldsComplete['cnpj'] .= Mage::helper('onestepcheckout')->__('CNPJ').': '.$dataHelper->clearDash($customer->getCnpj());
			//}
			$customerFieldsComplete['cnpj'] .= '<input type="hidden" name="billing[cnpj]" value="'.$dataHelper->clearDash($customer->getCnpj()).'" />';
		?>
	<?php endif; ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_cpf']): ?>
	<?php if ($dataHelper->clearDash($customer->getCpf()) == '') :?>
		<?php $show_save_button = true; ?>
		<?php $hide_checkout_button = true; ?>
		<?php $customerFieldsIncomplete['cpf'] = '
					<div class="input-box input-cpf'.((in_array('cpf', $formErrors)) ? ' input-error' : '').'">
							<label for="billing:cpf">'.$this->__('CPF').'<span class="required">*</span></label><br/>
							<input type="text" name="billing[cpf]" value="'.$dataHelper->clearDash($customer->getCpf()).'" title="'.$this->__('CPF').'" class="input-text mask-cpf validate-cpf" id="billing:cpf" />
					</div>';
		?>
	<?php else : ?>
		<?php
			$customerFieldsComplete['cpf'] = '';
			//if (in_array('cpf', $showFieldsText))
			//{
				$customerFieldsComplete['cpf'] .= Mage::helper('onestepcheckout')->__('CPF').': '.$dataHelper->clearDash($customer->getCpf());
			//}
			$customerFieldsComplete['cpf'] .= '<input type="hidden" name="billing[cpf]" value="'.$dataHelper->clearDash($customer->getCpf()).'" />';
		?>
	<?php endif; ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_inscricao_estadual'] && $this->getQuote()->getCustomer()->getTipopessoa() == 'PJ'): ?>

	<?php if ($dataHelper->clearDash($customer->getInscricaoEstadual()) == '') :?>
		<?php if (!$customer->getInscricaoEstadualIsento()) : ?>
			<?php $show_save_button = true; ?>
			<?php $hide_checkout_button = true; ?>
			<?php $customerFieldsIncomplete['inscricao_estadual'] = '
						<div class="input-box input-inscricao_estadual'.((in_array('inscricao_estadual', $formErrors)) ? ' input-error' : '').'">
								<label for="billing:inscricao_estadual">'.$this->__('Inscrição Estadual').' <span class="required">*</span></label><br/>
								<input type="text" name="billing[inscricao_estadual]" value="'.$dataHelper->clearDash($customer->getInscricaoEstadual()).'" title="'.$this->__('Inscrição Estadual').'" class="input-text required-entry" id="billing:inscricao_estadual" />
						</div>
						<div class="input-box input-short input-inscricao_estadual">
								<input type="checkbox" name="billing[inscricao_estadual_isento]" value="1" id="billing:inscricao_estadual_isento" />
								<label for="billing:inscricao_estadual_isento">'.$this->__('Isento').'</label>
						</div>
						';
			?>
		<?php else: ?>
			<?php
				$customerFieldsComplete['inscricao_estadual'] = '';
				//if (in_array('inscricao_estadual', $showFieldsText))
				//{
					$customerFieldsComplete['inscricao_estadual'] .= Mage::helper('onestepcheckout')->__('Insc. Estadual').': Isento';
				//}
				$customerFieldsComplete['inscricao_estadual'] .= '<input type="hidden" name="billing[inscricao_estadual_isento]" value="'.$dataHelper->clearDash($customer->getInscricaoEstadualIsento()).'" />';
			?>
		<?php endif; ?>
	<?php else : ?>
		<?php
			$customerFieldsComplete['inscricao_estadual'] = '';
			//if (in_array('inscricao_estadual', $showFieldsText))
			//{
				$customerFieldsComplete['inscricao_estadual'] .= Mage::helper('onestepcheckout')->__('Insc. Estadual').': '.$dataHelper->clearDash($customer->getInscricaoEstadual());
			//}
			$customerFieldsComplete['inscricao_estadual'] .= '<input type="hidden" name="billing[inscricao_estadual]" value="'.$dataHelper->clearDash($customer->getInscricaoEstadual()).'" />';
		?>
	<?php endif; ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_bairro']): ?>
	<?php if ($dataHelper->clearDash($address->getBairro()) == '') :?>
		<?php $show_save_button = true; ?>
		<?php $hide_checkout_button = true; ?>
		<?php $addressFieldsIncomplete['bairro'] = '
					<div class="input-box input-bairro'.((in_array('bairro', $formErrors)) ? ' input-error' : '').'">
							<label for="billing:bairro">'.$this->__('District').'<span class="required">*</span></label><br/>
							<input type="text" name="billing[bairro]" value="'.$dataHelper->clearDash($address->getBairro()).'" title="'.$this->__('District').'" class="input-text required-entry" id="billing:bairro" />
					</div>';
		?>
	<?php else : ?>
		<?php
			$addressFieldsComplete['bairro'] = '';
			//if (in_array('bairro', $showFieldsText))
			//{
				$addressFieldsComplete['bairro'] .= $dataHelper->clearDash($address->getBairro());
			//}
			$addressFieldsComplete['bairro'] .= '<input type="hidden" name="billing[bairro]" value="'.$dataHelper->clearDash($address->getBairro()).'" />';
		?>
	<?php endif; ?>
<?php endif; ?>

<?php
$_taxvat = false;
try {
	if(Mage::getStoreConfig('onestepcheckout/exclude_fields/enable_pillwaxeuvat_support')){
		$_taxvat = $this->getLayout()->createBlock('euvat/widget_taxvat');
	}
} catch (Exception $e) {
}
if(!is_object($_taxvat)){
	$_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat');
}
?>
<?php if(is_object($_taxvat) && $_taxvat->isEnabled()  && !$this->isCustomerLoggedIn()): ?>
	<?php $customerFieldsComplete['taxvat'] =
		$_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())
			->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml();
	?>
<?php endif; ?>
<?php if (method_exists(Mage::helper('customer/address'), 'isVatAttributeVisible') && Mage::helper('customer/address')->isVatAttributeVisible()) : ?>
	<?php $customerFieldsIncomplete['taxvat'] = '
            <label for="billing:vat_id">'.$this->__('VAT Number').'</label>
            <div class="input-box">
                <input type="text" id="billing:vat_id" name="billing[vat_id]" value="'.$dataHelper->clearDash($address->getVatId()).'" title="'.$this->__('VAT Number').'" class="input-text '.Mage::helper('customer/address')->getAttributeValidationClass('vat_id').'" />
            </div>';
	?>
<?php endif; ?>
<?php
try {
	$_dob = $this->getLayout()->createBlock('customer/widget_dob');
} catch (Exception $e) {
	$_dob = false;
}
?>
<?php
try {
	$_gender = $this->getLayout()->createBlock('customer/widget_gender');
} catch (Exception $e) {
	$_gender = false;
}
?>

<?php if (is_object($_dob) && $_dob->isEnabled() && !$this->isCustomerLoggedIn()): ?>
	<?php $customerFieldsIncomplete['dob'] = '
        <div class="field">
            '.$_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml().'
        </div>';
	?>
<?php endif; ?>
<?php if (is_object($_gender) && $_gender->isEnabled() && !$this->isCustomerLoggedIn()): ?>
	<?php $customerFieldsIncomplete['gender'] = '
        <div class="field">
            '.$_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml().'
        </div>';
	?>
<?php endif ?>
<?php if(!$this->isCustomerLoggedIn() && $helper->showCreateAccount()): ?>
	<?php $customerFieldsIncomplete['create_account'] = '
        <div class="input-box">
            <input id="id_create_account" type="checkbox" name="create_account" value="1" '.((isset($_POST['create_account']) && $_POST['create_account'] == '1') ? ' checked="checked"' : '').' />
            <label for="id_create_account">'.$this->__('Create an account for later use').'</label>
        </div>

        <script>
        document.observe("dom:loaded", function() {
            $("id_create_account").observe("click", function(e) {
                var element = e.element();
                if(element.checked) {
                    $("onestepcheckout-li-password").show();
                }
                else    {
                    $("onestepcheckout-li-password").hide();
                }
            });
        });
        </script>';
	?>
<?php endif; ?>
<?php if($helper->showPasswords() && !$this->isCustomerLoggedIn()): ?>
	<?php
	//id="onestepcheckout-li-password"
	$customerFieldsIncomplete['password'] = '
        <li id="onestepcheckout-li-password" '.(($helper->hidePasswords()) ? 'style="display: none;"':'').'>
            <div class="input-box input-password'.((in_array('password', $formErrors)) ? ' input-error' : '').'">
                <label for="billing:customer_password">'.$this->__('Password').'</label><br/>
                <input type="password" class="input-text required-entry validate-password" value="'.((isset($_POST['billing']['customer_password'])) ? Mage::helper('core')->escapeHtml($_POST['billing']['customer_password']) : '').'" title="Password" id="billing:customer_password" name="billing[customer_password]"/>
            </div>
            <div class="input-box input-password'.((in_array('confirm_password', $formErrors)) ? ' input-error' : '').'">
                <label for="billing:confirm_password">'.$this->__('Confirm password').'</label><br/>
                <input type="password" class="input-text required-entry validate-cpassword" value="'.((isset($_POST['billing']['confirm_password'])) ? Mage::helper('core')->escapeHtml($_POST['billing']['confirm_password']) : '').'" id="billing:confirm_password" title="Confirm Password" name="billing[confirm_password]"/>
            </div>
        </li>';
	?>
<?php endif; ?>
<?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses() && !$this->settings['exclude_saveaddress']):?>
	<?php $addressFieldsIncomplete['save_in_address_book'] = '
        <li class="control">
            <input type="checkbox" name="billing[save_in_address_book]" value="1" title="'.$this->__('Save in address book').'" id="billing:save_in_address_book" onchange="shipping.setSameAsBilling(false);"'.(($dataHelper->clearDash($address->getSaveInAddressBook())) ? 'checked="checked"':'').' class="checkbox" /><label for="billing:save_in_address_book">'.$this->__('Save in address book').'</label>
        </li>';
	?>
	<?php else :?>
    <?php $addressFieldsComplete['save_in_address_book'] = '
        <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>';
    ?>
<?php endif; ?>

<?php if ($this->settings['single_address']) : ?>
	<input type="hidden" id="billing_address_id" name="billing_address_id" value="<?php echo $address->getId(); ?>" />
	<input type="hidden" id="billing_identification" name="billing[identification]" value="Padrão" />
<?php endif; ?>

<div class="customer-fields">
	<ul>
		<?php $customerFieldsComplete = $this->getBillingFieldsOrder($customerFieldsComplete);?>
		<?php foreach($customerFieldsComplete as $key => $value):?>
				<?php if(!empty($value['has_li'])):?>
					<?php echo implode('',$value['fields']);?>
					<?php if ($key == 1) : ?>
						<?php if ($show_save_button) : ?>
							<br />
							<small><a href="javascript://" onclick="showIncompleteBillingBox(this)"><?php echo $this->__('(Seu cadastro está incompleto! Clique aqui)'); ?></a></small>
							<br />
						<?php endif; ?>
					<?php endif; ?>
				<?php else:?>
					<li class="clearfix">
						<?php echo implode('&nbsp;',$value['fields']);?>
						<?php if ($key == 1) : ?>
							<?php if ($show_save_button) : ?>
								<br />
								<small><a href="javascript://" onclick="showIncompleteBillingBox(this)"><?php echo $this->__('(Seu cadastro está incompleto! Clique aqui)'); ?></a></small>
								<br />
							<?php endif; ?>
						<?php endif; ?>
					</li>
				<?php endif;?>
		<?php endforeach;?>
	</ul>
</div>

<div class="address-fields">
	<ul>
		<?php $addressFieldsComplete = $this->getBillingFieldsOrder($addressFieldsComplete);?>
		<?php foreach($addressFieldsComplete as $key => $value):?>
			<?php if(!empty($value['has_li'])):?>
				<?php echo implode('',$value['fields']);?>
			<?php else:?>
				<li class="clearfix"><?php echo implode('',$value['fields']);?></li>
			<?php endif;?>
		<?php endforeach;?>
	</ul>
</div>


<?php if (count($addressFieldsIncomplete) > 0 || count($customerFieldsIncomplete) > 0) : ?>
	<div class="box-incomplete">
		<div class="container">
			<ul>
				<li class="box-incomplete-title">Por favor, complete alguns dados que estão faltando:</li>
				<li><br /></li>

				<?php $customerFieldsIncomplete = $this->getBillingFieldsOrder($customerFieldsIncomplete);?>
				<?php foreach($customerFieldsIncomplete as $key => $value):?>
					<?php if(!empty($value['has_li'])):?>
						<?php echo implode('',$value['fields']);?>
					<?php else:?>
						<li class="clearfix"><?php echo implode('',$value['fields']);?></li>
					<?php endif;?>
					<li class="clearfix"><br /></li>
				<?php endforeach;?>

				<?php $addressFieldsIncomplete = $this->getBillingFieldsOrder($addressFieldsIncomplete);?>
				<?php foreach($addressFieldsIncomplete as $key => $value):?>
					<?php if(!empty($value['has_li'])):?>
						<?php echo implode('',$value['fields']);?>
					<?php else:?>
						<li class="clearfix"><?php echo implode('',$value['fields']);?></li>
					<?php endif;?>
					<li class="clearfix"><br /></li>
				<?php endforeach;?>
				<li>
					<button id="billing:save_billing" type="button" onclick="save_billing_trigger()" class="button btn-doToAction saveBillingButton"><span><span>Salvar informações</span></span></button>
				</li>
			</ul>
		</div>
	</div>
<?php endif; ?>






<?php if ($show_save_button) : ?>
	<script>
		function showIncompleteBillingBox(hidden)
		{
			jQuery('.box-incomplete').slideDown(500);
			jQuery(hidden).slideUp(250);
		}
	</script>
<?php endif; ?>


<?php if($hide_checkout_button) : ?>
	<script>
		jQuery(document).ready(function() {
			bindMasks();
		});
	</script>
<?php else : ?>
	<script>
		jQuery(document).ready(function() {
			jQuery("#onestepcheckout-place-order").css({'opacity':'1'});
		});
	</script>
<?php endif; ?>