
<div style="background-image: url(<?php echo $this->getSkinUrl('images/institutional/nossa_proposta/0.jpg'); ?>)" class="category-image">
	<div class="page-title category-title">
		<div class="inner">
			<h1>A nossa proposta</h1>
			<p class="subtitle">Ser uma grande empresa que cria valor excepcional de longo prazo para nossos clientes, funcionários e acionistas, melhorando a saúde e o bem-estar dos animais e das pessoas.</p>
		</div>
	</div>
</div>

<p>&nbsp;</p>
<p>&nbsp;</p>

<div class="default-page-width">

	<h1>Princ&iacute;pios</h1>
	<p>&nbsp;</p>
	<p>&nbsp;</p>

	<div class="block-info">
		<h3>Alcan&ccedil;ar e manter a lideran&ccedil;a de mercado</h3>
		<br>
		<img title="Alcan&ccedil;ar e manter a lideran&ccedil;a do mercado" alt="Alcan&ccedil;ar e manter a lideran&ccedil;a do mercado" src="<?php echo $this->getSkinUrl('images/institutional/nossa_proposta/1.jpg'); ?>" width="307" height="168" />
		<br><br>
		<p>Combinamos um intenso desejo de ter sucesso com a paixão para ser líder nos nossos mercados.<br/>Alcançamos o excepcional e sustentável sucesso financeiro através da criação de valor para os nossos clientes e funcionários em todo o mundo.</p>
	</div>

	<div class="block-info">
		<h3>Exceder as expectativas de nossos clientes</h3>
		<br>
		<img title="Exceder as expectativas de nossos clientes" alt="Exceder as expectativas de nossos clientes" src="<?php echo $this->getSkinUrl('images/institutional/nossa_proposta/2.jpg'); ?>" width="307" height="168" />
		<br><br>
		<p>Colocamos as necessidades de nossos clientes no centro de todas as nossas atividades através de serviço de alta qualidade.<br />Ouvimos e interagimos com nossos clientes constantemente para construir parcerias duradouras e mutuamente rentáveis.</p>
	</div>

	<div class="block-info">
		<h3>Capacitar e recompensar nossos funcion&aacute;rios</h3>
		<br>
		<img title="Capacitar e recompensar nossos funcion&aacute;rios" alt="Capacitar e recompensar nossos funcion&aacute;rios" src="<?php echo $this->getSkinUrl('images/institutional/nossa_proposta/3.jpg'); ?>" width="307" height="168" />
		<br><br>
		<p>Tratamos uns aos outros com confiança, respeito e honestidade, dedicando grande importância em acessibilidade, colaboração, comunicação aberta, tomada de decisão clara e responsabilidade individual. Nós fornecemos aos nossos funcionários diversas oportunidades de aprender, contribuir e se beneficiarem, baseados em seus méritos, resultados e valores.</p>
	</div>

	<div class="block-info">
		<h3>Inovar com intelig&ecirc;ncia</h3>
		<br>
		<img title="Inovar com intelig&ecirc;ncia" alt="Inovar com intelig&ecirc;ncia" src="<?php echo $this->getSkinUrl('images/institutional/nossa_proposta/4.jpg'); ?>" width="307" height="168" />
		<br><br>
		<p>Antecipamos as necessidades dos nossos clientes e fornecemos produtos e serviços simples e intuitivos com a mais alta qualidade. Buscamos inspiração interna e externamente, e temos a flexibilidade e a visão de incorporar as melhores ideias e tecnologias a partir de qualquer fonte.</p>
	</div>

	<div class="block-info">
		<h3>Cultivar o esp&iacute;rito empreendedor</h3>
		<br>
		<img title="Cultivar o esp&iacute;rito empreendedor" alt="Cultivar o esp&iacute;rito empreendedor" src="<?php echo $this->getSkinUrl('images/institutional/nossa_proposta/5.jpg'); ?>" width="307" height="168" />
		<br><br>
		<p>Somos bem-sucedidos através de um senso comum de urgência e da nossa capacidade de reconhecer e aproveitar novas oportunidades em nossos mercados. Incentivamos a iniciativa e a criatividade combinados com o compromisso de um planejamento cuidadoso e uma execução disciplinada.</p>
	</div>

	<div class="block-info">
		<h3>Contribuir para nossas comunidades</h3>
		<br>
		<img title="Contribuir para nossas comunidades" alt="Contribuir para nossas comunidades" src="<?php echo $this->getSkinUrl('images/institutional/nossa_proposta/6.jpg'); ?>" width="307" height="168" />
		<br><br>
		<p>Conduzimos nossos negócios com os mais altos padrões éticos, com respeito às leis, bem como a compreensão das nossas responsabilidades ambientais.<br />Somos cidadãos das comunidades nas quais fazemos negócios, e contribuimos para a saúde e a qualidade de vida dessas comunidades.</p>
	</div>
</div>