<br />
<script>
	var showRegions = new Array();
</script>
<div class="salesreps-list">

	<div>
		<strong><?php echo $this->__('Find a salesrep for your region'); ?></strong> <?php echo $this->getChildHtml('selector'); ?>
	</div>

	<br />
	<hr />
	<br />

	<div class="tabs-content2">
		<div id="product-vendors-contents">
			<table id="product-vendors-table" class="data-table" >
				<tbody>
				<?php foreach ($this->getSalesreps() as $salesrep) : ?>
					<?php $salesrepRegion = $salesrep->getSelectedRegions(); ?>
					<script>
					<?php foreach ($salesrepRegion as $region) : ?>
						showRegions.push('<?php echo $region->getCode(); ?>');
					<?php endforeach; ?>
					</script>
					<tr id="product_vendors_row" class="vendor <?php foreach ($salesrepRegion as $region) : echo $region->getCode() . ' '; endforeach; ?>">
						<?php /*
						<td class="first">
							<div class="seller-image">
								<img src="<?php echo $this->helper('fvets_salesrep')->getImageUrl($salesrep); ?>" width="100" height="100" />
							</div>
						</td>
 						*/ ?>
						<td>
							<div class="seller-info">
								<?php echo strtoupper($salesrep->getName()); ?>
								<?php /*<br />
								Campo a desenvolver para incluir endereço do representante.*/ ?>
								<br />
								Tel: <?php echo $salesrep->getTelephone(); ?>
								<br />
								Email: <?php echo $salesrep->getEmail(); ?>
							</div>
						</td>
					</tr>
				<?php endforeach; ?>
				<tr class="no-salesrep-available" style="display: none;">
					<th colspan="3">
						<?php echo $this->__('Nenhum representante disponível'); ?>
					</th>
				</tr>
				</tbody>
			</table>
		</div>
	</div>
	<style>
		#product-vendors-table tr {
			display:none;
		}
		<?php if (Mage::getModel('core/cookie')->get('customer-region')) : ?>
		#product-vendors-table .<?php echo Mage::getModel('core/cookie')->get('customer-region'); ?> {
			display: table-row;
		}
		<?php endif; ?>
	</style>

	<script>
		jQuery(document).ready(function() {
			<?php if($this->getSalesreps()->count() == 0) : ?>
				jQuery('#product-vendors-table tr').hide();
				jQuery('#product-vendors-table tr.no-salesrep-available').show();
			<?php endif; ?>
			<?php if (Mage::getModel('core/cookie')->get('customer-region')) : ?>
				if (jQuery('#product-vendors-table .<?php echo Mage::getModel('core/cookie')->get('customer-region'); ?>').size() <= 0)
				{
					jQuery('#product-vendors-table tr').hide();
					jQuery('#product-vendors-table tr.no-salesrep-available').show();
				}
			<?php endif; ?>
		});
	</script>
</div>