<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
$_productCollection=$this->getLoadedProductCollection();

//adicionando ao select o atributo id_erp
//$_productCollection->addAttributeToSelect('id_erp', true);
//echo $_productCollection->getSelect()->__toString();

$_helper = $this->helper('catalog/output');
$_customer = Mage::getSingleton('customer/session');
?>
<hr class="hundred" />
<?php if(!$_productCollection->count()): ?>
	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
	<div class="category-products">
		<?php // List mode ?>
<!--		verifica se existe o bloco onepagecatalog e se tem um modo setado pra ele-->
		<?php if($this->getMode()!='grid' || ($this->getOnePageCatalogMode() && $this->getOnePageCatalogMode() != 'grid')): ?>
			<?php $_iterator = 0; ?>
			<?php
			$_cookieFlagImgs = Mage::helper("page")->showImgs();
			?>

			<ol class="products-list" id="products-list">
				<?php foreach ($_productCollection as $_product): ?>
					<li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">

						<?php // Product description ?>
						<div class="product-shop">
							<?php // Product Image ?>
							<div <?php echo (isset($_cookieFlagImgs) && $_cookieFlagImgs == 1 ? "class='prolabel-wrapper no-image'" : "class='prolabel-wrapper'") ?>>
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img class="lazy" data-original="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(60); ?>" width="60" height="60" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
							</div>
							<?php if (Mage::helper('core')->isModuleOutputEnabled('TM_QuickShopping')) : ?>
								<?php echo Mage::helper('quickshopping')->getViewButton($this->__('Quick View'), $_product, $this->getMode(), null, $_productCollection); ?>
							<?php endif ?>
							<div class="f-fix">
								<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
								<div class="product-name-container">
									<?php $idErp = $_product->getIdErp(); ?>
									<?php $productName = $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>
									<?php $lenghtProductName = strlen($productName); ?>
									<?php if ($lenghtProductName > 44) {
										$productName = (substr($productName, 0, 20) . ' ... ' . substr($productName, $lenghtProductName - 20));
									} ?>
									<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $productName . ' <strong>(Cód. ' . (isset($idErp) ? $idErp : $_product->getSku()) . ')</strong>'; ?></a></h2>
								</div>

								<?php echo Mage::helper('fvets_salesrule')->getLabelHtml($_product) ?>

								<?php if($_product->getRatingSummary()): ?>
									<?php echo $this->getReviewsSummaryHtml($_product) ?>
								<?php endif; ?>
								<?php if ($_customer->isLoggedIn()) : ?>
									<?php echo $this->getPriceHtml($_product, true) ?>
								<?php endif; ?>

								<div class="desc std">
									<div class="short-description">
										<?php $_shortDescription = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'); ?>
										<?php //if (strlen($_shortDescription) > 50) {
										//echo (substr(strip_tags($_shortDescription), 0, 50))." ...";
										//} else {
										echo strip_tags($_shortDescription);
										//} ?>
									</div>
									<div class="link-see-more">
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Veja Mais') ?></a>
									</div>
								</div>
								<?php echo Mage::helper('facebooklb')->getCategoryLikeButton($_product) ?>
							</div>
							<?php if(Mage::helper('privatesales')->canShowPricesAndAddToCartButton()) { ?>
							<?php if ($_customer->isLoggedIn()) : ?>
								<?php if($_product->isSaleable()): ?>

									<div class="form-container">
										<form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId()?>"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

											<div class="btnAddCart"><p><button id="btn-<?php echo $_product->getId(); ?>" type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="addToCart('<?php echo $this->getAddToCartUrl($_product) ?>', <?php echo $_product->getId(); ?>)"><span><span><?php echo $this->__('Add to Shopping Cart') ?></span></span></button></p></div>
											<?php //if(!$_product->isGrouped()): ?>
											<div class="divQtd">
												<!--														<label for="qty">--><?php //echo $this->__('Qty') ?><!--:</label>-->
												<input type='button' value='-' class='qtyminus' field='qty-<?php echo $_product->getId(); ?>' />
												<input type='text' name='quantity' value='1' class='qty' id="qty-<?php echo $_product->getId(); ?>"/>
												<input type='button' value='+' class='qtyplus' field='qty-<?php echo $_product->getId(); ?>' />
											</div>

											<?php //endif; ?>

										</form>
									</div>

								<?php else: ?>
									<?php if ($_product->getIsSalable()): ?>
										<p class="availability in-stock"><span><?php echo $this->__('In stock') ?></span></p>
									<?php else: ?>
										<?php if ($_product->getIsSalable()): ?>
											<p class="availability in-stock"><span><?php echo $this->__('In stock') ?></span></p>
										<?php else: ?>
											<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
										<?php endif; ?>
									<?php endif; ?>
								<?php endif; ?>
							<?php endif; ?>

							<?php } ?>
						</div>
					</li>
				<?php endforeach; ?>
			</ol>
			<script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

		<?php else: ?>

		<?php // Grid Mode ?>

		<?php $_collectionSize = $_productCollection->count() ?>
		<?php $_columnCount = $this->getColumnCount(); ?>
		<?php $i=0; foreach ($_productCollection as $_product): ?>
		<?php if ($i++%$_columnCount==0): ?>
			<ul class="products-grid cols-<?php echo $_columnCount ?>">
		<?php endif;

			$productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
			if (strlen($productName) > 52) {
				$productName = substr($productName, 0, 52) . '...';
			}

			?>
			<li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
				<h5 class="product-name"><a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $productName ?></a></h5>
				<div>
					Cód: <?php echo (($_product->getIdErp()) ? $_product->getIdErp() : $_product->getSku()); ?>
				</div>
				<div class="prolabel-wrapper">

					<?php echo Mage::helper('fvets_salesrule')->getLabelHtml($_product) ?>

					<a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200); ?>" width="200" height="200" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
				</div>

				<div>
					<a class="featured" href="<?php echo $this->getProductUrl($_product) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->__('See details'); ?> ></a>
				</div>
				<?php if($_product->getRatingSummary()): ?>
					<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
				<?php endif; ?>
				<?php if ($_customer->isLoggedIn()) : ?>
				<?php echo $this->getPriceHtml($_product, true, $this->getPriceSuffix()) ?>
				<div class="clear"></div>
					<div class="actions">
						<?php if($_product->isSaleable()): ?>
							<div class="divQtd">
								<label for="qty" class="qtyLabel"><?php echo $this->__('Qty') ?></label>
								<div class="qtyButtons">
									<input type='button' value='-' class='qtyminus' field='qty-<?php echo $_product->getId(); ?>' />
									<input type='text' name='quantity' value='1' class='qty' id="qty-<?php echo $_product->getId(); ?>"/>
									<input type='button' value='+' class='qtyplus' field='qty-<?php echo $_product->getId(); ?>' />
								</div>
								<div class="clear"></div>
							</div>
							<div class="clear"></div>
							<div>
								<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="addToCart('<?php echo $this->getAddToCartUrl($_product) ?>', <?php echo $_product->getId(); ?>)"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
							</div>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
					</div>
				<?php endif; ?>
			</li>
			<?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
			</ul>
		<?php endif ?>
		<?php endforeach ?>
			<div class="clearer"></div>
			<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
		<?php endif; ?>
	</div>
<?php endif; ?>
