<?php

/**
 * Widget Slider
 */
/*$widget = Mage::getModel('widget/widget_instance')->load($this->getFirstBannerId());
$widgetSlider = $this
	->getLayout()
	->createBlock($widget->getType(),
		$widget->getTitle(),
		$widget->getWidgetParameters());*/

$componentSlider = $this
	->getLayout()
	->createBlock('easyslide/insert', 'slider', array('slider_id' => $this->getSliderName()));

$componentMiniBanners = $this
	->getLayout()
	->createBlock('easybanner/widget_placeholder', 'banners', array('placeholder_name' => 'loggedout_homepage_minibanners'));
?>
<div class="callout-home-top col2-set">
	<?php if (is_object($componentSlider)): ?>
		<div class="col-1"><?php echo $componentSlider->toHtml(); ?></div>
	<?php endif; ?>
	<?php if (is_object($componentMiniBanners)): ?>
		<div class="col-2"><?php echo $componentMiniBanners->toHtml(); ?></div>
	<?php endif; ?>
</div>