<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<form id="respond" method="post" action="<?php echo $this->getCommentFormAction() ?>">
	<div class="display-none">
		<input type="hidden" name="comment_post_ID" value="<?php echo $this->getPostId() ?>"/>
		<input type="hidden" name="comment_parent" id="comment_parent" value="<?php echo (int)$this->getRequest()->getParam('replytocom', 0) ?>"/>
	</div>
	<div class="fieldset row">
		<h1 class="block-title"><?php echo $this->__('Comentários') ?> (<?php echo ($this->getCommentCount() > 0) ? $this->getCommentCount() :  0; ?>)</h1>
		<div class="row">
			<div class="col-md-12">
				<?php if ($this->customerMustLogin()): ?>
					<p><?php echo $this->__('Sorry, you must be logged in to post a comment.') ?></p>
					<p><button class="button btn-login" type="button" onclick="setLocation('<?php echo $this->getLoginLink() ?>');"><span><span><?php echo $this->__('Login') ?></span></span></button></p>
				<?php else: ?>
					<ul class="comment-form-list">
						<?php if (!$this->isCustomerLoggedIn()): ?>
							<li class="fields">
								<div class="field">
									<label for="author" class="required"><?php echo $this->__('Name') ?> <em>*</em></label>
									<div class="input-box">
										<input type="text" id="author" name="author" class="form-control required-entry" value=""/>
									</div>
								</div>
								<div class="field">
									<label for="email" class="required"><?php echo $this->__('Email') ?> <em>*</em></label>
									<div class="input-box">
										<input type="text" id="email" name="email" class="form-control required-entry validate-email" value=""/>
									</div>
								</div>
							</li>
						<?php endif; ?>
						<?php /*<li>
							<label for="url"><?php echo $this->__('Website') ?></label>
							<div class="input-box">
								<input type="text" id="url" name="url" class="form-control" value="" style="width:95%;"/>
							</div>
						</li>*/ ?>
						<li class="wide row">
							<?php /*<label for="comment" class="required"><?php echo $this->__('Comment') ?> <em>*</em></label>*/ ?>
							<div class="input-box col-md-10">
								<textarea id="comment" name="comment" rows="1" class="required-entry wide"></textarea>
							</div>
							<div class="input-box col-md-2">
								<?php if (!$this->customerMustLogin()): ?>
									<div class="buttons-set">
										<button type="submit" name="submit"  class="button btn btn-success" value="Post your comment" id="post-the-comment"><span><span><?php echo $this->__('Publicar') ?></span></span></button>
										<span class="please-wait" id="respond-please-wait" style="display:none;">
											<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Please wait...') ?>" class="v-middle" /> <?php echo $this->__('Please wait...') ?>
										</span>
									</div>
									<script type="text/javascript">
									//<![CDATA[
										new fishpig.WP.Comments.Form('respond', '<?php echo $this->getPost()->getPermalink() ?>');
									//]]>
									</script>
								<?php endif; ?>
							</div>
						</li>
						<?php echo $this->getChildHtml('before_form_end') ?>
					</ul>
				<?php endif; ?>
			</div>
		</div>
	</div>
</form>