<?php
    $_productCollection = $this->getLoadedProductCollection();
	if (!$_productCollection)
	{
		$_productCollection = $this->getProductCollection();
	}
    $_helper            = $this->helper('catalog/output');
    $_collectionSize    = $_productCollection->count();
	$_count				= 0;
	$_customer			= Mage::getSingleton('customer/session');
?>
<?php if (!$_collectionSize) : return; endif; ?>

<div class="carousel-products <?php echo $this->getClassName() ?>">
    <h1 class="block-title"><span><?php echo $this->__($this->getTitle()) ?></span></h1>
	<div class="block-content">
		<div class="jcarousel">
			<ul class="products-grid">
			<?php $i=0; foreach ($_productCollection as $_product): ?>
				<?php $_count++; ?>
				<li class="item<?php if($_count==1): ?> first<?php elseif($_count==$_collectionSize): ?> last<?php endif; ?>">
					<h5 class="product-name"><a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h5>
					<div>
						<?php $idErp = $_product->getIdErp(); ?>
						Cód: <?php echo (isset($idErp) ? $idErp : $_product->getSku()); ?>
					</div>
					<div class="prolabel-wrapper">

						<?php echo Mage::helper('fvets_salesrule')->getLabelHtml($_product) ?>

						<a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200); ?>" width="200" height="200" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
					</div>
					<?php echo $this->getLayout()->createBlock('prolabels/category')->setProduct($_product)->toHtml(); ?>
					<div>
						<a class="featured" href="<?php echo $this->getProductUrl($_product) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->__('See details'); ?> ></a>
					</div>
					<div class="product-details-container">
						<?php if ($_product->getQtyIncrements() && $_product->getQtyIncrements() > 1) : ?>
							<div class="increment-message">
								<?php echo $this->__('disponível somente em múltiplos de '); ?><?php echo $_product->getQtyIncrements(); ?> (<?php echo $_product->getQtyIncrements(); ?>, <?php echo $_product->getQtyIncrements() * 2; ?>, <?php echo $_product->getQtyIncrements() * 3; ?>...)
							</div>
							<div class="clear"></div>
						<?php endif; ?>
					</div>

					<?php if($_product->getRatingSummary()): ?>
					<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
					<?php endif; ?>
					<?php if ($_customer->isLoggedIn()): ?>
					<?php echo $this->getPriceHtml($_product, true, $this->getPriceSuffix()) ?>

					<div class="clear"></div>
						<div class="actions">
							<?php if($_product->isSaleable()): ?>
								<div class="divQtd">
									<label for="qty" class="qtyLabel"><?php echo $this->__('Qty') ?></label>
									<div class="qtyButtons">
										<?php $increments = ($_product->getQtyIncrements()) ? $_product->getQtyIncrements() : 1; ?>
										<?php
										$_hasCustomOptions = $_product->getTypeInstance(true)->hasRequiredOptions($_product);
										if ($_hasCustomOptions) { 	?>
											<?php
												$optionsData = Mage::helper('fvets_catalog')->renderPresentationAttributeOptionFields($_product);
												if(isset($optionsData['increments'])) {
													$increments = $optionsData['increments'];
												}
												echo $optionsData['html'];
											?>
										<?php } ?>
										<input type='button' value='-' class='qtyminus' field='qty-<?php echo $_product->getId(); ?>' title="<?php if ($_product->getQtyIncrements() && $_product->getQtyIncrements() > 1) : ?><?php echo $this->__('disponível somente em múltiplos de '); ?> <?php echo $_product->getQtyIncrements(); ?> (<?php echo $_product->getQtyIncrements(); ?>, <?php echo $_product->getQtyIncrements() * 2; ?>, <?php echo $_product->getQtyIncrements() * 3; ?>...)<?php endif; ?>" />
										<input type='text' name='quantity' value='<?php echo $increments; ?>' data-increments="<?php echo $increments; ?>" class='qty' id="qty-<?php echo $_product->getId(); ?>"/>
										<input type='button' value='+' class='qtyplus' field='qty-<?php echo $_product->getId(); ?>' title="<?php if ($_product->getQtyIncrements() && $_product->getQtyIncrements() > 1) : ?><?php echo $this->__('disponível somente em múltiplos de '); ?> <?php echo $_product->getQtyIncrements(); ?> (<?php echo $_product->getQtyIncrements(); ?>, <?php echo $_product->getQtyIncrements() * 2; ?>, <?php echo $_product->getQtyIncrements() * 3; ?>...)<?php endif; ?>" />
									</div>
									<div class="clear"></div>
								</div>
								<div class="clear"></div>
								<div>
									<button type="button" title="<?php echo $this->__('Add to Shopping Cart') ?>" class="button btn-cart" onclick="addToCart('<?php echo $this->getAjaxAddToCartUrl($_product) ?>', <?php echo $_product->getId(); ?>)"><span><span><?php echo $this->__('Add to Shopping Cart') ?></span></span></button>
								</div>

							<?php else: ?>
								<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
							<?php endif; ?>
						</div>
					<?php endif; ?>
				</li>
			<?php endforeach ?>
			</ul>
			<div class="clearer"></div>
			<?php
				$highlightClasses = array('TM_Highlight_Block_Product_New',
																	'TM_Highlight_Block_Product_Popular',
																	'TM_Highlight_Block_Product_Featured',
																	'TM_Highlight_Block_Product_Bestseller');

				$currentClassName = get_class($this);

			if (in_array($currentClassName, $highlightClasses))
			{
				?>
				<div class="bottom-links">
					<a
						href="<?php echo rtrim($this->getUrl($this->getAllLink()), '/') ?>"><?php echo $this->getAllTitle() ?> &raquo;</a>
				</div>
			<?php } ?>
			<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
		</div>
		<!-- Prev/next controls -->
		<a href="#" class="jcarousel-control-prev"><i class="fa fa-chevron-left fa-5x"></i></a>
		<a href="#" class="jcarousel-control-next"><i class="fa fa-chevron-right fa-5x"></i></a>
	</div>
</div>