<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FVets
 * @package    FVets_CustomGrid
 * @copyright  Copyright (c) 2014 Carlos Farah <carlos.farah@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if (!$this->getDescriptionsOutput()): ?>
    <?php $this->_setDescriptionsOutput(true) ?>
    <div id="fvetscg-collection-renderers-descriptions" style="display: none;">
        <div class="fvetscg-content-header">
            <h3 class="icon-head head-adminhtml"><?php echo $this->__('Columns Types Descriptions') ?></h3>
        </div>
        <dl class="fvetscg-collection-renderers-descriptions-list">
        <?php foreach ($this->_getAvailableRenderers() as $_renderer): ?>
            <dt><?php echo $this->htmlEscape($_renderer['name']) ?></dt>
            <dd><?php if ($_renderer['description'] != ''): ?><?php echo $this->htmlEscape($_renderer['description']) ?><?php else: ?><?php echo $this->__('No Description') ?><?php endif ?></dd>
        <?php endforeach ?>
        </dl>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        function fvetscgDisplayCollectionRenderersHelp()
        {
            fvetscg.Tools.openDialogFromElement('fvetscg-collection-renderers-descriptions', {title: '<?php echo $this->jsQuoteEscape($this->__('Help')) ?>'});
        }
    //]]>
    </script>
<?php endif ?>