<?php
$block_data = $this->getBlockData();
$banners = $block_data['banners'];

if (count($banners) >= 3) :

?>

	<div class="row">
		<div class="col-md-4">
			<a href="<?php echo $banners[0]['click_url']; ?>" target="<?php echo $banners[0]['tartget']; ?>'">
				<?php list($width, $height, $type, $attr) = getimagesize($this->getBannerImage($banners[0]['image'])); ?>
				<img class="lazy" data-original="<?php echo $this->getBannerImage($banners[0]['image']); ?>" alt="<?php echo $banners[0]['image_alt']; ?>" <?php echo $attr; ?> />
				<?php if ($this->getRequest()->getModuleName() != 'cms' || $this->getRequest()->getActionName() != 'index'): ?>
					<h2><?php echo $banners[0]['name']; ?></h2>
				<?php endif;?>
			</a>
		</div>
		<div class="col-md-4">
			<a href="<?php echo $banners[1]['click_url']; ?>" target="<?php echo $banners[1]['tartget']; ?>'">
				<?php list($width, $height, $type, $attr) = getimagesize($this->getBannerImage($banners[1]['image'])); ?>
				<img class="lazy" data-original="<?php echo $this->getBannerImage($banners[1]['image']); ?>" alt="<?php echo $banners[1]['image_alt']; ?>" <?php echo $attr; ?> />
				<?php if ($this->getRequest()->getModuleName() != 'cms' || $this->getRequest()->getActionName() != 'index'): ?>
					<h2><?php echo $banners[1]['name']; ?></h2>
				<?php endif;?>
			</a>
		</div>
		<div class="col-md-4">
			<a href="<?php echo $banners[2]['click_url']; ?>" target="<?php echo $banners[2]['tartget']; ?>'">
				<?php list($width, $height, $type, $attr) = getimagesize($this->getBannerImage($banners[2]['image'])); ?>
				<img class="lazy" data-original="<?php echo $this->getBannerImage($banners[2]['image']); ?>" alt="<?php echo $banners[2]['image_alt']; ?>" <?php echo $attr; ?> />
				<?php if ($this->getRequest()->getModuleName() != 'cms' || $this->getRequest()->getActionName() != 'index'): ?>
					<h2><?php echo $banners[0]['name']; ?></h2>
				<?php endif;?>
			</a>
		</div>
	</div>

	<div class="clear"></div>
	<br />
	<div class="clear"></div>

<?php endif; ?>