<?php
	$_fvetsCoreHelper = Mage::helper('fvets_core');
	$validateCnpjUrl = Mage::getUrl('customer/account/validatecnpj', array('_secure' => true));
	$validateCpfUrl = Mage::getUrl('customer/account/validatecpf', array('_secure' => true));

	$areaInterestOptions = Mage::getSingleton('fvets_customer/eav_entity_attribute_source_areainterest')->getOptionArray();
?>


<div class="account-create">
<h1><?php echo $this->__('Create an Account') ?></h1>
<h6>* Para Veterinários, Clínicas Veterinárias, Pet Shops, Criadores, Lojas Agropecuárias e afins.</h6><br>

<div class="hundred">
	<hr />
</div>
<br />

<?php echo $this->getChildHtml('form_fields_before')?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
<div class="fieldset">
	<input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
	<input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
	<h4 class="legend"><?php echo $this->__('Personal Information') ?></h4>
	<ul class="form-list">
		<li class="control">
			<div class="input-box">
				<input type="radio" class="validate-one-required-by-name" name="tipopessoa" value="PF" id="tipopessoapf" <?php echo ($this->getFormData()->getTipopessoa() == 'PF' ? 'checked="checked"' : ''); ?>/>
			</div>
			<label for="tipopessoapf"><?php echo $this->__('Pessoa física'); ?></label>
			<div class="input-box">
				<input type="radio" class="validate-one-required-by-name" name="tipopessoa" value="PJ" id="tipopessoapj" <?php echo ($this->getFormData()->getTipopessoa() == 'PJ' ? 'checked="checked"' : ''); ?>/>
			</div>
			<label for="tipopessoapj"><?php echo $this->__('Pessoa jurídica'); ?></label>
		</li>
		<li class="fields tipopessoa-pf tipopessoa-pj">
			<?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
		</li>
		<li class="fields tipopessoa-pf tipopessoa-pj">
			<div class="field" id="cpfContainer">
				<label for="cpf" class="required"><em>*</em><?php echo $this->__('CPF') ?></label>
				<div class="input-box">
					<input type="text" name="cpf" id="cpf" value="<?php echo $this->escapeHtml($this->getFormData()->getCpf()) ?>" title="<?php echo $this->__('CPF') ?>" class="input-text validate-cpf required-entry mask-cpf" />
				</div>
			</div>
			<div class="field">
				<label for="telefone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
				<div class="input-box">
					<input type="tel" name="telefone" id="telefone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelefone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text validate-telefone required-entry" />
				</div>
			</div>
		</li>

		<?php $_dob = $this->getLayout()->createBlock('magefm_customer/widget_dob') ?>
		<?php if ($_dob->isEnabled()): ?>
			<li class="tipopessoa-pf tipopessoa-pj"><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
		<?php endif ?>

		<?php $_gender = $this->getLayout()->createBlock('magefm_customer/widget_gender') ?>
		<?php if ($_gender->isEnabled()): ?>
			<li class="tipopessoa-pf tipopessoa-pj control"><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
		<?php endif ?>
	</ul>
</div>

<div class="fieldset tipopessoa-pf" style="<?php echo ($this->getFormData()->getTipopessoa() != 'PF' ? 'display: none;' : ''); ?>">
	<h4 class="legend"><?php echo $this->__('Veterinarian Information') ?></h4>
	<ul class="form-list">
		<li class="fields">
			<div class="field">
				<label for="crmv" class="required"><em>*</em><?php echo $this->__('CRMV') ?></label>
				<div class="input-box">
					<input type="text" name="crmv" id="crmv" value="<?php echo $this->escapeHtml($this->getFormData()->getCrmv()) ?>" title="<?php echo $this->__('CRMV') ?>" class="input-text required-entry" />
				</div>
			</div>
		</li>
	</ul>
</div>

<div class="fieldset tipopessoa-pj" style="<?php echo ($this->getFormData()->getTipopessoa() != 'PJ' ? 'display: none;' : ''); ?>">
	<h4 class="legend"><?php echo $this->__('Company Information') ?></h4>
	<ul class="form-list">
		<li class="fields">
			<div class="field">
				<label for="razao_social" class="required"><em>*</em><?php echo $this->__('Razão Social') ?></label>
				<div class="input-box">
					<input type="text" name="razao_social" id="razao_social" value="<?php echo $this->escapeHtml($this->getFormData()->getRazaoSocial()) ?>" title="<?php echo $this->__('Razão Social') ?>" class="input-text required-entry" />
				</div>
			</div>
			<div class="field" id="cnpjContainer">
				<label for="cnpj" class="required"><em>*</em><?php echo $this->__('CNPJ') ?></label>
				<div class="input-box">
					<input type="text" name="cnpj" id="cnpj" value="<?php echo $this->escapeHtml($this->getFormData()->getCnpj()) ?>" title="<?php echo $this->__('CNPJ') ?>" class="input-text validate-cnpj required-entry mask-cnpj" />
				</div>
			</div>
		</li>
		<li class="fields">
			<div class="field">
				<label for="inscricao_estadual" class="required"><em>*</em><?php echo $this->__('Inscrição Estadual') ?></label>
				<div class="input-box">
					<input type="text" name="inscricao_estadual" id="inscricao_estadual" value="<?php echo $this->escapeHtml($this->getFormData()->getInscricaoEstadual()) ?>" title="<?php echo $this->__('Inscrição Estadual') ?>" class="input-text <?php echo ($this->getFormData()->getInscricaoEstadualIsento() ? '' : 'required-entry'); ?>" <?php echo ($this->getFormData()->getInscricaoEstadualIsento() ? 'disabled="disabled"' : ''); ?>/>
				</div>
			</div>
			<div class="field control">
				<div class="input-box control">
					<input type="checkbox" name="inscricao_estadual_isento" value="1" id="inscricao_estadual_isento" <?php echo ($this->getFormData()->getInscricaoEstadualIsento() ? 'checked="checked"' : ''); ?>/>
					<label for="inscricao_estadual_isento"><?php echo $this->__('Isento') ?></label>
				</div>
			</div>
		</li>
	</ul>
</div>
<div class="fieldset">
	<h4 class="legend"><?php echo $this->__('Login Information') ?></h4>
	<ul class="form-list">
		<li class="fields">
			<div class="field">
				<label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
				<input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
			</div>
			<div class="field"></div>
		</li>
		<li class="fields">
			<div class="field">
				<label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
				<div class="input-box">
					<input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
				</div>
			</div>
			<div class="field">
				<label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
				<div class="input-box">
					<input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
				</div>
			</div>
		</li>
		<?php echo $this->getChildHtml('form.additional.info'); ?>
		<?php echo $this->getChildHtml('persistent.remember.me'); ?>
	</ul>
	<?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
</div>
<div class="fieldset">
	<h4 class="legend"><?php echo $this->__('Address') ?></h4>
	<ul class="form-list">
		<li class="fields">
			<div class="field">
				<label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
				<div class="input-box">
					<input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-internationa required-entry mask-zip" data-actionbutton="#buscar-cep" />
					<br />
					<span class="please-wait" id="cep-please-wait" style="display:none;width: 100%;text-align: center">
						<br />
						<i class="fa fa-spinner fa-spin fa-2x"></i>
					</span>
				</div>
			</div>
			<div class="field">
				<label class="clean">Buscar Cep</label>
				<div class="input-box">
					<button id="buscar-cep" type="button" class="buscar-cep button medium btn-doToAction disabled"><span><span><?php echo $this->__('Get Postcode') ?></span></span></button>
				</div>
			</div>
		</li>
		<li class="fields">
			<div class="field">
				<label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
				<div class="input-box">
					<input type="hidden" name="country_id" value="BR" id="country" />
					<select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select required-entry  input-text">
						<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
						<option value="485">Acre</option>
						<option value="486">Alagoas</option>
						<option value="487">Amapá</option>
						<option value="488">Amazonas</option>
						<option value="489">Bahia</option>
						<option value="490">Ceará</option>
						<option value="491">Distrito Federal</option>
						<option value="492">Espírito Santo</option>
						<option value="493">Goiás</option>
						<option value="494">Maranhão</option>
						<option value="496">Mato Grosso do Sul</option>
						<option value="495">Mato Grosso</option>
						<option value="497">Minas Gerais</option>
						<option value="500">Paraná</option>
						<option value="499">Paraíba</option>
						<option value="498">Pará</option>
						<option value="501">Pernambuco</option>
						<option value="502">Piauí</option>
						<option value="504">Rio Grande do Norte</option>
						<option value="505">Rio Grande do Sul</option>
						<option value="503">Rio de Janeiro</option>
						<option value="506">Rondônia</option>
						<option value="507">Roraima</option>
						<option value="508">Santa Catarina</option>
						<option value="510">Sergipe</option>
						<option value="509">São Paulo</option>
						<option value="511">Tocantins</option>
					</select>
				</div>
			</div>
			<div class="field">
				<label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
				<div class="input-box">
					<input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>"  title="<?php echo $this->__('City') ?>" class="input-text required-entry" id="city" />
				</div>
			</div>
		</li>
		<li class="fields">
			<div class="field">
				<label for="bairro" class="required"><em>*</em><?php echo $this->__('Bairro') ?></label>
				<div class="input-box">
					<input type="text" name="bairro" value="<?php echo $this->escapeHtml($this->getFormData()->getBairro()) ?>" title="<?php echo $this->__('Bairro') ?>" class="input-text required-entry" id="bairro" />
				</div>
			</div>
			<div class="field">
				<label for="logradouro" class="required"><em>*</em><?php echo $this->__('Logradouro') ?></label>
				<div class="input-box">
					<input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(0)) ?>" title="<?php echo $this->__('Logradouro') ?>" class="input-text required-entry" id="logradouro" />
				</div>
			</div>
		</li>
		<li class="fields">
			<div class="field">
				<label for="numero" class="required"><em>*</em><?php echo $this->__('Número') ?></label>
				<div class="input-box">
					<input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Número') ?>" class="input-text required-entry" id="numero" />
				</div>
			</div>
			<div class="field">
				<label for="complemento"><?php echo $this->__('Complemento') ?></label>
				<div class="input-box">
					<input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(2)) ?>" title="<?php echo $this->__('Complemento') ?>" class="input-text" id="complemento" />
				</div>
			</div>
		</li>
		<li class="fields">
			<div class="field">
				<label for="referencia"><?php echo $this->__('Referência') ?></label>
				<div class="input-box">
					<input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(3)) ?>" title="<?php echo $this->__('Referência') ?>" class="input-text" id="referencia" />
				</div>
			</div>
		</li>
<?php

	if (Mage::getStoreConfig(FVets_Core_Helper_Data::XML_PATH_STORE_IS_BRAND)) :

		$_views = $_fvetsCoreHelper->getBrandStoreviews(Mage::app()->getStore()->getCode());

?>

		<li class="fields">
			<div class="field">
				<label for="supplier"  class="required">Selecione a distribuidora da sua região</label>
				<div class="input-box">
					<select id="supplier" name="created_at" class="input-text validate-select">
						<option value="">Selecione a distribuidora</option>
						<?php foreach ($_views as $_supplier) : ?>
							<option value="<?php echo $_supplier->getId(); ?>"><?php echo Mage::helper('fvets_core')->getStoreAlias($_supplier); ?></option>
						<?php endforeach; ?>
							<option value="<?php echo Mage::app()->getStore()->getId(); ?>">Outro</option>
					</select>
				</div>
			</div>
		</li>

<?php endif; ?>
	</ul>
	<input type="hidden" name="identification" value="Padrão" />
	
	<input type="hidden" name="create_address" value="1" />
	
	
	<input type="hidden" name="default_billing" value="1" />
	
	<input type="hidden" name="default_shipping" value="1" />
</div>

<div class="fieldset">
	<h4 class="legend required"><?php echo $this->__('Área de Interesse') ?><em>*</em></h4>
	<ul class="form-list">		
		<li class="control">
			<?php $count = 0;?>
			<?php foreach($areaInterestOptions as $keyOption => $itemOption): ?>
			<?php if($count == 2): ?>
		</li>
		<li class="control">
			<?php $count = 0; ?>
			<?php endif;?>
			<div class="input-box">
				<input class="areaInteresse required-entry" type="checkbox" name="area_of_interest[]" value="<?php echo $keyOption; ?>" />
				<label><?php echo $itemOption; ?></label>
			</div>
			<?php $count ++;?>
			<?php endforeach; ?>
		</li>
	</ul>
</div>

<div>
	<button type="submit" title="<?php echo $this->__('Finalize Registration') ?>" id="btn-action" class="button btn-action"><span><span><?php echo $this->__('Finalize Registration') ?></span></span></button>
</div>
<input type="hidden" name="is_subscribed" value="1" id="is_subscribed"/>
</form>
</div>

<script type="text/javascript">
	//<![CDATA[

	var regionJson = <?php echo $this->helper('directory')->getRegionJson() ?>;
	var cepUrl = '<?php echo Mage::getUrl('magefm_customer/cep/buscar', array('_secure' => true)); ?>';

	//]]>
</script>

<script type="text/javascript">
	var cnpjField = jQuery('#cnpj');
	var cpfField = jQuery('#cpf');

	jQuery('#cnpj').on('blur', function () {
		validateCnpjServerSide();
	});

	jQuery('#cpf').on('blur', function () {
		validateCpfServerSide();
	});

	jQuery('#tipopessoapj').click(function() {
		//remove possiveis mensagens de validaçao do cpf ja que nao ha validaçao de CPF quando o cliente é PJ
		jQuery('#advice-required-entry-cpf').remove();
		cpfField.removeClass('validation-failed');
	});

	jQuery('#tipopessoapf').click(function() {
		if (cpfField.val() != '') {
			validateCpfServerSide();
		}
	});

	//validate cnpj server side
	function validateCnpjServerSide() {
		var cnpjValue = cnpjField.val();
		cnpjValue = cnpjValue.replace('__.___.___/____-__', '');

		if (!cnpjValue) {
			return;
		}

		jQuery('#cnpjContainer .validation-advice').remove();

		jQuery.ajax({
			url: "<?php echo $validateCnpjUrl ?>",
			context: document.body,
			data: {cnpj: encodeURI(jQuery('#cnpj').val())}
		}).done(function (msg) {
			if (msg == 'not allowed') {
				var errorHtml = '<div class="validation-advice" id="advice-required-entry-cnpj">Este CNPJ está inválido ou já existe um cliente cadastrado com ele.</div>';
				cnpjField.addClass('validation-failed');
				if (!jQuery('#advice-required-entry-cnpj').length) {
					cnpjField.after(errorHtml);
				}
			} else {
				jQuery('#advice-required-entry-cnpj').remove();
				cnpjField.removeClass('validation-failed');
			}
		});
	}

	function validateCpfServerSide() {
		if (jQuery('#tipopessoapj').is(':checked')) {
			return;
		}
		var cpfValue = cpfField.val();
		if (!cpfValue) {
			return;
		}

		jQuery('#cpfContainer .validation-advice').remove();

		jQuery.ajax({
			url: "<?php echo $validateCpfUrl ?>",
			context: document.body,
			data: {cpf: encodeURI(jQuery('#cpf').val())}
		}).done(function (msg) {
			if (msg == 'not allowed') {
				var errorHtml = '<div class="validation-advice" id="advice-required-entry-cpf">Este CPF está inválido ou já existe um cliente (Pessoa Física) cadastrado com ele.</div>';
				cpfField.addClass('validation-failed');
				if (!jQuery('#advice-required-entry-cpf').length) {
					cpfField.after(errorHtml);
				}
			} else {
				jQuery('#advice-required-entry-cpf').remove();
				cpfField.removeClass('validation-failed');
			}
		});
	}

	//adicionando verificação no botão de finalizar cadastro sobre cnpj validado em server side
	//caso não tenha sido validado, o evento de cadastro não é permitido
	jQuery('.button.btn-action').on('click', function(event) {
		if (cpfField.hasClass('validation-failed')) {
			event.preventDefault();

			var position = jQuery("#cpf").offset();
			window.scrollTo(position.left, position.top);
		}
		if (cnpjField.hasClass('validation-failed')) {
			event.preventDefault();

			var position = jQuery("#cnpj").offset();
			window.scrollTo(position.left, position.top);
		}
	});

</script>

<?php if ($this->escapeHtml($this->getFormData()->getPostcode()) == '') : ?>
	<style>
		.hidden-no-cep {
			display: none;
		}
	</style>
<?php endif; ?>
