<?php

if($this->getRequest()->getParam('original_totals', false))    {
    $summary = $this->getChildHtml('totals');
}
else    {
    $summary = $this->getChildHtml('summary');
}


$data = array(
    'shipping_method' => $this->getChildHtml('choose-shipping-method'),
    'payment_method' => $this->getChildHtml('choose-payment-method'),
    'summary' => $summary,
	'billing_address_list' => $this->getChildHtml('billing_address')
);



echo Zend_Json::encode($data);

?>